/*
 * Spinal Code Implementation
 * Rateless codes achieving capacity on unknown channels with hash-based incremental redundancy
 * (c)2006-2025 Hawkynt
 */

// Load AlgorithmFramework (REQUIRED)

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD
    define(['../../AlgorithmFramework', '../../OpCodes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // Node.js/CommonJS
    module.exports = factory(
      require('../../AlgorithmFramework'),
      require('../../OpCodes')
    );
  } else {
    // Browser/Worker global
    factory(root.AlgorithmFramework, root.OpCodes);
  }
}((function() {
  if (typeof globalThis !== 'undefined') return globalThis;
  if (typeof window !== 'undefined') return window;
  if (typeof global !== 'undefined') return global;
  if (typeof self !== 'undefined') return self;
  throw new Error('Unable to locate global object');
})(), function (AlgorithmFramework, OpCodes) {
  'use strict';

  if (!AlgorithmFramework) {
    throw new Error('AlgorithmFramework dependency is required');
  }

  if (!OpCodes) {
    throw new Error('OpCodes dependency is required');
  }

  // Extract framework components
  const { RegisterAlgorithm, CategoryType, SecurityStatus, ComplexityType, CountryCode,
          ErrorCorrectionAlgorithm, IErrorCorrectionInstance,
          TestCase, LinkItem, Vulnerability } = AlgorithmFramework;

  // ===== ALGORITHM IMPLEMENTATION =====

  /**
   * One decoder hypothesis and its distance to the received symbols
   * @class
   */
  class SpinalCandidate {
    /**
     * @param {uint32} hypothesis - Candidate message as integer
     * @param {int32} distance - Hamming distance to the received symbols
     */
    constructor(hypothesis, distance) {
      /** @type {uint32} */
      this.message = hypothesis;
      /** @type {int32} */
      this.metric = distance;
    }
  }

  class SpinalCodeAlgorithm extends ErrorCorrectionAlgorithm {
    constructor() {
      super();

      // Required metadata (EXACT compliance with requirements)
      this.name = "Spinal Code";
      this.description = "Rateless codes achieving capacity on unknown channels. Hash-based incremental redundancy. State machine generates pseudo-random symbols. Receiver uses sequential decoding (bubble decoder). Used in WiFi and modern wireless. No feedback needed. Asymptotically capacity-achieving.";
      this.inventor = "Jonathan Perry, Hari Balakrishnan";
      this.year = 2012;
      this.category = CategoryType.ECC;
      this.subCategory = "Rateless Code";
      this.securityStatus = SecurityStatus.EDUCATIONAL;
      this.complexity = ComplexityType.EXPERT;
      this.country = CountryCode.US;

      // Documentation and references
      this.documentation = [
        new LinkItem("Spinal Codes (Perry, Iannucci, Fleming, Balakrishnan, Shah)", "https://people.eecs.berkeley.edu/~sylvia/cs268-2014/papers/spinal.pdf"),
        new LinkItem("Fountain / Rateless Codes - Wikipedia", "https://en.wikipedia.org/wiki/Fountain_code"),
        new LinkItem("Spinal Codes - Devavrat Shah publication page", "https://devavrat.mit.edu/publication/spinal-codes/"),
        new LinkItem("Shannon Capacity Theory", "https://en.wikipedia.org/wiki/Shannon%27s_source_coding_theorem")
      ];

      this.references = [
        new LinkItem("Perry, Iannucci, Fleming, Balakrishnan, Shah - Spinal Codes, ACM SIGCOMM 2012", "https://dl.acm.org/doi/10.1145/2377677.2377684"),
        new LinkItem("Information Theory and Coding", "https://en.wikipedia.org/wiki/Channel_capacity"),
        new LinkItem("Spinal Codes - Semantic Scholar entry", "https://www.semanticscholar.org/paper/Spinal-codes-Perry-Iannucci/7a70d9bf3b2194dd5df11d7ad23ebb06bd95ea9f"),
        new LinkItem("Incremental Redundancy Techniques", "https://en.wikipedia.org/wiki/Automatic_repeat_request")
      ];

      this.knownVulnerabilities = [
        new Vulnerability(
          "Decoding Complexity Exponential",
          "Bubble decoder complexity grows exponentially with message length. Practical for k=4 to k=16 bits."
        ),
        new Vulnerability(
          "Hash Function Selection",
          "Security depends on hash function properties. Poor hash functions reduce decoding efficiency."
        ),
        new Vulnerability(
          "Bubble Decoder Pruning",
          "Aggressive pruning reduces decoding quality. Requires careful threshold tuning per channel."
        )
      ];

      // Test vectors: 4 binary vectors for k=4 message bits
      // Self-computed: this implementation uses a simplified, custom murmur-like spine
      // hash (not the paper's construction), so vectors are generated by running this
      // implementation itself rather than taken from the Spinal Codes paper.
      this.tests = [
        new TestCase(
          [0, 0, 0, 0], // Message: all zeros
          [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0], // 12 coded symbols (3 passes * 4 symbols)
          "Spinal code all-zero message k=4",
          "Self-computed: this implementation's spine hash and symbol generator"
        ),
        new TestCase(
          [1, 0, 1, 0], // Message: alternating pattern
          [1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0], // Coded symbols from spine evolution
          "Spinal code alternating pattern k=4",
          "Self-computed: this implementation's spine hash and symbol generator"
        ),
        new TestCase(
          [1, 1, 1, 1], // Message: all ones
          [1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1], // Coded symbols from spine
          "Spinal code all-ones message k=4",
          "Self-computed: this implementation's spine hash and symbol generator"
        ),
        new TestCase(
          [0, 1, 0, 1], // Message: alternating different phase
          [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0], // Coded symbols from spine evolution
          "Spinal code alternating pattern phase2 k=4",
          "Self-computed: this implementation's spine hash and symbol generator"
        )
      ];
    }

    /**
   * Create new cipher instance
   * @param {boolean} [isInverse=false] - True for decryption, false for encryption
   * @returns {SpinalCodeInstance} New cipher instance
   */

    CreateInstance(isInverse = false) {
      return new SpinalCodeInstance(this, isInverse);
    }
  }

  /**
 * SpinalCode cipher instance implementing Feed/Result pattern
 * @class
 * @extends {IBlockCipherInstance}
 */

  class SpinalCodeInstance extends IErrorCorrectionInstance {
    /**
   * Initialize Algorithm cipher instance
   * @param {SpinalCodeAlgorithm} algorithm - Parent algorithm instance
   * @param {boolean} [isInverse=false] - Decryption mode flag
   */

    constructor(algorithm, isInverse = false) {
      super(algorithm);
      /** @type {boolean} */
      this.isInverse = isInverse;
      /** @type {uint8[]|null} */
      this.result = null;

      // Spinal code configuration
      /** @type {int32} */
      this.k = 4; // Message bits
      /** @type {int32} */
      this.numPasses = 3; // Number of encoding passes
      this.symbolsPerPass = 4; // Constellation symbols per pass
      this.stateSize = 2; // 2-bit state machine
      // Note: Structural state size calculation (not cryptographic)
      this.stateMaxValue = OpCodes.BitMask(this.stateSize); // 3 (0b11)

      // Bubble decoder parameters
      this.maxBubbles = 16; // Maximum decoder bubbles to explore
      this.pruneThreshold = 0.5; // Pruning threshold for weak candidates
    }

    /**
     * @param {int32} bits - Message bits (1..32)
     */
    set messageLength(bits) {
      if (bits < 1 || bits > 32) {
        throw new Error('SpinalCodeInstance.messageLength: Must be between 1 and 32 bits');
      }
      this.k = bits;
    }

    /**
     * @returns {int32} Message bits
     */
    get messageLength() {
      return this.k;
    }

    /**
     * @param {int32} count - Encoding passes (1..10)
     */
    set passes(count) {
      if (count < 1 || count > 10) {
        throw new Error('SpinalCodeInstance.passes: Must be between 1 and 10');
      }
      this.numPasses = count;
    }

    /**
     * @returns {int32} Encoding passes
     */
    get passes() {
      return this.numPasses;
    }

    /**
   * Feed data to cipher for processing
   * @param {uint8[]} data - Input data bytes
   * @throws {Error} If key not set
   */

    Feed(data) {
      if (!Array.isArray(data)) {
        throw new Error('SpinalCodeInstance.Feed: Input must be bit array');
      }

      if (this.isInverse) {
        this.result = this.decode(data);
      } else {
        this.result = this.encode(data);
      }
    }

    /**
   * Get cipher result (encrypted or decrypted data)
   * @returns {uint8[]} Processed output bytes
   * @throws {Error} If key not set, no data fed, or invalid input length
   */

    Result() {
      if (this.result === null) {
        throw new Error('SpinalCodeInstance.Result: Call Feed() first to process data');
      }
      return this.result;
    }

    /**
     * Encodes message bits using spinal code with hash-based spine
     * @param {uint8[]} messageBits - k information bits
     * @returns {uint8[]} - Encoded symbols (numPasses * symbolsPerPass)
     */
    encode(messageBits) {
      if (messageBits.length !== this.k) {
        throw new Error("Spinal encode: Input must be exactly " + this.k + " bits");
      }

      // Convert message bits to integer
      /** @type {uint32} */
      const message = this._bitsToInt(messageBits);

      // Initialize spine state
      /** @type {uint32} */
      let spineState = 0;

      // Generate coded symbols through multiple passes
      /** @type {uint8[]} */
      const coded = [];

      for (let pass = 0; pass < this.numPasses; ++pass) {
        // Update spine state using hash function
        spineState = this._updateSpine(spineState, message, pass);

        // Generate constellation symbols from spine state
        for (let sym = 0; sym < this.symbolsPerPass; ++sym) {
          // Extract symbol from spine state using pseudo-random mapping
          /** @type {uint8} */
          const symbol = this._generateSymbol(spineState, sym);
          coded.push(symbol);
        }
      }

      return coded;
    }

    /**
     * Decodes received symbols using bubble decoder (sequential decoding)
     * @param {uint8[]} received - Received coded symbols
     * @returns {uint8[]} - Decoded message bits
     */
    decode(received) {
      if (received.length !== (this.numPasses * this.symbolsPerPass)) {
        throw new Error(
          "Spinal decode: Input must be exactly " + (this.numPasses * this.symbolsPerPass) + " symbols"
        );
      }

      // Bubble decoder: explore likely message hypotheses using sequential decoding
      /** @type {SpinalCandidate[]} */
      const candidates = this._bubbleDecoder(received);

      if (candidates.length === 0) {
        throw new Error('SpinalCodeInstance.decode: No valid candidate found');
      }

      // Return best candidate as bits
      /** @type {uint32} */
      const bestMessage = candidates[0].message;
      return this._intToBits(bestMessage, this.k);
    }

    /**
     * Bubble decoder: sequential decoder exploring most likely candidates
     * @param {uint8[]} received - Received symbols
     * @returns {SpinalCandidate[]} - Candidates [{message, metric}, ...] sorted by likelihood
     */
    _bubbleDecoder(received) {
      /** @type {SpinalCandidate[]} */
      const candidates = [];

      // Generate all possible messages (brute-force for small k)
      // Note: Structural message space calculation
      const totalMessages = OpCodes.Shl32(1, this.k);

      for (let msg = 0; msg < totalMessages; ++msg) {
        // Compute expected coded sequence for this message
        /** @type {uint8[]} */
        const expected = this._generateCodedSequence(msg);

        // Compute likelihood metric (Hamming distance or soft metric)
        /** @type {int32} */
        let metric = 0;
        for (let i = 0; i < received.length; ++i) {
          metric += (received[i] !== expected[i]) ? 1 : 0;
        }

        candidates.push(new SpinalCandidate(msg, metric));

        // Prune if too many candidates
        if (candidates.length > this.maxBubbles) {
          this._sortByMetric(candidates);
          candidates.splice(this.maxBubbles);
        }
      }

      // Sort by metric (lower is better)
      this._sortByMetric(candidates);

      return candidates;
    }

    /**
     * Stable ascending sort by metric (equal metrics keep their order)
     * @param {SpinalCandidate[]} candidates - Sorted in place
     * @returns {void}
     */
    _sortByMetric(candidates) {
      for (let i = 1; i < candidates.length; ++i) {
        /** @type {SpinalCandidate} */
        const current = candidates[i];
        let j = i - 1;
        while (j >= 0 && candidates[j].metric > current.metric) {
          candidates[j + 1] = candidates[j];
          --j;
        }
        candidates[j + 1] = current;
      }
    }

    /**
     * Generate complete coded sequence for a message
     * @param {uint32} message - Message as integer
     * @returns {uint8[]} - Expected coded symbols
     */
    _generateCodedSequence(message) {
      /** @type {uint32} */
      let spineState = 0;
      /** @type {uint8[]} */
      const coded = [];

      for (let pass = 0; pass < this.numPasses; ++pass) {
        spineState = this._updateSpine(spineState, message, pass);

        for (let sym = 0; sym < this.symbolsPerPass; ++sym) {
          /** @type {uint8} */
          const symbol = this._generateSymbol(spineState, sym);
          coded.push(symbol);
        }
      }

      return coded;
    }

    /**
     * Update spine state using hash function
     * XOR-based hash for spine evolution to create pseudo-random symbols
     * Note: Uses bitwise operations for hash computation (structural, not cryptographic)
     * @param {uint32} currentState - Current spine state
     * @param {uint32} message - Message integer
     * @param {int32} pass - Current pass index
     * @returns {uint32} - Updated spine state
     */
    _updateSpine(currentState, message, pass) {
      // Hash-based spine update: XOR previous state with message and pass
      // This creates deterministic but pseudo-random symbols based on message content
      /** @type {uint32} */
      let hash = currentState;

      // Mix in message bits
      // Note: XOR operation for hash mixing (structural algorithm component)
      hash = this._simpleHash(OpCodes.Xor32(hash, message));

      // Mix in pass number for variation
      // Note: Structural pass encoding
      hash = this._simpleHash(OpCodes.Xor32(hash, OpCodes.Shl32(pass, 16)));

      // Mix in state to ensure evolution
      // Note: Structural state mixing
      hash = this._simpleHash(OpCodes.Xor32(hash, OpCodes.Shl32(currentState, 8)));

      // Mask to 32-bit boundary (structural)
      return OpCodes.ToUint32(hash);
    }

    /**
     * Simple hash function (murmurhash-like)
     * Note: Uses bitwise operations for hash mixing (structural, not cryptographic)
     * @param {uint32} value - Input value
     * @returns {uint32} - Hashed value
     */
    _simpleHash(value) {
      // Murmurhash-inspired mixing function for spine state generation
      // These bitwise operations are for structural algorithm implementation
      value = OpCodes.Xor32(OpCodes.Xor32(value, 61), OpCodes.Shr32(value, 16)); // XOR and shift for mixing
      value = OpCodes.ToUint32(value + OpCodes.Shl32(value, 3)); // Shift and add for distribution
      value = OpCodes.Xor32(value, OpCodes.Shr32(value, 4)); // XOR and shift for avalanche effect
      // Multiply with magic constant (structural); (value|0) matches native signed-int32
      // multiplication semantics so double-precision rounding stays bit-identical.
      value = OpCodes.ToUint32((value|0) * 0x27d4eb2d);
      value = OpCodes.Xor32(value, OpCodes.Shr32(value, 15)); // Final XOR and shift
      return OpCodes.ToUint32(value);
    }

    /**
     * Generate symbol from spine state using constellation mapping
     * Note: Uses bitwise operations for symbol extraction (structural)
     * @param {uint32} spineState - Current spine state
     * @param {int32} symbolIndex - Index within pass
     * @returns {uint8} - Symbol (0 or 1 for binary)
     */
    _generateSymbol(spineState, symbolIndex) {
      // Extract bit from spine state at pseudo-random position
      // Note: Shifts and mask for symbol position calculation (structural)
      /** @type {uint32} */
      const bitPosition = OpCodes.And32(OpCodes.Add32(OpCodes.Shr32(spineState, symbolIndex), OpCodes.Shr32(spineState, symbolIndex + 8)), 31);
      return OpCodes.GetBit(spineState, bitPosition) ? 1 : 0;
    }

    /**
     * Convert bit array to integer
     * Note: Uses bitwise operations for bit packing (structural)
     * @param {uint8[]} bits - Bit array
     * @returns {uint32} - Integer value
     */
    _bitsToInt(bits) {
      /** @type {uint32} */
      let value = 0;
      for (let i = 0; i < bits.length; ++i) {
        // Note: Structural bit packing
        if (bits[i])
          value = OpCodes.SetBit(value, i, true);
      }
      return OpCodes.ToUint32(value);
    }

    /**
     * Convert integer to bit array
     * Note: Uses bitwise operations for bit unpacking (structural)
     * @param {uint32} value - Integer value
     * @param {int32} numBits - Number of bits to extract
     * @returns {uint8[]} - Bit array
     */
    _intToBits(value, numBits) {
      /** @type {uint8[]} */
      const bits = [];
      for (let i = 0; i < numBits; ++i) {
        // Note: Structural bit extraction
        bits.push(OpCodes.GetBit(value, i) ? 1 : 0);
      }
      return bits;
    }

    /**
     * Detects errors by comparing re-encoded sequence
     * @param {uint8[]} received - Received symbols
     * @returns {boolean} - True if error detected
     */
    DetectError(received) {
      if (!Array.isArray(received) || received.length !== (this.numPasses * this.symbolsPerPass)) {
        throw new Error('SpinalCodeInstance.DetectError: Invalid input length');
      }

      try {
        /** @type {uint8[]} */
        const decoded = this.decode(received);
        /** @type {uint8[]} */
        const reencoded = this._generateCodedSequence(this._bitsToInt(decoded));

        // Check if re-encoding matches received
        for (let i = 0; i < received.length; ++i) {
          if (reencoded[i] !== received[i]) {
            return true; // Error detected
          }
        }
        return false; // No error detected
      } catch (e) {
        return true; // Error in decoding indicates corruption
      }
    }
  }

  // ===== REGISTRATION =====

  const algorithmInstance = new SpinalCodeAlgorithm();
  if (!AlgorithmFramework.Find(algorithmInstance.name)) {
    RegisterAlgorithm(algorithmInstance);
  }

  // ===== EXPORTS =====

  return { SpinalCodeAlgorithm, SpinalCodeInstance };
}));
