;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});

  SZ.manifest = {
    applications: [
      {
        id: 'explorer',
        title: 'Explorer',
        icon: 'System/explorer/icon.svg',
        type: 'iframe',
        entry: 'System/explorer/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false
      },
      {
        id: 'task-manager',
        title: 'Task Manager',
        icon: 'System/task-manager/icon.svg',
        type: 'iframe',
        entry: 'System/task-manager/index.html',
        width: 500,
        height: 420,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        hidden: true
      },
      {
        id: 'about',
        title: 'About \u00BBSynthelicZ\u00AB',
        icon: 'Accessories/about/icon.svg',
        type: 'iframe',
        entry: 'Accessories/about/index.html',
        width: 440,
        height: 550,
        resizable: false,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Accessories'
      },
      {
        id: 'control-panel',
        title: 'Control Panel',
        icon: 'System/control-panel/icon.svg',
        type: 'iframe',
        entry: 'System/control-panel/index.html',
        width: 600,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        hidden: true
      },
      {
        id: 'encryptor',
        title: 'Data Encryption',
        icon: 'Accessories/encryptor/icon.svg',
        type: 'iframe',
        entry: 'Accessories/encryptor/index.html',
        width: 520,
        height: 420,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Accessories'
      },
      {
        id: 'calculator',
        title: 'Calculator',
        icon: 'Office/calculator/icon.svg',
        type: 'iframe',
        entry: 'Office/calculator/index.html',
        width: 260,
        height: 340,
        resizable: false,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Office'
      },
      {
        id: 'minesweeper',
        title: 'Minesweeper',
        icon: 'Games/minesweeper/icon.svg',
        type: 'iframe',
        entry: 'Games/minesweeper/index.html',
        width: 200,
        height: 260,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'notepad',
        title: 'Notepad',
        icon: 'Office/notepad/icon.svg',
        type: 'iframe',
        entry: 'Office/notepad/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['*']
      },
      {
        id: 'image-viewer',
        title: 'Image Viewer',
        icon: 'Graphics/image-viewer/icon.svg',
        type: 'iframe',
        entry: 'Graphics/image-viewer/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['bmp', 'png', 'jpg', 'jpeg', 'jp2', 'gif', 'webp', 'tif', 'tiff', 'tga', 'pcx', 'svg', 'ico', 'avif']
      },
      {
        id: 'paint',
        title: 'Paint',
        icon: 'Graphics/paint/icon.svg',
        type: 'iframe',
        entry: 'Graphics/paint/index.html',
        width: 800,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['bmp', 'png', 'jpg', 'jpeg', 'gif', 'webp']
      },
      {
        id: 'terminal',
        title: 'Terminal',
        icon: 'System Tools/terminal/icon.svg',
        type: 'iframe',
        entry: 'System Tools/terminal/index.html',
        width: 680,
        height: 440,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'System Tools'
      },
      {
        id: 'tetris',
        title: 'Tetris',
        icon: 'Games/tetris/icon.svg',
        type: 'iframe',
        entry: 'Games/tetris/index.html',
        width: 360,
        height: 480,
        resizable: false,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'media-player',
        title: 'Media Player',
        icon: 'Entertainment/media-player/icon.svg',
        type: 'iframe',
        entry: 'Entertainment/media-player/index.html',
        width: 720,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Entertainment',
        fileTypes: ['mp3', 'wav', 'ogg', 'mp4', 'webm', 'flac', 'm4a']
      },
      {
        id: 'wordpad',
        title: 'WordPad',
        icon: 'Office/wordpad/icon.svg',
        type: 'iframe',
        entry: 'Office/wordpad/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['rtf', 'doc', 'docx']
      },
      {
        id: 'web-browser',
        title: 'Web Browser',
        icon: 'Internet/web-browser/icon.svg',
        type: 'iframe',
        entry: 'Internet/web-browser/index.html',
        width: 800,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Internet',
        fileTypes: ['html', 'htm']
      },
      {
        id: 'color-picker',
        title: 'Color Picker',
        icon: 'Graphics/color-picker/icon.svg',
        type: 'iframe',
        entry: 'Graphics/color-picker/index.html',
        width: 480,
        height: 460,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Graphics'
      },
      {
        id: 'markdown-editor',
        title: 'Markdown Editor',
        icon: 'Office/markdown-editor/icon.svg',
        type: 'iframe',
        entry: 'Office/markdown-editor/index.html',
        width: 900,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['md', 'markdown']
      },
      {
        id: 'hex-editor',
        title: 'Hex Editor',
        icon: 'Development/hex-editor/icon.svg',
        type: 'iframe',
        entry: 'Development/hex-editor/index.html',
        width: 700,
        height: 450,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['*']
      },
      {
        id: 'spreadsheet',
        title: 'Spreadsheet',
        icon: 'Office/spreadsheet/icon.svg',
        type: 'iframe',
        entry: 'Office/spreadsheet/index.html',
        width: 800,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['csv', 'tsv', 'xlsx', 'xls']
      },
      {
        id: 'font-viewer',
        title: 'Font Viewer',
        icon: 'Graphics/font-viewer/icon.svg',
        type: 'iframe',
        entry: 'Graphics/font-viewer/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Graphics',
        fileTypes: ['ttf', 'otf', 'woff', 'woff2']
      },
      {
        id: 'font-pairing',
        title: 'Font Pairing Tool',
        icon: 'Graphics/font-pairing/icon.svg',
        type: 'iframe',
        entry: 'Graphics/font-pairing/index.html',
        width: 950,
        height: 650,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Graphics'
      },
      {
        id: 'json-viewer',
        title: 'JSON Viewer',
        icon: 'Development/json-viewer/icon.svg',
        type: 'iframe',
        entry: 'Development/json-viewer/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['json']
      },
      {
        id: 'regex-tester',
        title: 'Regex Tester',
        icon: 'Development/regex-tester/icon.svg',
        type: 'iframe',
        entry: 'Development/regex-tester/index.html',
        width: 750,
        height: 550,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'diff-viewer',
        title: 'Diff Viewer',
        icon: 'Development/diff-viewer/icon.svg',
        type: 'iframe',
        entry: 'Development/diff-viewer/index.html',
        width: 800,
        height: 550,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['diff', 'patch']
      },
      {
        id: 'clock',
        title: 'Date and Time',
        icon: 'Accessories/clock/icon.svg',
        type: 'iframe',
        entry: 'Accessories/clock/index.html',
        width: 420,
        height: 380,
        resizable: true,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Accessories',
        hidden: true
      },
      {
        id: 'qr-generator',
        title: 'QR Code Generator',
        icon: 'Accessories/qr-generator/icon.svg',
        type: 'iframe',
        entry: 'Accessories/qr-generator/index.html',
        width: 650,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Accessories'
      },
      {
        id: 'skin-tester',
        title: 'Skin Tester',
        icon: 'System Tools/skin-tester/icon.svg',
        type: 'iframe',
        entry: 'System Tools/skin-tester/index.html',
        width: 800,
        height: 650,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'System Tools'
      },
      {
        id: 'icon-editor',
        title: 'Icon Editor',
        icon: 'Graphics/icon-editor/icon.svg',
        type: 'iframe',
        entry: 'Graphics/icon-editor/index.html',
        width: 800,
        height: 550,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['ico', 'cur']
      },
      {
        id: 'function-plotter',
        title: 'Function Plotter',
        icon: 'Office/function-plotter/icon.svg',
        type: 'iframe',
        entry: 'Office/function-plotter/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office'
      },
      {
        id: 'svg-editor',
        title: 'SVG Editor',
        icon: 'Graphics/svg-editor/icon.svg',
        type: 'iframe',
        entry: 'Graphics/svg-editor/index.html',
        width: 980,
        height: 680,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['svg']
      },
      {
        id: 'cron-visualizer',
        title: 'Cron Visualizer',
        icon: 'Development/cron-visualizer/icon.svg',
        type: 'iframe',
        entry: 'Development/cron-visualizer/index.html',
        width: 1100,
        height: 720,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['cron', 'crontab']
      },
      {
        id: 'subnet-calculator',
        title: 'Subnet Calculator',
        icon: 'Development/subnet-calculator/icon.svg',
        type: 'iframe',
        entry: 'Development/subnet-calculator/index.html',
        width: 750,
        height: 650,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'gradient-generator',
        title: 'Gradient Generator',
        icon: 'Development/gradient-generator/icon.svg',
        type: 'iframe',
        entry: 'Development/gradient-generator/index.html',
        width: 660,
        height: 560,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'readme-generator',
        title: 'README Generator',
        icon: 'Development/readme-generator/icon.svg',
        type: 'iframe',
        entry: 'Development/readme-generator/index.html',
        width: 900,
        height: 620,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['md', 'markdown']
      },
      {
        id: 'cookie-banner',
        title: 'Cookie Banner Generator',
        icon: 'Development/cookie-banner/icon.svg',
        type: 'iframe',
        entry: 'Development/cookie-banner/index.html',
        width: 780,
        height: 620,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'display-tester',
        title: 'Display Tester',
        icon: 'System Tools/display-tester/icon.svg',
        type: 'iframe',
        entry: 'System Tools/display-tester/index.html',
        width: 1024,
        height: 768,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'System Tools'
      },
      {
        id: 'resume-builder',
        title: 'Resume Builder',
        icon: 'Office/resume-builder/icon.svg',
        type: 'iframe',
        entry: 'Office/resume-builder/index.html',
        width: 950,
        height: 650,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['md', 'markdown']
      },
      {
        id: 'archiver',
        title: 'Archiver',
        icon: 'System Tools/archiver/icon.svg',
        type: 'iframe',
        entry: 'System Tools/archiver/index.html',
        width: 750,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'System Tools',
        fileTypes: ['zip', 'gz', 'tar', 'tgz', 'bz2', 'xz', 'zst', 'b64', 'rar', '7z', 'lzh', 'lha', 'arj', 'sqx', 'cpio', 'cab', 'iso', 'z', 'rpm', 'deb', 'jar', 'war', 'ear', 'apk', 'epub', 'docx', 'xlsx', 'pptx', 'odt', 'ods', 'odp', 'zipx', 'lzma', 'lz', 'lzo', 'uue', 'uu', 'tlz', 'a', 'ar', 'lib', 'arc', 'zoo', 'ha', 'ace', 'sit', 'sitx', 'pak', 'shar', 'wim', 'esd', 'xar', 'pkg', 'msi', 'chm', 'dmg', 'squashfs', 'cramfs', 'udf', 'fat', 'ntfs', 'ext2', 'ext3', 'ext4', 'hfs', 'apfs', 'qcow2', 'vhd', 'vhdx', 'vdi', 'vmdk', 'hex', 'ihex', 'par', 'par2', 'mar', 'alz', 'pea']
      },
      {
        id: 'properties',
        title: 'Properties',
        type: 'hosted',
        entry: 'System/properties/app.js',
        width: 420,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: false,
        singleton: false,
        hidden: true
      },
      {
        id: 'metadata-viewer',
        title: 'Metadata Viewer',
        icon: 'Development/metadata-viewer/icon.svg',
        type: 'iframe',
        entry: 'Development/metadata-viewer/index.html',
        width: 850,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['*']
      },
      {
        id: 'mock-data',
        title: 'Mock Data Generator',
        icon: 'Development/mock-data/icon.svg',
        type: 'iframe',
        entry: 'Development/mock-data/index.html',
        width: 900,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development'
      },
      {
        id: 'email-signature',
        title: 'E-Mail Signature Generator',
        icon: 'Office/email-signature/icon.svg',
        type: 'iframe',
        entry: 'Office/email-signature/index.html',
        width: 880,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Office'
      },
      {
        id: 'snake',
        title: 'Snake',
        icon: 'Games/snake/icon.svg',
        type: 'iframe',
        entry: 'Games/snake/index.html',
        width: 420,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'breakout',
        title: 'Breakout',
        icon: 'Games/breakout/icon.svg',
        type: 'iframe',
        entry: 'Games/breakout/index.html',
        width: 508,
        height: 640,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'space-invaders',
        title: 'Space Invaders',
        icon: 'Games/space-invaders/icon.svg',
        type: 'iframe',
        entry: 'Games/space-invaders/index.html',
        width: 480,
        height: 540,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'asteroids',
        title: 'Asteroids',
        icon: 'Games/asteroids/icon.svg',
        type: 'iframe',
        entry: 'Games/asteroids/index.html',
        width: 560,
        height: 620,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'pacman',
        title: 'Pac-Man',
        icon: 'Games/pacman/icon.svg',
        type: 'iframe',
        entry: 'Games/pacman/index.html',
        width: 470,
        height: 560,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'flappy-bird',
        title: 'Flappy Bird',
        icon: 'Games/flappy-bird/icon.svg',
        type: 'iframe',
        entry: 'Games/flappy-bird/index.html',
        width: 420,
        height: 640,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'cookie-clicker',
        title: 'Cookie Clicker',
        icon: 'Games/cookie-clicker/icon.svg',
        type: 'iframe',
        entry: 'Games/cookie-clicker/index.html',
        width: 840,
        height: 640,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'endless-runner',
        title: 'Endless Runner',
        icon: 'Games/endless-runner/icon.svg',
        type: 'iframe',
        entry: 'Games/endless-runner/index.html',
        width: 420,
        height: 640,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'space-combat',
        title: 'Space Combat',
        icon: 'Games/space-combat/icon.svg',
        type: 'iframe',
        entry: 'Games/space-combat/index.html',
        width: 620,
        height: 660,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'bomberman',
        title: 'Bomberman',
        icon: 'Games/bomberman/icon.svg',
        type: 'iframe',
        entry: 'Games/bomberman/index.html',
        width: 640,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'boulder-dash',
        title: 'Boulder Dash',
        icon: 'Games/boulder-dash/icon.svg',
        type: 'iframe',
        entry: 'Games/boulder-dash/index.html',
        width: 1000,
        height: 620,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'bubble-bobble',
        title: 'Bubble Bobble',
        icon: 'Games/bubble-bobble/icon.svg',
        type: 'iframe',
        entry: 'Games/bubble-bobble/index.html',
        width: 560,
        height: 540,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'platformer',
        title: 'Platformer',
        icon: 'Games/platformer/icon.svg',
        type: 'iframe',
        entry: 'Games/platformer/index.html',
        width: 700,
        height: 560,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'space-puzzle',
        title: 'Space Puzzle',
        icon: 'Games/space-puzzle/icon.svg',
        type: 'iframe',
        entry: 'Games/space-puzzle/index.html',
        width: 700,
        height: 560,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'space-mining',
        title: 'Space Mining',
        icon: 'Games/space-mining/icon.svg',
        type: 'iframe',
        entry: 'Games/space-mining/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'space-racing',
        title: 'Space Racing',
        icon: 'Games/space-racing/icon.svg',
        type: 'iframe',
        entry: 'Games/space-racing/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'space-farming',
        title: 'Space Farming',
        icon: 'Games/space-farming/icon.svg',
        type: 'iframe',
        entry: 'Games/space-farming/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'dome-keeper',
        title: 'Dome Keeper',
        icon: 'Games/dome-keeper/icon.svg',
        type: 'iframe',
        entry: 'Games/dome-keeper/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'fantasy-puzzle',
        title: 'Fantasy Puzzle',
        icon: 'Games/fantasy-puzzle/icon.svg',
        type: 'iframe',
        entry: 'Games/fantasy-puzzle/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'physics-puzzle',
        title: 'Physics Puzzle',
        icon: 'Games/physics-puzzle/icon.svg',
        type: 'iframe',
        entry: 'Games/physics-puzzle/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'mind-puzzle',
        title: 'Mind-Bending Puzzle',
        icon: 'Games/mind-puzzle/icon.svg',
        type: 'iframe',
        entry: 'Games/mind-puzzle/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'illusion-puzzle',
        title: 'Optical Illusion Puzzle',
        icon: 'Games/illusion-puzzle/icon.svg',
        type: 'iframe',
        entry: 'Games/illusion-puzzle/index.html',
        width: 740,
        height: 580,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'tower-defense',
        title: 'Tower Defense',
        icon: 'Games/tower-defense/icon.svg',
        type: 'iframe',
        entry: 'Games/tower-defense/index.html',
        width: 840,
        height: 640,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'fantasy-cards',
        title: 'Fantasy Cards',
        icon: 'Games/fantasy-cards/icon.svg',
        type: 'iframe',
        entry: 'Games/fantasy-cards/index.html',
        width: 840,
        height: 640,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'card-games',
        title: 'Card Games Suite',
        icon: 'Games/card-games/icon.svg',
        type: 'iframe',
        entry: 'Games/card-games/index.html',
        width: 940,
        height: 680,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'cooking-game',
        title: 'Cooking Game',
        icon: 'Games/cooking-game/icon.svg',
        type: 'iframe',
        entry: 'Games/cooking-game/index.html',
        width: 940,
        height: 680,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'rhythm-game',
        title: 'Rhythm Game',
        icon: 'Games/rhythm-game/icon.svg',
        type: 'iframe',
        entry: 'Games/rhythm-game/index.html',
        width: 940,
        height: 700,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'presentations',
        title: 'Presentations',
        icon: 'Office/presentations/icon.svg',
        type: 'iframe',
        entry: 'Office/presentations/index.html',
        width: 960,
        height: 640,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['pptx']
      },
      {
        id: 'tactical-realms',
        title: 'Tactical Realms',
        icon: 'Games/tactical-realms/icon.svg',
        type: 'iframe',
        entry: 'Games/tactical-realms/index.html',
        width: 940,
        height: 700,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      }
    ]
  };
})();
