;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});

  SZ.manifest = {
    applications: [
      {
        id: 'explorer',
        title: 'Explorer',
        icon: 'explorer/icon.svg',
        type: 'iframe',
        entry: 'explorer/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false
      },
      {
        id: 'task-manager',
        title: 'Task Manager',
        icon: 'task-manager/icon.svg',
        type: 'iframe',
        entry: 'task-manager/index.html',
        width: 500,
        height: 420,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        hidden: true
      },
      {
        id: 'about',
        title: 'About \u00BBSynthelicZ\u00AB',
        icon: 'about/icon.svg',
        type: 'iframe',
        entry: 'about/index.html',
        width: 440,
        height: 550,
        resizable: false,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Accessories'
      },
      {
        id: 'control-panel',
        title: 'Control Panel',
        icon: 'control-panel/icon.svg',
        type: 'iframe',
        entry: 'control-panel/index.html',
        width: 600,
        height: 450,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        hidden: true
      },
      {
        id: 'encryptor',
        title: 'Data Encryption',
        icon: 'encryptor/icon.svg',
        type: 'iframe',
        entry: 'encryptor/index.html',
        width: 520,
        height: 420,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Accessories'
      },
      {
        id: 'calculator',
        title: 'Calculator',
        icon: 'calculator/icon.svg',
        type: 'iframe',
        entry: 'calculator/index.html',
        width: 260,
        height: 340,
        resizable: false,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Office'
      },
      {
        id: 'minesweeper',
        title: 'Minesweeper',
        icon: 'minesweeper/icon.svg',
        type: 'iframe',
        entry: 'minesweeper/index.html',
        width: 200,
        height: 260,
        resizable: false,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'notepad',
        title: 'Notepad',
        icon: 'notepad/icon.svg',
        type: 'iframe',
        entry: 'notepad/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['txt', 'log', 'cfg', 'ini', 'bat', 'cmd', 'sh', 'js', 'css', 'xml', 'py', 'rb', 'pl', 'java', 'cs', 'cpp', 'c', 'h', 'ts', 'tsx', 'jsx', 'yml', 'yaml', 'toml', 'conf', 'env', 'gitignore', 'sql', 'json', 'md', 'markdown', 'csv', 'tsv', 'html', 'htm']
      },
      {
        id: 'paint',
        title: 'Paint',
        icon: 'paint/icon.svg',
        type: 'iframe',
        entry: 'paint/index.html',
        width: 800,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['bmp', 'png', 'jpg', 'jpeg', 'gif', 'webp']
      },
      {
        id: 'terminal',
        title: 'Terminal',
        icon: 'terminal/icon.svg',
        type: 'iframe',
        entry: 'terminal/index.html',
        width: 680,
        height: 440,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'System Tools'
      },
      {
        id: 'tetris',
        title: 'Tetris',
        icon: 'tetris/icon.svg',
        type: 'iframe',
        entry: 'tetris/index.html',
        width: 360,
        height: 480,
        resizable: false,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'media-player',
        title: 'Media Player',
        icon: 'media-player/icon.svg',
        type: 'iframe',
        entry: 'media-player/index.html',
        width: 720,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Entertainment',
        fileTypes: ['mp3', 'wav', 'ogg', 'mp4', 'webm', 'flac', 'm4a']
      },
      {
        id: 'solitaire',
        title: 'Solitaire',
        icon: 'solitaire/icon.svg',
        type: 'iframe',
        entry: 'solitaire/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'freecell',
        title: 'FreeCell',
        icon: 'freecell/icon.svg',
        type: 'iframe',
        entry: 'freecell/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'spider-solitaire',
        title: 'Spider Solitaire',
        icon: 'spider-solitaire/icon.svg',
        type: 'iframe',
        entry: 'spider-solitaire/index.html',
        width: 800,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Games'
      },
      {
        id: 'image-viewer',
        title: 'Image Viewer',
        icon: 'image-viewer/icon.svg',
        type: 'iframe',
        entry: 'image-viewer/index.html',
        width: 640,
        height: 480,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['png', 'jpg', 'jpeg', 'gif', 'webp']
      },
      {
        id: 'wordpad',
        title: 'WordPad',
        icon: 'wordpad/icon.svg',
        type: 'iframe',
        entry: 'wordpad/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['rtf', 'doc', 'docx']
      },
      {
        id: 'web-browser',
        title: 'Web Browser',
        icon: 'web-browser/icon.svg',
        type: 'iframe',
        entry: 'web-browser/index.html',
        width: 800,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Internet',
        fileTypes: ['html', 'htm']
      },
      {
        id: 'color-picker',
        title: 'Color Picker',
        icon: 'color-picker/icon.svg',
        type: 'iframe',
        entry: 'color-picker/index.html',
        width: 480,
        height: 400,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Graphics'
      },
      {
        id: 'markdown-editor',
        title: 'Markdown Editor',
        icon: 'markdown-editor/icon.svg',
        type: 'iframe',
        entry: 'markdown-editor/index.html',
        width: 900,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['md', 'markdown']
      },
      {
        id: 'hex-editor',
        title: 'Hex Editor',
        icon: 'hex-editor/icon.svg',
        type: 'iframe',
        entry: 'hex-editor/index.html',
        width: 700,
        height: 450,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['bin', 'dat', 'exe', 'dll', 'rom']
      },
      {
        id: 'spreadsheet',
        title: 'Spreadsheet',
        icon: 'spreadsheet/icon.svg',
        type: 'iframe',
        entry: 'spreadsheet/index.html',
        width: 800,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['csv', 'tsv', 'xlsx', 'xls']
      },
      {
        id: 'font-viewer',
        title: 'Font Viewer',
        icon: 'font-viewer/icon.svg',
        type: 'iframe',
        entry: 'font-viewer/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Graphics',
        fileTypes: ['ttf', 'otf', 'woff', 'woff2']
      },
      {
        id: 'json-viewer',
        title: 'JSON Viewer',
        icon: 'json-viewer/icon.svg',
        type: 'iframe',
        entry: 'json-viewer/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['json']
      },
      {
        id: 'regex-tester',
        title: 'Regex Tester',
        icon: 'regex-tester/icon.svg',
        type: 'iframe',
        entry: 'regex-tester/index.html',
        width: 750,
        height: 550,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'diff-viewer',
        title: 'Diff Viewer',
        icon: 'diff-viewer/icon.svg',
        type: 'iframe',
        entry: 'diff-viewer/index.html',
        width: 800,
        height: 550,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['diff', 'patch']
      },
      {
        id: 'clock',
        title: 'Date and Time',
        icon: 'clock/icon.svg',
        type: 'iframe',
        entry: 'clock/index.html',
        width: 420,
        height: 380,
        resizable: true,
        minimizable: true,
        maximizable: false,
        singleton: true,
        category: 'Accessories',
        hidden: true
      },
      {
        id: 'qr-generator',
        title: 'QR Code Generator',
        icon: 'qr-generator/icon.svg',
        type: 'iframe',
        entry: 'qr-generator/index.html',
        width: 650,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Accessories'
      },
      {
        id: 'skin-tester',
        title: 'Skin Tester',
        icon: 'skin-tester/icon.svg',
        type: 'iframe',
        entry: 'skin-tester/index.html',
        width: 800,
        height: 650,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'System Tools'
      },
      {
        id: 'icon-editor',
        title: 'Icon Editor',
        icon: 'icon-editor/icon.svg',
        type: 'iframe',
        entry: 'icon-editor/index.html',
        width: 800,
        height: 550,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['ico', 'cur']
      },
      {
        id: 'function-plotter',
        title: 'Function Plotter',
        icon: 'function-plotter/icon.svg',
        type: 'iframe',
        entry: 'function-plotter/index.html',
        width: 700,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office'
      },
      {
        id: 'svg-editor',
        title: 'SVG Editor',
        icon: 'svg-editor/icon.svg',
        type: 'iframe',
        entry: 'svg-editor/index.html',
        width: 980,
        height: 680,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Graphics',
        fileTypes: ['svg']
      },
      {
        id: 'cron-visualizer',
        title: 'Cron Visualizer',
        icon: 'cron-visualizer/icon.svg',
        type: 'iframe',
        entry: 'cron-visualizer/index.html',
        width: 1100,
        height: 720,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['cron', 'crontab']
      },
      {
        id: 'subnet-calculator',
        title: 'Subnet Calculator',
        icon: 'subnet-calculator/icon.svg',
        type: 'iframe',
        entry: 'subnet-calculator/index.html',
        width: 750,
        height: 650,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'gradient-generator',
        title: 'Gradient Generator',
        icon: 'gradient-generator/icon.svg',
        type: 'iframe',
        entry: 'gradient-generator/index.html',
        width: 660,
        height: 560,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'readme-generator',
        title: 'README Generator',
        icon: 'readme-generator/icon.svg',
        type: 'iframe',
        entry: 'readme-generator/index.html',
        width: 900,
        height: 620,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development',
        fileTypes: ['md', 'markdown']
      },
      {
        id: 'cookie-banner',
        title: 'Cookie Banner Generator',
        icon: 'cookie-banner/icon.svg',
        type: 'iframe',
        entry: 'cookie-banner/index.html',
        width: 780,
        height: 620,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'Development'
      },
      {
        id: 'display-tester',
        title: 'Display Tester',
        icon: 'display-tester/icon.svg',
        type: 'iframe',
        entry: 'display-tester/index.html',
        width: 1024,
        height: 768,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: true,
        category: 'System Tools'
      },
      {
        id: 'resume-builder',
        title: 'Resume Builder',
        icon: 'resume-builder/icon.svg',
        type: 'iframe',
        entry: 'resume-builder/index.html',
        width: 950,
        height: 650,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Office',
        fileTypes: ['md', 'markdown']
      },
      {
        id: 'archiver',
        title: 'Archiver',
        icon: 'archiver/icon.svg',
        type: 'iframe',
        entry: 'archiver/index.html',
        width: 750,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'System Tools',
        fileTypes: ['zip', 'gz', 'tar', 'tgz', 'bz2', 'xz', 'zst', 'b64', 'rar', '7z', 'lzh', 'lha', 'arj', 'sqx', 'cpio', 'cab', 'iso', 'z', 'rpm', 'deb', 'jar', 'war', 'ear', 'apk', 'epub', 'docx', 'xlsx', 'pptx', 'odt', 'ods', 'odp', 'zipx', 'lzma', 'lz', 'lzo', 'uue', 'uu', 'tlz', 'a', 'ar', 'lib', 'arc', 'zoo', 'ha', 'ace', 'sit', 'sitx', 'pak', 'shar', 'wim', 'esd', 'xar', 'pkg', 'msi', 'chm', 'dmg', 'squashfs', 'cramfs', 'udf', 'fat', 'ntfs', 'ext2', 'ext3', 'ext4', 'hfs', 'apfs', 'qcow2', 'vhd', 'vhdx', 'vdi', 'vmdk', 'hex', 'ihex', 'par', 'par2', 'mar', 'alz', 'pea']
      },
      {
        id: 'metadata-viewer',
        title: 'Metadata Viewer',
        icon: 'metadata-viewer/icon.svg',
        type: 'iframe',
        entry: 'metadata-viewer/index.html',
        width: 850,
        height: 600,
        resizable: true,
        minimizable: true,
        maximizable: true,
        singleton: false,
        category: 'Development'
      }
    ]
  };
})();
