/*
 * RC4-drop[65536] (DarkCrypt) Stream Cipher Implementation
 * Compatible with AlgorithmFramework
 * (c)2006-2025 Hawkynt
 *
 * RC4-drop is standard RC4 (Key Scheduling Algorithm + Pseudo-Random
 * Generation Algorithm) where the first N generated keystream bytes are
 * discarded before any output is produced, mitigating known biases in the
 * early RC4 keystream.
 *
 * This variant, as exposed by the DarkCrypt Total Commander plugin
 * (Alexander Myasnikov, "Zarya" project), uses a fixed 128-byte (1024-bit)
 * key and drops the first 65536 generated bytes - matching the readme's
 * "RC4-drop[65536] (1024 bit)" entry exactly: setup() runs the standard
 * KSA over 128 key bytes, then a "drop" phase runs the PRGA state-update
 * 65536 times without producing output. No IV/nonce is used.
 *
 * A standalone implementation is used here (rather than extending the
 * existing algorithms/stream/rc4.js) because that file's Feed/Result API has
 * no way to express "discard N bytes of keystream before encrypting" without
 * external bookkeeping.
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['../../AlgorithmFramework', '../../OpCodes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory(
      require('../../AlgorithmFramework'),
      require('../../OpCodes')
    );
  } else {
    factory(root.AlgorithmFramework, root.OpCodes);
  }
}((function () {
  if (typeof globalThis !== 'undefined') return globalThis;
  if (typeof window !== 'undefined') return window;
  if (typeof global !== 'undefined') return global;
  if (typeof self !== 'undefined') return self;
  throw new Error('Unable to locate global object');
})(), function (AlgorithmFramework, OpCodes) {
  'use strict';

  if (!AlgorithmFramework) throw new Error('AlgorithmFramework dependency is required');
  if (!OpCodes) throw new Error('OpCodes dependency is required');

  const { RegisterAlgorithm, CategoryType, SecurityStatus, ComplexityType, CountryCode,
          StreamCipherAlgorithm, IAlgorithmInstance,
          TestCase, LinkItem, Vulnerability, KeySize } = AlgorithmFramework;

  const KEY_SIZE = 128;   // 1024-bit fixed key, per DarkCrypt readme + disasm
  const DROP_COUNT = 65536;

  class DarkCryptRC4DropAlgorithm extends StreamCipherAlgorithm {
    constructor() {
      super();

      this.name = "RC4-drop[65536] (DarkCrypt)";
      this.description = "Standard RC4 KSA/PRGA with a fixed 1024-bit (128-byte) key, discarding the first 65536 generated keystream bytes before output. As implemented in the DarkCrypt Total Commander plugin (readme entry \"RC4-drop[65536] (1024 bit)\").";
      this.inventor = "Ron Rivest (RC4); DarkCrypt build by Alexander Myasnikov";
      this.year = 1987;
      this.category = CategoryType.STREAM;
      this.subCategory = "Stream Cipher";
      this.securityStatus = SecurityStatus.BROKEN;
      this.complexity = ComplexityType.BEGINNER;
      this.country = CountryCode.RU;

      this.SupportedKeySizes = [new KeySize(KEY_SIZE, KEY_SIZE, 0)]; // fixed 1024-bit
      this.SupportedNonceSizes = [new KeySize(0, 0, 0)];             // no IV

      this.documentation = [
        new LinkItem("RFC 6229: Test Vectors for RC4", "https://tools.ietf.org/html/rfc6229"),
        new LinkItem("DarkCrypt plugin (Total Commander PlugRing)", "https://totalcmd.net/plugring/darkcrypttc.html")
      ];

      this.knownVulnerabilities = [
        new Vulnerability(
          "Statistical Biases",
          "Dropping the first 65536 bytes mitigates but does not eliminate known RC4 keystream biases",
          "DO NOT USE - Use ChaCha20 or AES-GCM instead"
        )
      ];

      // Test vectors verified against the DarkCrypt implementation
      // (setup(key) then crypt(buf,len) in-place XOR keystream).
      this.tests = [
        {
          text: "DarkCrypt Rc4drop — incrementing 128-byte key, 128-byte zero keystream after drop",
          uri: "https://totalcmd.net/plugring/darkcrypttc.html",
          input: OpCodes.Hex8ToBytes("00".repeat(128)),
          key: OpCodes.Hex8ToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f"),
          expected: OpCodes.Hex8ToBytes("d4bb07e3632f1774c816557a74378899c56bbd2cb76ddd7034c2a1511264852466314c6b086c59efc926c365d5a778c8205c27e38386fd45c79cf68ea75681c6fc8dd9d55726703aa314f76f9c91ba583d0875c0fbc7f29c10555aa5b8d312e19ba17baf096aa0f982d578774222bbe5dd363d48454a8f9dce2984ade642e40f")
        },
        {
          text: "DarkCrypt Rc4drop — incrementing 128-byte key/plaintext",
          uri: "https://totalcmd.net/plugring/darkcrypttc.html",
          input: OpCodes.Hex8ToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f"),
          key: OpCodes.Hex8ToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f"),
          expected: OpCodes.Hex8ToBytes("d4ba05e0672a1173c01f5f71783a8696d57aaf3fa378cb672cdbbb4a0e799b3b46106e482c497fc8e10fe94ef98a56e7106d15d0b7b3cb72ffa5ccb59b6bbff9")
        }
      ];
    }

    CreateInstance(isInverse = false) {
      return new DarkCryptRC4DropInstance(this, isInverse);
    }
  }

  class DarkCryptRC4DropInstance extends IAlgorithmInstance {
    constructor(algorithm, isInverse = false) {
      super(algorithm);
      this.isInverse = isInverse;
      this.inputBuffer = [];
      this._key = null;

      this.S = new Array(256);
      this.i = 0;
      this.j = 0;
      this.initialized = false;
    }

    set key(keyBytes) {
      if (!keyBytes) { this._key = null; this.initialized = false; return; }
      if (keyBytes.length !== KEY_SIZE)
        throw new Error(`Invalid key size: ${keyBytes.length} bytes. RC4-drop[65536] (DarkCrypt) requires exactly ${KEY_SIZE} bytes`);
      this._key = [...keyBytes];
      this._initialize();
    }

    get key() { return this._key ? [...this._key] : null; }

    Feed(data) {
      if (!data || data.length === 0) return;
      if (!this._key) throw new Error("Key not set");
      for (let _i = 0; _i < data.length; _i++) this.inputBuffer.push(data[_i]);
    }

    Result() {
      if (!this._key) throw new Error("Key not set");
      if (!this.initialized) throw new Error("RC4-drop not properly initialized");
      if (this.inputBuffer.length === 0) return [];

      const output = [];
      for (let k = 0; k < this.inputBuffer.length; k++)
        output.push(OpCodes.XorN(this.inputBuffer[k], this._nextKeystreamByte()));

      this.inputBuffer = [];
      return output;
    }

    _initialize() {
      // Key Scheduling Algorithm
      for (let k = 0; k < 256; k++) this.S[k] = k;
      let j = 0;
      for (let k = 0; k < 256; k++) {
        j = OpCodes.AndN(j + this.S[k] + this._key[k % this._key.length], 0xFF);
        const tmp = this.S[k]; this.S[k] = this.S[j]; this.S[j] = tmp;
      }
      this.i = 0;
      this.j = 0;
      this.initialized = true;

      // Drop phase: run the PRGA state update DROP_COUNT times, discarding output.
      for (let n = 0; n < DROP_COUNT; n++) this._prgaStep();
    }

    _prgaStep() {
      this.i = OpCodes.AndN(this.i + 1, 0xFF);
      this.j = OpCodes.AndN(this.j + this.S[this.i], 0xFF);
      const tmp = this.S[this.i]; this.S[this.i] = this.S[this.j]; this.S[this.j] = tmp;
    }

    _nextKeystreamByte() {
      this._prgaStep();
      const t = OpCodes.AndN(this.S[this.i] + this.S[this.j], 0xFF);
      return this.S[t];
    }
  }

  const algorithmInstance = new DarkCryptRC4DropAlgorithm();
  if (!AlgorithmFramework.Find(algorithmInstance.name)) {
    RegisterAlgorithm(algorithmInstance);
  }

  return { DarkCryptRC4DropAlgorithm, DarkCryptRC4DropInstance };
}));
