;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/IRIXOS';

  skins['IRIXOS'] = {
    name: 'Irix OS',
    author: 'Massimo Rossi',
    email: 'sgrangware@tiscali.it',
    url: 'N/A',
    generator: 'Stardock SkinStudio ver 1.9.0, Build 437  - http://www.skinstudio.net',
    editorNotes: '� 1999-2002 Rossi Massimo <sgrangware@tiscali.it>',
    wbVersion: 200,
    basePath: BASE,

    personality: {
      usestran: 1,
      buttoncount: 3,
      textalignment: 0,
      textshift: 24,
      textshiftvert: 10,
      textrightclip: 82,
      menur: 81,
      menug: 118,
      menub: 162,
      activetextr: 0,
      activetextg: 0,
      activetextb: 0,
      inactivetextr: 0,
      inactivetextg: 0,
      inactivetextb: 0,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      tripleimages: 1,
      menubar: `${BASE}/MENU.BMP`,
      top: `${BASE}/TOP.BMP`,
      left: `${BASE}/LEFT.BMP`,
      right: `${BASE}/RIGHT.BMP`,
      bottom: `${BASE}/BOTTOM.BMP`,
      anirate: 0,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      toptopheight: 32,
      topbotheight: 36,
      lefttopheight: 34,
      leftbotheight: 36,
      righttopheight: 34,
      rightbotheight: 36,
      bottomtopheight: 32,
      bottombotheight: 36,
      topstretch: 0,
      leftstretch: 0,
      rightstretch: 0,
      bottomstretch: 0,
      rightclickaction: 1,
      doubleclickaction: '4',
      rollupsize: 40,
      explorerbmp: `${BASE}/EXPLORER2.BMP`,
      wallpaper: 'irixos\\Twhilight.png',
      menuborders: `${BASE}/MENUFRAME.BMP`,
      tilemenu: 0,
      tileleftmenu: 3,
      tilerightmenu: 3,
      maxbordercutleft: '0',
      maxbordercutright: '0',
      maxbordercuttop: '0',
      maxbordercutbottom: '0',
      soundenabled: 0,
      noshape: '0',
    },

    buttons: {
      checkbutton: `${BASE}/CHECKBOX.BMP`,
      radiobutton: `${BASE}/RADIO.BMP`,
      bitmap: `${BASE}/BUTTON.BMP`,
      topheight: 5,
      bottomheight: 5,
      leftwidth: 5,
      rightwidth: 5,
    },

    titleButtons: [
      { image: `${BASE}/MIN.BMP`, align: 1, xcoord: 58, ycoord: 8, action: 2, visibility: 22 },
      { image: `${BASE}/MAX.BMP`, align: 1, xcoord: 34, ycoord: 8, action: 1, visibility: 20 },
      { image: `${BASE}/CLOSE.BMP`, align: 0, xcoord: 8, ycoord: 8, action: 0 },
    ],

    comboButton: {
    },

    startButton: { image: `${BASE}/STARTBUTTON.BMP` },

    colors: {
      activeBorder: [193, 193, 193],
      activeTitle: [32, 50, 127],
      appWorkspace: [128, 128, 128],
      background: [125, 165, 165],
      buttonAlternateFace: [184, 184, 184],
      buttonDarkShadow: [0, 0, 0],
      buttonFace: [192, 192, 192],
      buttonHighlight: [224, 224, 224],
      buttonLight: [192, 192, 192],
      buttonShadow: [128, 128, 128],
      buttonText: [0, 0, 0],
      gradientActiveTitle: [129, 142, 150],
      gradientInactiveTitle: [129, 142, 150],
      grayText: [128, 128, 128],
      highlight: [80, 120, 160],
      highlightText: [0, 0, 0],
      hotTrackingColor: [0, 0, 255],
      inactiveBorder: [220, 218, 220],
      inactiveTitle: [32, 51, 128],
      inactiveTitleText: [255, 255, 255],
      infoText: [0, 0, 0],
      infoWindow: [184, 142, 144],
      menu: [192, 192, 192],
      menuText: [0, 0, 0],
      scrollbar: [224, 224, 224],
      titleText: [255, 255, 255],
      window: [132, 170, 204],
      windowFrame: [0, 0, 0],
      windowText: [0, 0, 0],
    },

    fonts: {
      family: 'Lucida Sans Typewriter',
      height: 15,
    },
  };
})();
