/*
 * Rainbow (DarkCrypt variant) Implementation
 * Compatible with AlgorithmFramework
 * (c)2006-2025 Hawkynt
 *
 * "Rainbow" is a home-grown block cipher bundled with the DarkCrypt Total
 * Commander plugin (Alexander Myasnikov, "Zarya" project); it is not related
 * to any published "Rainbow" cipher or signature scheme. 128-bit block,
 * 256-bit key.
 *
 * Structure (an unbalanced SP network, 8 rounds over the full 128-bit state):
 *   - Key schedule: split the 256-bit key into two 128-bit halves K0,K1 (four
 *     32-bit little-endian words each). RK[0] = Mix(K0 XOR K1); RK[i] =
 *     Mix(RK[i-1]) for i=1..14, where Mix applies a fixed sequential
 *     ROR(3/5/7/11)-and-XOR diffusion (constant 0xB7E15163, borrowed from the
 *     RC5/RC6 P32 constant) to the 4 words, each new word depending on the
 *     previously updated words in the same call. Every even-indexed RK (RK0,
 *     RK2, ..., RK14) then has its word0 overwritten with
 *     NOT(word1 XOR word2 XOR word3) ("checksum" step).
 *     The 16-entry forward table is CTX = [K0, RK0, RK1, ..., RK14].
 *     The 16-entry inverse table is DCTX = [F(RK13,RK14), RK14, F(RK11,RK12),
 *     RK12, ..., F(K0,RK0), RK0] where F(A,B)[j] = XOR over k=0..3 of
 *     (A[k] AND B[(k+j) mod 4]) (a circular AND/XOR "convolution").
 *   - Round function (applied 8 times, consuming table pairs (T[2i],T[2i+1])
 *     for i=0..7): state ^= T[2i] (word-wise XOR); mixed = F(state, T[2i+1]);
 *     for i<7 the 4 mixed words are each passed through a fixed pair of
 *     256-entry substitution tables S0/S1 with a position-dependent
 *     byte permutation (word0: out=[S1[b1],S0[b0],S1[b3],S0[b2]]; word1 and
 *     word3: out=[S1[b2],S1[b3],S0[b0],S0[b1]]; word2: out=[S1[b3],S1[b2],
 *     S0[b1],S0[b0]], each bN meaning byte N of the input word); the last
 *     round (i=7) skips the substitution and its AND-mixed output is the
 *     final state directly.
 *   - Encryption uses table CTX; decryption uses the SAME round function
 *     with table DCTX (built during key setup so the two 256-entry S-boxes
 *     can be reused unmodified for decryption too).
 *   - S0 and S1 are fixed 256-byte tables, generated at DLL load time by a
 *     GF(2)-based construction independent of the key; their concrete values
 *     were extracted directly from the running DLL's memory (address
 *     0x41F010/0x41F110 at image base 0x400000) rather than re-derived, since
 *     the generator algorithm is a self-contained bit-slice search unrelated
 *     to the cipher's data path.
 * All 32-bit words are read/written little-endian.
 * Test vectors verified against the DarkCrypt implementation (encrypt/decrypt
 * round-trip verified).
 * 128-bit blocks, 256-bit keys. Educational only.
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['../../AlgorithmFramework', '../../OpCodes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory(
      require('../../AlgorithmFramework'),
      require('../../OpCodes')
    );
  } else {
    factory(root.AlgorithmFramework, root.OpCodes);
  }
}((function () {
  if (typeof globalThis !== 'undefined') return globalThis;
  if (typeof window !== 'undefined') return window;
  if (typeof global !== 'undefined') return global;
  if (typeof self !== 'undefined') return self;
  throw new Error('Unable to locate global object');
})(), function (AlgorithmFramework, OpCodes) {
  'use strict';

  if (!AlgorithmFramework) throw new Error('AlgorithmFramework dependency is required');
  if (!OpCodes) throw new Error('OpCodes dependency is required');

  const { RegisterAlgorithm, CategoryType, SecurityStatus, ComplexityType, CountryCode,
          BlockCipherAlgorithm, IBlockCipherInstance,
          TestCase, LinkItem, Vulnerability, KeySize } = AlgorithmFramework;

  const ROUNDS = 8;
  const MIX_CONST = 0xB7E15163;

  // Fixed substitution tables, as used by the DarkCrypt implementation (they are
  // generated by a key-independent GF(2) bit-slice construction at load time;
  // the construction routine itself is not part of the
  // cipher's data path, so its concrete output is used as-is).
  const S0 = [
    0x00,0x0E,0x1C,0x08,0x38,0xE5,0x10,0x19,0x70,0x16,0xCB,0x42,0x20,0xE7,0x32,0xD4,
    0xE0,0xCC,0x2C,0x65,0x97,0xA7,0x84,0x1F,0x40,0x67,0xCF,0x78,0x64,0x2D,0xA9,0xBE,
    0xC1,0xC2,0x99,0xEC,0x58,0xD1,0xCA,0xFB,0x2F,0x8E,0x4F,0x6D,0x09,0x50,0x3E,0x2A,
    0x80,0x56,0xCE,0x11,0x9F,0x0C,0xF0,0xA4,0xC8,0xDF,0x5A,0xB1,0x53,0x73,0x7D,0x6F,
    0x83,0x79,0x85,0xF9,0x33,0xE9,0xD9,0x4B,0xB0,0x74,0xA3,0x14,0x95,0x03,0xF7,0xDC,
    0x5E,0x7A,0x1D,0xC0,0x9E,0x55,0xDA,0x26,0x12,0x6B,0xA0,0xD5,0x7C,0x98,0x54,0x72,
    0x01,0x48,0xAC,0x0F,0x9D,0xAD,0x22,0x36,0x3F,0x82,0x18,0xBA,0xE1,0x57,0x49,0x2E,
    0x91,0xF1,0xBF,0x4A,0xB4,0x62,0x63,0xEE,0xA6,0x51,0xE6,0x71,0xFA,0xC9,0xDE,0x43,
    0x07,0x04,0xF2,0x8C,0x0B,0x21,0xF3,0x6A,0x66,0xB2,0xD3,0x8F,0xB3,0x3C,0x96,0x5F,
    0x61,0x76,0xE8,0xFD,0x47,0xB6,0x28,0x15,0x2B,0x88,0x06,0x52,0xEF,0xD8,0xB9,0xB7,
    0xBC,0xFC,0xF4,0xA5,0x3A,0x0A,0x81,0x6E,0x3D,0x60,0xAA,0x13,0xB5,0xEA,0x4C,0x39,
    0x24,0x87,0xD6,0x1B,0x41,0x5D,0xAB,0x17,0xF8,0x25,0x31,0x77,0xA8,0xB8,0xE4,0xA1,
    0x02,0x46,0x90,0x35,0x59,0xC7,0x1E,0xAF,0x3B,0xFE,0x5B,0x8A,0x44,0x29,0x6C,0xDB,
    0x7E,0xD2,0x05,0x37,0x30,0x89,0x75,0x9C,0xC3,0x8D,0xAE,0x8B,0x92,0xBB,0x5C,0xD0,
    0x23,0x9A,0xE3,0xD7,0x7F,0x45,0x94,0xED,0x69,0x9B,0xC4,0x4E,0xC6,0xC5,0xDD,0x68,
    0x4D,0xEB,0xA2,0xF6,0xCD,0x27,0xE2,0x34,0xF5,0x7B,0x93,0x1A,0xBD,0x0D,0x86,0xFF
  ];

  const S1 = [
    0x00,0x60,0xC0,0x4D,0x81,0xD2,0x9A,0x80,0x03,0x2C,0xA5,0x84,0x35,0xFD,0x01,0x63,
    0x06,0x33,0x58,0xAB,0x4B,0x97,0x09,0xB7,0x6A,0x07,0xFB,0xB3,0x02,0x52,0xC6,0x17,
    0x0C,0x85,0x66,0xE0,0xB0,0xB9,0x57,0xF5,0x96,0xCD,0x2F,0x98,0x12,0x1D,0x6F,0x28,
    0xD4,0xBA,0x0E,0x44,0xF7,0xC3,0x67,0xD3,0x04,0xAF,0xA4,0xC8,0x8D,0xA8,0x2E,0x68,
    0x18,0xB4,0x0B,0x7F,0xCC,0xE5,0xC1,0x94,0x61,0x6E,0x73,0x47,0xAE,0xF0,0xEB,0x2A,
    0x2D,0x79,0x9B,0x3C,0x5E,0x55,0x31,0x6D,0x24,0xC4,0x3A,0xCA,0xDE,0xB5,0x50,0x8F,
    0xA9,0x90,0x75,0x76,0x1C,0x13,0x88,0x19,0xEF,0xE8,0x87,0x59,0xCE,0x2B,0xA7,0x3F,
    0x08,0x7B,0x5F,0x3D,0x49,0xD6,0x91,0xBB,0x1B,0x41,0x51,0xF9,0x5C,0x3E,0xD0,0xE4,
    0x30,0xA6,0x69,0x40,0x16,0x42,0xFE,0xB1,0x99,0xD5,0xCB,0xDB,0x83,0xD9,0x29,0x8B,
    0xC2,0x70,0xDC,0xFA,0xE6,0x4C,0x8E,0x14,0x5D,0x22,0xE1,0xE9,0xD7,0x64,0x54,0x34,
    0x5A,0xBF,0xF2,0x4A,0x37,0xA3,0x78,0x15,0xBC,0x1E,0xAA,0xB6,0x62,0x65,0xDA,0xC7,
    0x48,0x3B,0x89,0x8C,0x74,0xAC,0x95,0x9F,0xBD,0x9E,0x6B,0xDD,0xA0,0xFC,0x1F,0x72,
    0x53,0x20,0x21,0xD8,0xEA,0xED,0xEC,0xC5,0x38,0x7D,0x26,0x0A,0x11,0xF4,0x32,0x1A,
    0xDF,0x25,0xD1,0x8A,0x0F,0x5B,0xB2,0xE3,0x9D,0x46,0x56,0xCF,0x4F,0xEE,0x7E,0x39,
    0x10,0x6C,0xF6,0xE2,0xBE,0x05,0x7A,0x0D,0x92,0x45,0xAD,0xF1,0x23,0xE7,0x77,0x9C,
    0x36,0x71,0x82,0x86,0xA2,0xF8,0xF3,0x4E,0xB8,0x43,0x7C,0x27,0xA1,0x93,0xC9,0xFF
  ];

  class DarkCryptRainbowAlgorithm extends BlockCipherAlgorithm {
    constructor() {
      super();

      this.name = "Rainbow (DarkCrypt)";
      this.description = "Home-grown SP-network block cipher from the DarkCrypt Total Commander plugin (not related to the Rainbow signature scheme or any other published cipher named Rainbow). 256-bit key, 128-bit block, 8 rounds combining word-wise XOR, a circular AND/XOR mix, and a pair of fixed 256-entry substitution tables with position-dependent byte permutation.";
      this.inventor = "Alexander Myasnikov (DarkCrypt / \"Zarya\" project)";
      this.year = 2009;
      this.category = CategoryType.BLOCK;
      this.subCategory = "Block Cipher";
      this.securityStatus = SecurityStatus.EDUCATIONAL;
      this.complexity = ComplexityType.INTERMEDIATE;
      this.country = CountryCode.RU;

      this.SupportedKeySizes = [new KeySize(32, 32, 0)];   // fixed 256-bit
      this.SupportedBlockSizes = [new KeySize(16, 16, 0)]; // fixed 128-bit

      this.documentation = [
        new LinkItem("DarkCrypt plugin (Total Commander PlugRing)", "https://totalcmd.net/plugring/darkcrypttc.html")
      ];

      this.knownVulnerabilities = [
        new Vulnerability("Undocumented home-grown design", "Proprietary DarkCrypt cipher with no public specification or cryptanalysis; unanalyzed and not recommended for real use.", "Use AES or another vetted cipher.")
      ];

      // Test vectors verified against the DarkCrypt implementation (raw primitive: key setup + single-block encryption).
      this.tests = [
        {
          text: "DarkCrypt Rainbow — zero key/plaintext",
          uri: "https://totalcmd.net/plugring/darkcrypttc.html",
          input: OpCodes.Hex8ToBytes("00000000000000000000000000000000"),
          key: OpCodes.Hex8ToBytes("0000000000000000000000000000000000000000000000000000000000000000"),
          expected: OpCodes.Hex8ToBytes("c0976d52c43382351c60816706aabc5a")
        },
        {
          text: "DarkCrypt Rainbow — incrementing key/plaintext",
          uri: "https://totalcmd.net/plugring/darkcrypttc.html",
          input: OpCodes.Hex8ToBytes("000102030405060708090a0b0c0d0e0f"),
          key: OpCodes.Hex8ToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
          expected: OpCodes.Hex8ToBytes("cfee4bb0ffe0309628166dc2ca110aa4")
        },
        {
          text: "DarkCrypt Rainbow — shifted incrementing key/plaintext",
          uri: "https://totalcmd.net/plugring/darkcrypttc.html",
          input: OpCodes.Hex8ToBytes("101112131415161718191a1b1c1d1e1f"),
          key: OpCodes.Hex8ToBytes("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"),
          expected: OpCodes.Hex8ToBytes("e0d408b835a32ed5e47a12b9214a8b02")
        }
      ];
    }

    CreateInstance(isInverse = false) {
      return new DarkCryptRainbowInstance(this, isInverse);
    }
  }

  class DarkCryptRainbowInstance extends IBlockCipherInstance {
    constructor(algorithm, isInverse = false) {
      super(algorithm);
      this.isInverse = isInverse;
      this._key = null;
      this._ctx = null;   // forward (encryption) round-key table, 16 x [w0..w3]
      this._dctx = null;  // inverse (decryption) round-key table, 16 x [w0..w3]
      this.inputBuffer = [];
      this.BlockSize = 16;
      this.KeySize = 0;
    }

    set key(keyBytes) {
      if (!keyBytes) { this._key = null; this._ctx = null; this._dctx = null; this.KeySize = 0; return; }
      if (keyBytes.length !== 32)
        throw new Error(`Invalid key size: ${keyBytes.length} bytes. Rainbow (DarkCrypt) requires exactly 32 bytes`);
      this._key = [...keyBytes];
      this.KeySize = keyBytes.length;
      const { ctx, dctx } = this._buildSchedule(this._key);
      this._ctx = ctx;
      this._dctx = dctx;
    }

    get key() { return this._key ? [...this._key] : null; }

    Feed(data) {
      if (!data || data.length === 0) return;
      if (!this._key) throw new Error("Key not set");
      this.inputBuffer.push(...data);
    }

    Result() {
      if (!this._key) throw new Error("Key not set");
      if (this.inputBuffer.length === 0) throw new Error("No data fed");
      if (this.inputBuffer.length % this.BlockSize !== 0)
        throw new Error(`Input length must be multiple of ${this.BlockSize} bytes`);

      const output = [];
      for (let i = 0; i < this.inputBuffer.length; i += this.BlockSize) {
        const block = this.inputBuffer.slice(i, i + this.BlockSize);
        output.push(...(this.isInverse ? this._decryptBlock(block) : this._encryptBlock(block)));
      }
      this.inputBuffer = [];
      return output;
    }

    // Sequential ROR(3/5/7/11)-and-XOR diffusion; each new word uses the
    // already-updated earlier words of this same call (matches the DLL's
    // in-place, register-chained computation).
    _mix(b) {
      const n0 = OpCodes.ToUint32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.RotR32(b[0], 3), OpCodes.RotR32(b[1], 5)), OpCodes.RotR32(b[2], 7)), OpCodes.RotR32(b[3], 11)), MIX_CONST));
      const n1 = OpCodes.ToUint32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.RotR32(n0, 5), OpCodes.RotR32(b[1], 7)), OpCodes.RotR32(b[2], 11)), OpCodes.RotR32(b[3], 3)), MIX_CONST));
      const n2 = OpCodes.ToUint32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.RotR32(n0, 7), OpCodes.RotR32(n1, 11)), OpCodes.RotR32(b[2], 3)), OpCodes.RotR32(b[3], 5)), MIX_CONST));
      const n3 = OpCodes.ToUint32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.Xor32(OpCodes.RotR32(n0, 11), OpCodes.RotR32(n1, 3)), OpCodes.RotR32(n2, 5)), OpCodes.RotR32(b[3], 7)), MIX_CONST));
      return [n0, n1, n2, n3];
    }

    // word0 replaced with NOT(word1 XOR word2 XOR word3)
    _checksum(b) {
      return [OpCodes.ToUint32(~(OpCodes.Xor32(OpCodes.Xor32(b[1], b[2]), b[3]))), b[1], b[2], b[3]];
    }

    // Circular AND/XOR mix: out[j] = XOR over k=0..3 of (A[k] AND B[(k+j) mod 4])
    _mixAnd(a, b) {
      const out = [0, 0, 0, 0];
      for (let j = 0; j < 4; j++) {
        let v = 0;
        for (let k = 0; k < 4; k++) v ^= OpCodes.And32(a[k], b[(k + j) % 4]);
        out[j] = OpCodes.ToUint32(v);
      }
      return out;
    }

    _buildSchedule(keyBytes) {
      const k0 = [
        OpCodes.Pack32LE(keyBytes[0], keyBytes[1], keyBytes[2], keyBytes[3]),
        OpCodes.Pack32LE(keyBytes[4], keyBytes[5], keyBytes[6], keyBytes[7]),
        OpCodes.Pack32LE(keyBytes[8], keyBytes[9], keyBytes[10], keyBytes[11]),
        OpCodes.Pack32LE(keyBytes[12], keyBytes[13], keyBytes[14], keyBytes[15])
      ];
      const k1 = [
        OpCodes.Pack32LE(keyBytes[16], keyBytes[17], keyBytes[18], keyBytes[19]),
        OpCodes.Pack32LE(keyBytes[20], keyBytes[21], keyBytes[22], keyBytes[23]),
        OpCodes.Pack32LE(keyBytes[24], keyBytes[25], keyBytes[26], keyBytes[27]),
        OpCodes.Pack32LE(keyBytes[28], keyBytes[29], keyBytes[30], keyBytes[31])
      ];

      const seed = [0, 1, 2, 3].map(i => OpCodes.Xor32(k0[i], k1[i]));
      const rk = [this._mix(seed)];
      for (let i = 1; i < 15; i++) rk.push(this._mix(rk[i - 1]));
      const rkc = rk.map((b, i) => (i % 2 === 0) ? this._checksum(b) : b);

      const ctx = [k0, ...rkc]; // 16 entries: k0, RK0..RK14

      const dctx = [
        this._mixAnd(rkc[13], rkc[14]), rkc[14],
        this._mixAnd(rkc[11], rkc[12]), rkc[12],
        this._mixAnd(rkc[9], rkc[10]), rkc[10],
        this._mixAnd(rkc[7], rkc[8]), rkc[8],
        this._mixAnd(rkc[5], rkc[6]), rkc[6],
        this._mixAnd(rkc[3], rkc[4]), rkc[4],
        this._mixAnd(rkc[1], rkc[2]), rkc[2],
        this._mixAnd(k0, rkc[0]), rkc[0]
      ];

      return { ctx, dctx };
    }

    // Position-dependent substitution: word0 uses one byte/table permutation,
    // words 1 and 3 share a second, word2 uses a third.
    _sub0(w) {
      const b0 = OpCodes.And32(w, 0xFF), b1 = OpCodes.And32(OpCodes.Shr32(w, 8), 0xFF), b2 = OpCodes.And32(OpCodes.Shr32(w, 16), 0xFF), b3 = OpCodes.And32(OpCodes.Shr32(w, 24), 0xFF);
      return OpCodes.ToUint32(S1[b1] | OpCodes.Shl32(S0[b0], 8) | OpCodes.Shl32(S1[b3], 16) | OpCodes.Shl32(S0[b2], 24));
    }

    _sub1(w) {
      const b0 = OpCodes.And32(w, 0xFF), b1 = OpCodes.And32(OpCodes.Shr32(w, 8), 0xFF), b2 = OpCodes.And32(OpCodes.Shr32(w, 16), 0xFF), b3 = OpCodes.And32(OpCodes.Shr32(w, 24), 0xFF);
      return OpCodes.ToUint32(S1[b2] | OpCodes.Shl32(S1[b3], 8) | OpCodes.Shl32(S0[b0], 16) | OpCodes.Shl32(S0[b1], 24));
    }

    _sub2(w) {
      const b0 = OpCodes.And32(w, 0xFF), b1 = OpCodes.And32(OpCodes.Shr32(w, 8), 0xFF), b2 = OpCodes.And32(OpCodes.Shr32(w, 16), 0xFF), b3 = OpCodes.And32(OpCodes.Shr32(w, 24), 0xFF);
      return OpCodes.ToUint32(S1[b3] | OpCodes.Shl32(S1[b2], 8) | OpCodes.Shl32(S0[b1], 16) | OpCodes.Shl32(S0[b0], 24));
    }

    // Applies the 8-round primitive using the given round-key table
    // (either the forward CTX table for encryption, or the DCTX table for
    // decryption — the round structure itself is identical either way).
    _process(state, table) {
      let s = state;
      for (let i = 0; i < ROUNDS; i++) {
        const xorKey = table[2 * i];
        const andKey = table[2 * i + 1];
        s = [0, 1, 2, 3].map(idx => OpCodes.Xor32(s[idx], xorKey[idx]));
        const mixed = this._mixAnd(s, andKey);
        if (i < ROUNDS - 1)
          s = [this._sub0(mixed[0]), this._sub1(mixed[1]), this._sub2(mixed[2]), this._sub1(mixed[3])];
        else
          s = mixed;
      }
      return s;
    }

    _encryptBlock(block) {
      const state = [
        OpCodes.Pack32LE(block[0], block[1], block[2], block[3]),
        OpCodes.Pack32LE(block[4], block[5], block[6], block[7]),
        OpCodes.Pack32LE(block[8], block[9], block[10], block[11]),
        OpCodes.Pack32LE(block[12], block[13], block[14], block[15])
      ];
      const out = this._process(state, this._ctx);
      return [...OpCodes.Unpack32LE(out[0]), ...OpCodes.Unpack32LE(out[1]), ...OpCodes.Unpack32LE(out[2]), ...OpCodes.Unpack32LE(out[3])];
    }

    _decryptBlock(block) {
      const state = [
        OpCodes.Pack32LE(block[0], block[1], block[2], block[3]),
        OpCodes.Pack32LE(block[4], block[5], block[6], block[7]),
        OpCodes.Pack32LE(block[8], block[9], block[10], block[11]),
        OpCodes.Pack32LE(block[12], block[13], block[14], block[15])
      ];
      const out = this._process(state, this._dctx);
      return [...OpCodes.Unpack32LE(out[0]), ...OpCodes.Unpack32LE(out[1]), ...OpCodes.Unpack32LE(out[2]), ...OpCodes.Unpack32LE(out[3])];
    }
  }

  const algorithmInstance = new DarkCryptRainbowAlgorithm();
  if (!AlgorithmFramework.Find(algorithmInstance.name)) {
    RegisterAlgorithm(algorithmInstance);
  }

  return { DarkCryptRainbowAlgorithm, DarkCryptRainbowInstance };
}));
