;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/LCARS';

  skins['LCARS'] = {
    name: 'LCARS_Red',
    author: 'Martin Prohn',
    email: 'MartinProh@lycos.de',
    generator: 'Stardock SkinStudio ver 1.9.0, Build 437  - http://www.skinstudio.net',
    wbVersion: 200,
    basePath: BASE,

    personality: {
      buttoncount: 10,
      mouseover: 1,
      tripleimages: 0,
      textalignment: 0,
      textshift: 20,
      textshiftvert: 1,
      textrightclip: 110,
      toptopheight: 0,
      topbotheight: 0,
      lefttopheight: 21,
      leftbotheight: 3,
      righttopheight: 21,
      rightbotheight: 3,
      bottomtopheight: 2,
      bottombotheight: 2,
      topstretch: 1,
      leftstretch: 1,
      rightstretch: 1,
      bottomstretch: 1,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      anirate: 0,
      rollupsize: 20,
      soundenabled: 0,
      tilemenu: 0,
      tileleftmenu: 2,
      tilerightmenu: 2,
      menulefttile: 0,
      colouraware: 1,
      maxbordercuttop: 2,
      menur: 0,
      menug: 0,
      menub: 0,
      activetextr: 255,
      activetextg: 255,
      activetextb: 255,
      inactivetextr: 192,
      inactivetextg: 192,
      inactivetextb: 192,
      menutextr: 255,
      menutextg: 211,
      menutextb: 0,
      top: `${BASE}/TOP.BMP`,
      topmask: `${BASE}/TOPMASK.BMP`,
      left: `${BASE}/LEFT.BMP`,
      leftmask: `${BASE}/LEFTMASK.BMP`,
      right: `${BASE}/RIGHT.BMP`,
      rightmask: `${BASE}/RIGHTMASK.BMP`,
      bottom: `${BASE}/BOTTOM.BMP`,
      bottommask: `${BASE}/BOTTOMMASK.BMP`,
      menubar: `${BASE}/MENU.BMP`,
      explorerbmp: `${BASE}/EXPLORE.BMP`,
      dialogbmp: `${BASE}/DIALOG.BMP`,
      mdibmp: `${BASE}/MDI.BMP`,
    },

    buttons: {
      checkbutton: `${BASE}/CHECKBOX.BMP`,
      radiobutton: `${BASE}/RADIO.BMP`,
      bitmap: `${BASE}/BUTTON_3.BMP`,
      topheight: 1,
      bottomheight: 1,
      leftwidth: 1,
      rightwidth: 1,
      mouseover: 1,
      tile: 1,
      trans: 1,
    },

    titleButtons: [
      { image: `${BASE}/EXIT.BMP`, mask: `${BASE}/EXITMASK.BMP`, align: 1, xcoord: 20, ycoord: 3, action: 0 },
      { image: `${BASE}/MAX.BMP`, mask: `${BASE}/MAXMASK.BMP`, align: 1, xcoord: 38, ycoord: 3, action: 22, visibility: 4, visibility1: 20 },
      { image: `${BASE}/MIN.BMP`, mask: `${BASE}/MINMASK.BMP`, align: 1, xcoord: 54, ycoord: 3, action: 23, visibility: 22 },
      { image: `${BASE}/RESTORE.BMP`, mask: `${BASE}/RESTOREMASK.BMP`, align: 1, xcoord: 38, ycoord: 3, action: 22, visibility: 3, visibility1: 20 },
      { align: 0, xcoord: 3, ycoord: 3, action: 11 },
      { image: `${BASE}/NOICON.BMP`, align: 0, xcoord: 3, ycoord: 3, action: -1, visibility: 28 },
      { image: `${BASE}/NO_MAX.BMP`, mask: `${BASE}/MAXMASK.BMP`, align: 1, xcoord: 38, ycoord: 3, action: -1, visibility: 21 },
      { image: `${BASE}/NO_MIN.BMP`, mask: `${BASE}/MINMASK.BMP`, align: 1, xcoord: 54, ycoord: 3, action: -1, visibility: 23 },
      { image: `${BASE}/HELP.BMP`, mask: `${BASE}/HELPMASK.BMP`, align: 1, xcoord: 74, ycoord: 3, action: 3, visibility: 13, visibility1: 20 },
      { image: `${BASE}/HELP.BMP`, mask: `${BASE}/HELPMASK.BMP`, align: 1, xcoord: 38, ycoord: 3, action: 3, visibility: 13, visibility1: 17 },
    ],

    comboButton: {},

    startButton: { image: `${BASE}/START.BMP` },

    colors: {
      scrollbar: [32, 32, 32],
      background: [0, 0, 0],
      activeTitle: [32, 32, 32],
      inactiveTitle: [32, 32, 32],
      menu: [32, 32, 32],
      window: [0, 0, 0],
      windowFrame: [255, 0, 0],
      menuText: [255, 255, 255],
      windowText: [255, 255, 255],
      titleText: [255, 255, 255],
      activeBorder: [255, 0, 0],
      inactiveBorder: [255, 192, 192],
      appWorkspace: [0, 0, 0],
      highlight: [255, 32, 32],
      highlightText: [255, 255, 255],
      buttonFace: [0, 0, 0],
      buttonShadow: [192, 0, 0],
      grayText: [128, 128, 128],
      buttonText: [221, 221, 221],
      inactiveTitleText: [192, 192, 192],
      buttonHighlight: [255, 64, 64],
      buttonDarkShadow: [172, 0, 0],
      buttonLight: [255, 0, 0],
      infoText: [0, 0, 0],
      infoWindow: [255, 255, 225],
      buttonAlternateFace: [0, 0, 0],
      hotTrackingColor: [255, 0, 0],
      gradientActiveTitle: [32, 32, 32],
      gradientInactiveTitle: [32, 32, 32],
    },

    fonts: {
      family: 'Arial',
      height: 11,
      weight: 400,
      antialias: true,
    },
  };
})();
