;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/MDNATURE';

  skins['MDNATURE'] = {
    name: 'MdNature',
    author: 'MDsigns',
    email: 'mdsigns@vt4.net',
    url: 'Not available',
    generator: 'BuilderBlinds ver 0.76.0, Build 76  - http://www.stardock.com/products/builderblinds',
    editorNotes: 'This is a skin for WindowBlinds 1.1 or higher, e-mail suggestions to me!',
    wbVersion: 130,
    basePath: BASE,

    personality: {
      usestran: 0,
      buttoncount: 6,
      textalignment: 1,
      textshift: 25,
      textshiftvert: 6,
      textrightclip: 80,
      menur: 196,
      menug: 196,
      menub: 196,
      activetextr: 45,
      activetextg: 50,
      activetextb: 38,
      inactivetextr: 92,
      inactivetextg: 102,
      inactivetextb: 78,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      top: `${BASE}/TOP.BMP`,
      left: `${BASE}/LEFT.BMP`,
      right: `${BASE}/RIGHT.BMP`,
      bottom: `${BASE}/BOTTOM.BMP`,
      toptopheight: 20,
      topbotheight: 100,
      lefttopheight: 25,
      leftbotheight: 5,
      righttopheight: 25,
      rightbotheight: 5,
      bottomtopheight: 10,
      bottombotheight: 10,
      topstretch: 1,
      leftstretch: 1,
      rightstretch: 1,
      bottomstretch: 1,
      anirate: 0,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      tripleimages: 1,
      soundenabled: 0,
      menubar: `${BASE}/MENU.BMP`,
      tilemenu: 1,
      dialogbmp: `${BASE}/DIALOGBOX.BMP`,
      mouseover: 1,
      menuborders: `${BASE}/MENUBORDER.BMP`,
      rollupsize: 29,
      explorerbmp: `${BASE}/EXPLORER.BMP`,
      textbackground: '0',
      tileleftmenu: 12,
      tilerightmenu: 12,
      rightclickaction: 4,
      doubleclickaction: '1',
      maxbordercutleft: '0',
      maxbordercutright: '0',
      maxbordercuttop: '0',
      maxbordercutbottom: '0',
      menulefttile: 3,
      noshape: '0',
    },

    buttons: {
      checkbutton: `${BASE}/CHECKBOX.BMP`,
      radiobutton: `${BASE}/RADIO.BMP`,
      bitmap: `${BASE}/BUTTONS.BMP`,
      topheight: 2,
      bottomheight: 2,
      leftwidth: 2,
      rightwidth: 2,
      mouseover: 1,
      tile: '0',
    },

    titleButtons: [
      { image: `${BASE}/CLOSE.BMP`, align: 1, xcoord: 31, ycoord: 4, action: 0, visibility: 0 },
      { image: `${BASE}/BLANK.BMP`, align: 1, xcoord: 56, ycoord: 4, action: -1, visibility: 21 },
      { image: `${BASE}/MAXIMIZE.BMP`, align: 1, xcoord: 56, ycoord: 4, action: 22, visibility: 20 },
      { image: `${BASE}/BLANK.BMP`, align: 1, xcoord: 81, ycoord: 4, action: -1, visibility: 23 },
      { image: `${BASE}/MINIMIZE.BMP`, align: 1, xcoord: 81, ycoord: 4, action: 23, visibility: 22 },
      { image: `${BASE}/RADIO.BMP`, align: 0, xcoord: 16, ycoord: 7, action: 11 },
    ],

    comboButton: {
    },

    startButton: { image: `${BASE}/START.BMP` },

    colors: {
      activeBorder: [129, 142, 109],
      inactiveBorder: [129, 142, 109],
      activeTitle: [184, 182, 133],
      inactiveTitle: [85, 94, 72],
      titleText: [255, 255, 255],
      inactiveTitleText: [192, 192, 192],
      buttonText: [0, 0, 0],
      grayText: [85, 94, 72],
      highlightText: [0, 0, 0],
      windowText: [0, 0, 0],
      menuText: [0, 0, 0],
      highlight: [184, 182, 133],
      window: [255, 255, 255],
      windowFrame: [0, 0, 0],
      background: [0, 0, 0],
      appWorkspace: [0, 0, 0],
      menu: [129, 142, 109],
      scrollbar: [192, 199, 182],
      buttonHighlight: [192, 199, 182],
      buttonLight: [129, 142, 109],
      buttonFace: [129, 142, 109],
      buttonShadow: [85, 94, 72],
      buttonDarkShadow: [0, 0, 0],
      infoText: [0, 0, 0],
      infoWindow: [184, 182, 133],
    },

    fonts: {
      family: 'Eurostile Extended',
      height: 12,
    },
  };
})();
