;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/WINDOWSXL';

  skins['WINDOWSXL'] = {
    name: 'Windows XL',
    author: 'Fuzzy Logic',
    email: 'm.hather@btinternet.com',
    url: 'http://www.SkinStudio.net (put your URL here)',
    generator: 'Stardock SkinStudio Professional ver 4.4.0, Build 954  - http://www.skinstudio.net',
    editorNotes: 'Do not edit this skin without permission from the author � fuzzylogic 2004',
    wbVersion: 400,
    basePath: BASE,

    personality: {
      buttoncount: 19,
      colouraware: '0',
      top: `${BASE}/WINDOWFRAMETOPUIS2.BMP`,
      left: `${BASE}/WINDOWFRAMELEFTUIS2.BMP`,
      right: `${BASE}/WINDOWFRAMERIGHTUIS2.BMP`,
      bottom: `${BASE}/WINDOWFRAMEBOTTOMUIS2.BMP`,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      topstretch: 0,
      leftstretch: 0,
      rightstretch: 0,
      bottomstretch: 1,
      textalignment: 1,
      textshift: 49,
      textshiftvert: 1,
      textrightclip: 108,
      anirate: 0,
      menur: 167,
      menug: 167,
      menub: 167,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      rollupsize: 38,
      mouseover: 1,
      soundenabled: 0,
      tilemenu: 0,
      menubar: `${BASE}/REBAR.BMP`,
      menuborders: `${BASE}/MENUBACKGROUND.BMP`,
      maxbordercutleft: '0',
      maxbordercutright: '0',
      maxbordercuttop: '0',
      maxbordercutbottom: '0',
      toptopheight: 58,
      topbotheight: 115,
      bottomtopheight: 11,
      bottombotheight: 11,
      lefttopheight: 80,
      leftbotheight: 5,
      righttopheight: 80,
      rightbotheight: 5,
      tileleftmenu: 0,
      tilerightmenu: 0,
      mditransparent: '1',
      tripleimages: 0,
      activetextr: 0,
      activetextg: 0,
      activetextb: 0,
      textshiftnoicon: '0',
      textrightclipnoicon: '0',
      inactivetextr: 0,
      inactivetextg: 0,
      inactivetextb: 0,
    },

    buttons: {
      checkbutton: `${BASE}/CHECKBOX.TGA`,
      radiobutton: `${BASE}/RADIOBUTTON.TGA`,
      bitmap: `${BASE}/PUSHBUTTON.BMP`,
      mouseover: 1,
      enhancedmode: '1',
      trans: 1,
      leftwidth: 2,
      rightwidth: 2,
      topheight: 2,
      bottomheight: 2,
      contentleft: '3',
      contentright: '3',
      contenttop: '3',
      contentbottom: '3',
      checkperpixel: '1',
      radioperpixel: '1',
      perpixel: '0',
      tile: '2',
      tiletop: '0',
      tilebottom: '0',
      tileleft: '0',
      tileright: '0',
      normalcolour: '0',
      pressedcolour: '0',
      disabledcolour: '7',
      focuscolour: '0',
      defaultcolour: '0',
    },

    titleButtons: [
      { image: `${BASE}/CLOSEBUTTON.BMP`, align: 1, xcoord: 33, ycoord: 0, action: 0, linkedto: 1, visibility: 31, visibility1: 1 },
      { image: `${BASE}/CLOSEBUTTON.BMP`, align: 1, xcoord: 33, ycoord: 0, action: 0, visibility: 1 },
      { image: `${BASE}/CLOSEBUTTONINACTIVE.BMP`, align: 1, xcoord: 33, ycoord: 0, action: -2, visibility: 2, visibility1: 2 },
      { image: `${BASE}/MAXBUTTONDISABLED.BMP`, align: 1, xcoord: 58, ycoord: 0, action: -6, visibility: 4, visibility1: 21, visibility2: 22, visibility3: 1 },
      { image: `${BASE}/MAXBUTTON.BMP`, align: 1, xcoord: 58, ycoord: 0, action: 22, visibility: 20, visibility1: 4, visibility2: 1 },
      { image: `${BASE}/MAXBUTTONINACTIVE.BMP`, align: 1, xcoord: 58, ycoord: 0, action: 22, visibility: 20, visibility1: 4, visibility2: 2 },
      { image: `${BASE}/RESTOREBUTTONDISABLED.BMP`, align: 1, xcoord: 58, ycoord: 0, action: -6, visibility: 3, visibility1: 21, visibility2: 22, visibility3: 1 },
      { image: `${BASE}/RESTOREBUTTONINACTIVE.BMP`, align: 1, xcoord: 58, ycoord: 0, action: 22, visibility: 3, visibility1: 2 },
      { image: `${BASE}/RESTOREBUTTON.BMP`, align: 1, xcoord: 58, ycoord: 0, action: 22, visibility: 3, visibility1: 1 },
      { image: `${BASE}/MINBUTTONDISABLED.BMP`, align: 1, xcoord: 83, ycoord: 0, action: -6, visibility: 23, visibility1: 20, visibility2: 1 },
      { image: `${BASE}/MINBUTTONINACTIVE.BMP`, align: 1, xcoord: 83, ycoord: 0, action: 23, visibility: 22, visibility1: 2 },
      { image: `${BASE}/MINBUTTON.BMP`, align: 1, xcoord: 83, ycoord: 0, action: 23, visibility: 22, visibility1: 1 },
      { image: `${BASE}/HELPBUTTONINACTIVE.BMP`, align: 1, xcoord: 58, ycoord: 0, action: 3, visibility: 13, visibility1: 21, visibility2: 23, visibility3: 2 },
      { image: `${BASE}/HELPBUTTON.BMP`, align: 1, xcoord: 58, ycoord: 0, action: 3, visibility: 13, visibility1: 21, visibility2: 23, visibility3: 1 },
      { image: `${BASE}/MAXBUTTONDISABLEDINACT.BMP`, align: 1, xcoord: 58, ycoord: 0, action: -6, visibility: 21, visibility1: 22, visibility2: 2 },
      { image: `${BASE}/RESTOREBUTTONDISABLEDI.BMP`, align: 1, xcoord: 58, ycoord: 0, action: -6, visibility: 3, visibility1: 21, visibility2: 22, visibility3: 2 },
      { image: `${BASE}/MINBUTTONDISABLEDINACT.BMP`, align: 1, xcoord: 83, ycoord: 0, action: -6, visibility: 23, visibility1: 20, visibility2: 2 },
      { align: 0, xcoord: 38, ycoord: 8, action: 11, visibility: 30 },
      { image: `${BASE}/ROLL.BMP`, align: 0, xcoord: 9, ycoord: 0, action: 4, visibility: 29 },
    ],

    comboButton: {
      image: `${BASE}/COMBOBOXDROPDOWNBUTTON.BMP`,
      mouseover: 1,
      leftwidth: 3,
      rightwidth: 4,
      topheight: 4,
      bottomheight: 4,
      tile: 0,
    },

    taskButton: {
      image: `${BASE}/DRTASKBANDTOOLBARBTN.BMP`,
      topheight: 4,
      bottomheight: 4,
      leftwidth: 4,
      rightwidth: 4,
    },

    progressBar: {
      image: `${BASE}/DRPROGRESSBAR.BMP`,
      topheight: 2,
      bottomheight: 2,
      leftwidth: 2,
      rightwidth: 2,
    },

    tabControl: {
      image: `${BASE}/DRTABITEM.BMP`,
      topheight: 2,
      bottomheight: 2,
      leftwidth: 2,
      rightwidth: 2,
    },

    startButton: { image: `${BASE}/DRTASKBARSTARTBUTTON.BMP` },

    colors: {
      window: [255, 255, 255],
      menu: [192, 192, 192],
      background: [192, 192, 192],
      buttonFace: [222, 222, 222],
      buttonHighlight: [255, 255, 255],
      buttonShadow: [168, 168, 168],
      buttonDarkShadow: [111, 111, 111],
      buttonLight: [232, 232, 232],
      highlight: [192, 192, 192],
      highlightText: [255, 255, 255],
      grayText: [110, 110, 110],
      gradientActiveTitle: [255, 255, 255],
      gradientInactiveTitle: [185, 185, 185],
      activeTitle: [85, 85, 85],
      inactiveTitle: [192, 192, 192],
      titleText: [255, 255, 255],
      inactiveTitleText: [216, 216, 216],
      buttonText: [0, 0, 0],
      menuText: [0, 0, 0],
      scrollbar: [213, 213, 213],
      menuBar: [192, 192, 192],
      menuHighlight: [192, 192, 192],
      infoWindow: [192, 192, 192],
      infoText: [255, 255, 255],
      appWorkspace: [221, 221, 221],
      activeBorder: [128, 128, 128],
      inactiveBorder: [128, 128, 128],
      windowFrame: [222, 222, 222],
      windowText: [0, 0, 0],
      buttonAlternateFace: [222, 222, 222],
      hotTrackingColor: [85, 85, 85],
    },

    customFonts: [
      { fontangle: 0, antialias: 1, fontname: 'Arial', fontheight: 11, italics: 0, underline: 0, fontweight: 400, shadowb: 128, shadowg: 128, shadowr: 128, shadowoffset: 1, drawingstyle: 1 },
      { fontname: 'Arial', fontheight: 16, drawingstyle: 0, fontweight: 700 },
      { fontname: 'Arial', fontheight: 16 },
      { fontname: 'Arial', fontheight: 12 },
      { fontname: 'Arial', fontheight: 24, drawingstyle: 1, fontweight: 700, shadowr: 255, shadowg: 255, shadowb: 255 },
      { fontname: 'Arial', fontheight: 16, drawingstyle: 1, fontweight: 700 },
      { fontname: 'Arial', fontheight: 16, drawingstyle: 1, shadowr: 255, shadowg: 255, shadowb: 255 },
    ],

    customColors: [
      { r: 255, g: 255, b: 255 },
      { r: 0, g: 0, b: 0 },
      { r: 0, g: 0, b: 0 },
      { r: 0, g: 0, b: 0 },
      { r: 161, g: 161, b: 161 },
      { r: 110, g: 110, b: 110 },
      { r: 128, g: 128, b: 128 },
      { r: 222, g: 222, b: 222 },
    ],

    fonts: {
      family: 'Arial',
      height: 11,
      weight: 400,
    },
  };
})();
