;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/MOREWINDOWS';

  skins['MOREWINDOWS'] = {
    name: 'More Windows',
    author: 'Morphh',
    email: 'jeffg2k@freewwweb.com',
    generator: 'BuilderBlinds ver 0.16.34, Build 72  - http://welcome.to/BuilderBlinds',
    wbVersion: 0,
    basePath: BASE,

    personality: {
      usestran: 0,
      buttoncount: 6,
      textalignment: 1,
      textshift: 85,
      textshiftvert: 0,
      textrightclip: 110,
      menubar: `${BASE}/MENU.BMP`,
      tileleftmenu: 0,
      tilerightmenu: 0,
      menulefttile: 4,
      menur: 0,
      menug: 0,
      menub: 0,
      activetextr: 0,
      activetextg: 0,
      activetextb: 0,
      inactivetextr: 84,
      inactivetextg: 116,
      inactivetextb: 152,
      menutextr: 50,
      menutextg: 50,
      menutextb: 50,
      top: `${BASE}/TOP.BMP`,
      left: `${BASE}/LEFT.BMP`,
      right: `${BASE}/RIGHT.BMP`,
      bottom: `${BASE}/BOTTOM.BMP`,
      toptopheight: 60,
      topbotheight: 90,
      lefttopheight: 32,
      leftbotheight: 5,
      righttopheight: 32,
      rightbotheight: 5,
      bottomtopheight: 5,
      bottombotheight: 110,
      topstretch: 1,
      leftstretch: 1,
      rightstretch: 1,
      bottomstretch: 1,
      anirate: 0,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      mouseover: 1,
      tripleimages: 1,
      soundenabled: 1,
      explorerbmp: `${BASE}/MDI.BMP`,
      dialogbmp: `${BASE}/DIALOG.BMP`,
      mdibmp: `${BASE}/MDI.BMP`,
      rollupsize: 30,
      rightclickaction: 4,
      tilemenu: 0,
      menuborders: `${BASE}/BORDERS.BMP`,
      maxbordercutleft: '1',
      maxbordercutright: '1',
      maxbordercuttop: '1',
      maxbordercutbottom: '1',
      noshape: '1',
    },

    buttons: {
      checkbutton: `${BASE}/CHECK.BMP`,
      radiobutton: `${BASE}/RADIO.BMP`,
      bitmap: `${BASE}/BUTTONS.BMP`,
      topheight: 4,
      bottomheight: 4,
      leftwidth: 4,
      rightwidth: 4,
      trans: 1,
    },

    titleButtons: [
      { image: '', align: 8, xcoord: 3, ycoord: 6, action: 11, visibility: 1 },
      { image: `${BASE}/ONTOP2.BMP`, align: 1, xcoord: 110, ycoord: 0, action: 6, alpha: 254, visibility: 0, insound: 'morewindows\\ontop.wav' },
      { image: `${BASE}/MIN.BMP`, align: 1, xcoord: 69, ycoord: 0, action: 23, alpha: 254, visibility: 0, insound: 'morewindows\\click.wav' },
      { image: `${BASE}/RESTORE.BMP`, align: 1, xcoord: 48, ycoord: 0, action: 22, alpha: 254, visibility: 0 },
      { image: `${BASE}/CLOSE.BMP`, align: 1, xcoord: 27, ycoord: 0, action: 0, alpha: 254, visibility: 0, insound: 'morewindows\\min.wav' },
      { image: `${BASE}/ONTOP.BMP`, align: 1, xcoord: 84, ycoord: 7, alpha: 254, visibility: 7 },
    ],

    comboButton: {
    },

    tabControl: {
      image: `${BASE}/TABS.BMP`,
      topheight: 2,
      bottomheight: 2,
      leftwidth: 2,
      rightwidth: 2,
    },

    startButton: { image: `${BASE}/STARTBUTTON.BMP` },

    colors: {
      background: [0, 0, 0],
      appWorkspace: [219, 221, 227],
      window: [255, 255, 255],
      windowText: [0, 0, 0],
      menu: [220, 220, 220],
      menuText: [0, 0, 0],
      activeTitle: [255, 255, 255],
      inactiveTitle: [156, 156, 156],
      titleText: [0, 0, 0],
      activeBorder: [211, 211, 211],
      inactiveBorder: [211, 211, 211],
      windowFrame: [0, 0, 0],
      scrollbar: [245, 245, 245],
      buttonFace: [235, 235, 235],
      buttonShadow: [156, 156, 156],
      buttonText: [0, 0, 0],
      grayText: [156, 156, 156],
      highlight: [55, 100, 175],
      highlightText: [255, 255, 255],
      inactiveTitleText: [80, 100, 130],
      buttonHighlight: [200, 200, 200],
      infoWindow: [255, 255, 255],
      buttonLight: [255, 255, 255],
      buttonDarkShadow: [119, 119, 119],
      infoText: [1, 0, 0],
      buttonAlternateFace: [235, 235, 235],
      hotTrackingColor: [55, 100, 175],
      gradientActiveTitle: [255, 255, 255],
      gradientInactiveTitle: [156, 156, 156],
    },

    fonts: {
      family: 'Tahoma',
      height: 15,
    },
  };
})();
