;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/LCARS TERMINAL COMPANION';

  skins['LCARS TERMINAL COMPANION'] = {
    name: 'star trek',
    author: 'bigjohn',
    generator: 'BuilderBlinds ver 1.1.3, Build 136  - http://stardock.com/builderblinds',
    wbVersion: 200,
    basePath: BASE,

    personality: {
      buttoncount: 11,
      usestran: 1,
      mouseover: 1,
      tripleimages: 1,
      textalignment: 0,
      textshift: 16,
      textshiftvert: 1,
      textrightclip: 130,
      toptopheight: 60,
      topbotheight: 50,
      lefttopheight: 25,
      leftbotheight: 25,
      righttopheight: 25,
      rightbotheight: 25,
      bottomtopheight: 0,
      bottombotheight: 0,
      topstretch: 0,
      leftstretch: 1,
      rightstretch: 0,
      bottomstretch: 0,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      anirate: 0,
      rollupsize: 92,
      soundenabled: 1,
      textbackground: 1,
      textonbottom: 0,
      doubleclickaction: 6,
      menur: 185,
      menug: 130,
      menub: 255,
      activetextr: 225,
      activetextg: 50,
      activetextb: 50,
      inactivetextr: 225,
      inactivetextg: 50,
      inactivetextb: 50,
      menutextr: 170,
      menutextg: 170,
      menutextb: 13,
      top: `${BASE}/TOP.BMP`,
      left: `${BASE}/LEFT.BMP`,
      right: `${BASE}/RIGHT.BMP`,
      bottom: `${BASE}/BOTTOM.BMP`,
      menubar: `${BASE}/MENU.BMP`,
      explorerbmp: `${BASE}/BLUE.BMP`,
      dialogbmp: `${BASE}/BLUE.BMP`,
      mdibmp: `${BASE}/RED.BMP`,
    },

    buttons: {
      checkbutton: `${BASE}/CHECKBOX.BMP`,
      bitmap: `${BASE}/BUTTON.BMP`,
      topheight: 5,
      bottomheight: 5,
      leftwidth: 5,
      rightwidth: 5,
    },

    titleButtons: [
      { image: `${BASE}/ROLL.BMP`, align: 1, xcoord: 74, ycoord: 46, action: 4 },
      { image: `${BASE}/CLOSE.BMP`, align: 1, xcoord: 74, ycoord: 22, action: 0 },
      { image: `${BASE}/MAX.BMP`, align: 1, xcoord: 74, ycoord: 118, action: 1 },
      { image: `${BASE}/MIN.BMP`, align: 1, xcoord: 74, ycoord: 142, action: 2 },
      { image: `${BASE}/BACK.BMP`, align: 1, xcoord: 74, ycoord: 94, action: 7 },
      { image: `${BASE}/FORWARD.BMP`, align: 1, xcoord: 74, ycoord: 70, action: 6 },
      { image: `${BASE}/ICON.BMP`, align: 0, xcoord: 21, ycoord: 3, action: 11 },
      { align: 3, xcoord: 73, ycoord: 24, action: -3, visibility: 0 },
      { image: `${BASE}/HELP.BMP`, align: 1, xcoord: 74, ycoord: -2, action: 3, visibility: 13 },
      { image: `${BASE}/ACTIVE.BMP`, align: 1, xcoord: 74, ycoord: 191, action: -1, visibility: 0 },
    ],

    comboButton: {},

    startButton: { image: `${BASE}/START.BMP` },

    colors: {
      scrollbar: [64, 128, 128],
      activeTitle: [0, 0, 100],
      background: [64, 128, 128],
      inactiveTitle: [10, 10, 10],
      menu: [64, 128, 128],
      window: [64, 128, 128],
      windowFrame: [255, 255, 255],
      menuText: [35, 197, 188],
      windowText: [5, 254, 241],
      titleText: [200, 50, 50],
      activeBorder: [255, 255, 255],
      inactiveBorder: [255, 255, 255],
      appWorkspace: [64, 128, 128],
      highlight: [100, 25, 25],
      highlightText: [200, 200, 200],
      buttonFace: [0, 0, 0],
      buttonShadow: [100, 100, 100],
      grayText: [125, 125, 125],
      buttonText: [250, 250, 250],
      inactiveTitleText: [200, 50, 50],
      buttonHighlight: [0, 0, 0],
      buttonDarkShadow: [100, 100, 100],
      buttonLight: [100, 100, 100],
      infoText: [255, 255, 255],
      infoWindow: [0, 0, 0],
      buttonAlternateFace: [255, 0, 0],
      hotTrackingColor: [255, 0, 0],
      gradientActiveTitle: [0, 0, 0],
      gradientInactiveTitle: [0, 0, 0],
    },

    fonts: {
      family: 'Arial',
      height: 11,
      weight: 400,
    },
  };
})();
