;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/BLUECURVE';

  skins['BLUECURVE'] = {
    name: 'Blue Curve: Red Hat Linux 8.0',
    author: 'Patric Fontaine (Paxx)',
    email: 'patricfontaine@hotmail.com',
    generator: 'Stardock SkinStudio ver 3.0.0, Build 553  - http://www.skinstudio.net',
    editorNotes: 'Do not copy, modify, adapt or distribute without my proper permission.',
    wbVersion: 400,
    basePath: BASE,

    personality: {
      colouraware: '1',
      top: `${BASE}/BORDER-TOP.BMP`,
      left: `${BASE}/BORDER-LEFT.BMP`,
      right: `${BASE}/BORDER-RIGHT.BMP`,
      bottom: `${BASE}/BORDER-BOTTOM.BMP`,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      toptopheight: 236,
      topbotheight: 59,
      bottomtopheight: 16,
      bottombotheight: 16,
      lefttopheight: 20,
      leftbotheight: 22,
      righttopheight: 20,
      rightbotheight: 22,
      topstretch: 0,
      leftstretch: 0,
      rightstretch: 0,
      bottomstretch: 0,
      buttoncount: 15,
      textalignment: 0,
      textshift: 22,
      textshiftvert: 2,
      textrightclip: 110,
      anirate: 0,
      menur: 49,
      menug: 106,
      menub: 197,
      activetextr: 255,
      activetextg: 255,
      activetextb: 255,
      inactivetextr: 156,
      inactivetextg: 154,
      inactivetextb: 156,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      rollupsize: 30,
      mouseover: 1,
      tripleimages: 1,
      soundenabled: 0,
      tilemenu: 1,
      menubar: `${BASE}/MENUBAR.TGA`,
      menuborders: `${BASE}/BLUE_MENUFRAME_.BMP`,
      maxbordercutleft: '2',
      maxbordercutright: '2',
      maxbordercuttop: '1',
      maxbordercutbottom: '2',
      wallpaper: 'BlueCurve\\wallpaper.bmp',
    },

    buttons: {
      checkbutton: `${BASE}/BLUE_CHECKBOX.BMP`,
      radiobutton: `${BASE}/BUTTON_RADIO.BMP`,
      bitmap: `${BASE}/BUTTONS.TGA`,
      topheight: 3,
      bottomheight: 3,
      leftwidth: 3,
      rightwidth: 3,
      mouseover: 1,
      enhancedmode: '1',
      tile: '1',
    },

    titleButtons: [
      { image: `${BASE}/BUTTON_EXIT.BMP`, align: 1, xcoord: 21, ycoord: 0, action: 0, linkedto: 2, visibility: 31, visibility1: 2 },
      { image: `${BASE}/BUTTON_EXIT_DIABLED.BMP`, align: 1, xcoord: 21, ycoord: 0, action: -6, visibility: 55 },
      { image: `${BASE}/BUTTON_EXIT.BMP`, align: 1, xcoord: 21, ycoord: 0, action: 0, visibility: 0 },
      { image: `${BASE}/BUTTON_MAXIMIZE_DISABLED.BMP`, align: 1, xcoord: 42, ycoord: 0, action: -6, visibility: 21, visibility1: 22 },
      { image: `${BASE}/BUTTON_MAXIMIZE.BMP`, align: 1, xcoord: 42, ycoord: 0, action: 22, linkedto: 5, visibility: 31, visibility1: 4, visibility2: 2 },
      { image: `${BASE}/BUTTON_MAXIMIZE.BMP`, align: 1, xcoord: 42, ycoord: 0, action: 22, visibility: 4, visibility1: 20 },
      { image: `${BASE}/BUTTON_RESTORE_DISABLED.BMP`, align: 1, xcoord: 42, ycoord: 0, action: -6, visibility: 21, visibility1: 22, visibility2: 3 },
      { image: `${BASE}/BUTTON_RESTORE.BMP`, align: 1, xcoord: 42, ycoord: 0, action: 22, linkedto: 8, visibility: 31, visibility1: 2 },
      { image: `${BASE}/BUTTON_RESTORE.BMP`, align: 1, xcoord: 42, ycoord: 0, action: 22, visibility: 3 },
      { image: `${BASE}/BUTTON_MINIMIZE_DISABLED.BMP`, align: 1, xcoord: 63, ycoord: 0, action: -6, visibility: 23, visibility1: 20 },
      { image: `${BASE}/BUTTON_MINIMIZE.BMP`, align: 1, xcoord: 63, ycoord: 0, action: 23, linkedto: 11, visibility: 31, visibility1: 22, visibility2: 2 },
      { image: `${BASE}/BUTTON_MINIMIZE.BMP`, align: 1, xcoord: 63, ycoord: 0, action: 23, visibility: 22 },
      { image: `${BASE}/BUTTON_HELP.BMP`, align: 1, xcoord: 42, ycoord: 0, action: 3, visibility: 13, visibility1: 21, visibility2: 23 },
      { image: `${BASE}/BUTTON_HELP.BMP`, align: 1, xcoord: 84, ycoord: 0, action: 3, visibility: 13, visibility1: 26 },
      { image: `${BASE}/BUTTON_SYSTEM.BMP`, align: 0, xcoord: 0, ycoord: 0, action: 12 },
    ],

    comboButton: {
      image: `${BASE}/COMBOBOX_BUTTON.BMP`,
      topheight: 2,
      bottomheight: 2,
      leftwidth: 2,
      rightwidth: 2,
      tile: 0,
      mouseover: 1,
    },

    taskButton: {
      image: `${BASE}/TASKBAR_BUTTONSXP.BMP`,
      topheight: 3,
      bottomheight: 3,
      leftwidth: 3,
      rightwidth: 3,
    },

    progressBar: {
      image: `${BASE}/PROGRESS.BMP`,
      topheight: 3,
      bottomheight: 3,
      leftwidth: 3,
      rightwidth: 3,
    },

    tabControl: {
      image: `${BASE}/TABS.BMP`,
      topheight: 3,
      bottomheight: 3,
      leftwidth: 3,
      rightwidth: 3,
    },

    startButton: { image: `${BASE}/START-BUTTON-NO-XP.BMP` },

    colors: {
      scrollbar: [231, 231, 231],
      window: [255, 255, 255],
      menu: [231, 231, 231],
      background: [82, 97, 165],
      buttonFace: [231, 231, 231],
      highlight: [82, 97, 165],
      activeTitle: [82, 97, 165],
      titleText: [255, 255, 255],
      inactiveTitle: [231, 231, 231],
      inactiveTitleText: [156, 154, 156],
      gradientActiveTitle: [231, 231, 231],
      gradientInactiveTitle: [231, 231, 231],
      highlightText: [255, 255, 255],
      windowFrame: [0, 0, 0],
      activeBorder: [231, 231, 231],
      menuText: [0, 0, 0],
      windowText: [0, 0, 0],
      inactiveBorder: [231, 231, 231],
      appWorkspace: [231, 231, 231],
      grayText: [150, 150, 150],
      buttonText: [0, 0, 0],
      buttonHighlight: [255, 255, 255],
      buttonDarkShadow: [175, 175, 175],
      buttonShadow: [210, 210, 210],
      buttonLight: [245, 245, 245],
      infoText: [0, 0, 0],
      infoWindow: [255, 254, 206],
      buttonAlternateFace: [231, 231, 231],
      hotTrackingColor: [82, 97, 165],
      menuBar: [82, 97, 165],
      menuHighlight: [62, 73, 136],
    },

    subSkins: [
      { id: 'default', name: 'Bluecurve (Default)' },
      {
        id: 'green',
        name: 'Greencurve',
        colors: {
          background: [78, 134, 78],
          highlight: [78, 134, 78],
          activeTitle: [78, 134, 78],
          hotTrackingColor: [78, 134, 78],
          menuBar: [78, 134, 78],
          menuHighlight: [58, 110, 58],
        },
      },
      {
        id: 'red',
        name: 'Redcurve',
        colors: {
          background: [165, 82, 82],
          highlight: [165, 82, 82],
          activeTitle: [165, 82, 82],
          hotTrackingColor: [165, 82, 82],
          menuBar: [165, 82, 82],
          menuHighlight: [136, 62, 62],
        },
      },
    ],

    customFonts: [
      { fontangle: 0, antialias: 1, fontname: 'Arial', fontheight: 11, italics: 0, underline: 0, fontweight: 400, shadowb: 128, shadowg: 128, shadowr: 128, shadowoffset: 0, drawingstyle: 0 },
      { fontname: 'Arial', fontheight: 36, fontweight: 700, fontangle: 0, drawingstyle: 1, shadowr: 0, shadowg: 0, shadowb: 0, shadowoffset: 2 },
    ],

    customColors: [
      { r: 0, g: 0, b: 0 },
      { r: 255, g: 255, b: 255 },
    ],

    fonts: {
      family: 'Arial',
      height: 11,
      weight: 400,
    },
  };
})();
