;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/APOLLO';

  skins['APOLLO'] = {
    name: 'Apollo',
    author: 'Mike Bryant',
    email: 'mike@skinplant.com',
    url: 'http://www.skinplant.com',
    generator: 'Stardock SkinStudio Professional ver 3.9.7, Build 811  - http://www.skinstudio.net',
    editorNotes: 'This skin is copyrighted to Mike Bryant.  http://www.skinplant.com',
    wbVersion: 400,
    basePath: BASE,

    personality: {
      colouraware: '0',
      top: `${BASE}/FRAMETOP.BMP`,
      left: `${BASE}/FRAMELEFT.BMP`,
      right: `${BASE}/FRAMERIGHT.BMP`,
      bottom: `${BASE}/FRAMEBOTTOM.BMP`,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      toptopheight: 12,
      topbotheight: 107,
      bottomtopheight: 2,
      bottombotheight: 2,
      lefttopheight: 36,
      leftbotheight: 7,
      righttopheight: 36,
      rightbotheight: 7,
      topstretch: 0,
      leftstretch: 0,
      rightstretch: 0,
      bottomstretch: 0,
      buttoncount: 5,
      textalignment: 0,
      textshift: 28,
      textshiftvert: 4,
      textrightclip: 115,
      anirate: 0,
      menur: 97,
      menug: 97,
      menub: 97,
      activetextr: 0,
      activetextg: 0,
      activetextb: 0,
      inactivetextr: 79,
      inactivetextg: 79,
      inactivetextb: 79,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      rollupsize: 43,
      mouseover: 1,
      tripleimages: 0,
      soundenabled: 1,
      tilemenu: 0,
      menubar: `${BASE}/MENU.BMP`,
      menuborders: `${BASE}/MENUFRAME.BMP`,
      maxbordercutleft: '0',
      maxbordercutright: '0',
      maxbordercuttop: '0',
      maxbordercutbottom: '0',
      textshiftnoicon: '11',
      rightclickaction: 4,
      textonbottom: '0',
      hidecaptiontext: '0',
      dynamicframe: 0,
      groupfortextbackground: '30',
      groupforwindowframe: '30',
      groupfortitlebarmenu: '30',
      groupfortitlebar: '30',
      groupfortitlebarbuttons: '30',
      groupforbackgrounds: '30',
      groupforscripting: '30',
      explorerbmp: `${BASE}/EXPLORER_BG.BMP`,
      mdibmp: `${BASE}/DIALOG_BG.BMP`,
      dialogbmp: `${BASE}/DIALOG_BG.BMP`,
      tileleftmenu: 15,
      tilerightmenu: 4,
      fadelinkedbuttons: 1,
      menulefttile: 11,
      textrightclipnoicon: '115',
      mditransparent: '0',
      ignoredialogbitmap: '0',
      activealpha: '255',
      inactivealpha: '255',
      textbackground: '0',
    },

    buttons: {
      checkbutton: `${BASE}/CHECKBOX.BMP`,
      radiobutton: `${BASE}/RADIO.BMP`,
      bitmap: `${BASE}/BUTTONS.BMP`,
      topheight: 11,
      bottomheight: 7,
      leftwidth: 10,
      rightwidth: 9,
      mouseover: 1,
      enhancedmode: '1',
      tile: '2',
      trans: 1,
      focuscolour: '2',
      mouseovercolour: '2',
      disabledcolour: '3',
      normalcolour: '2',
      pressedcolour: '2',
      defaultcolour: '2',
      normalfont: 1,
      pressedfont: 1,
      disabledfont: 2,
      defaultfont: 1,
      focusfont: 1,
      mouseoverfont: 1,
      radioperpixel: '1',
      perpixel: '1',
      contenttop: '1',
      contentbottom: '6',
      contentright: '3',
      checkperpixel: '1',
      alpha: 255,
      contentleft: '3',
      textfont: '1',
      textcolour: '2',
    },

    titleButtons: [
      { image: `${BASE}/CLOSE.BMP`, align: 1, xcoord: 63, ycoord: 4, action: 0, alpha: 255, visibility: 0, insound: 'Apollo\\Bleeep.wav' },
      { image: `${BASE}/MAXIMIZE.BMP`, align: 1, xcoord: 86, ycoord: 4, action: 22, visibility: 20, insound: 'Apollo\\Bleeep.wav' },
      { image: `${BASE}/MINIMIZE.BMP`, align: 1, xcoord: 113, ycoord: 4, action: 23, visibility: 22, insound: 'Apollo\\Bleeep.wav' },
      { align: 0, xcoord: 19, ycoord: 2, action: 11, visibility: 27, insound: 'Apollo\\Bleeep.wav' },
      { image: `${BASE}/ROLLUP.BMP`, align: 1, xcoord: 25, ycoord: 22, action: 4, insound: 'Apollo\\Bleeep.wav' },
    ],

    comboButton: {
      image: `${BASE}/COMBOBUTTON.BMP`,
      topheight: 8,
      bottomheight: 5,
      leftwidth: 5,
      rightwidth: 5,
      tile: 2,
      mouseover: 1,
    },

    taskButton: {
      image: `${BASE}/TASKBUTTON.BMP`,
      topheight: 5,
      bottomheight: 5,
      leftwidth: 5,
      rightwidth: 5,
      tile: 1,
      mouseover: 1,
      trans: 1,
    },

    progressBar: {
      image: `${BASE}/PROGRESSBAR.BMP`,
      topheight: 8,
      bottomheight: 7,
      leftwidth: 4,
      rightwidth: 3,
      tile: 2,
      tilemode: 0,
      trans: 1,
    },

    tabControl: {
      image: `${BASE}/TABS.BMP`,
      topheight: 6,
      bottomheight: 1,
      leftwidth: 10,
      rightwidth: 10,
      tile: 2,
      mouseover: 1,
      trans: 1,
    },

    startButton: { image: `${BASE}/STARTBUTTONXP.BMP` },

    colors: {
      scrollbar: [178, 178, 178],
      window: [255, 255, 255],
      menu: [178, 178, 178],
      background: [54, 54, 54],
      buttonFace: [178, 178, 178],
      highlight: [0, 0, 0],
      activeTitle: [148, 148, 148],
      titleText: [0, 0, 0],
      inactiveTitle: [178, 178, 178],
      inactiveTitleText: [79, 79, 79],
      gradientActiveTitle: [148, 148, 148],
      gradientInactiveTitle: [178, 178, 178],
      highlightText: [255, 255, 255],
      windowFrame: [0, 0, 0],
      activeBorder: [148, 148, 148],
      menuText: [0, 0, 0],
      windowText: [0, 0, 0],
      inactiveBorder: [148, 148, 148],
      appWorkspace: [178, 178, 178],
      grayText: [54, 54, 54],
      buttonText: [0, 0, 0],
      buttonHighlight: [202, 202, 202],
      buttonDarkShadow: [79, 79, 79],
      buttonShadow: [101, 101, 101],
      buttonLight: [195, 195, 195],
      infoText: [0, 0, 0],
      infoWindow: [178, 178, 178],
      buttonAlternateFace: [148, 148, 148],
      hotTrackingColor: [233, 36, 36],
      menuBar: [178, 178, 178],
      menuHighlight: [158, 158, 158],
    },

    customFonts: [
      { fontname: 'Microsoft Sans Serif', fontweight: 600, drawingstyle: 1, shadowoffset: 1, antialias: 1, fontheight: 13, shadowr: 205, shadowg: 209, shadowb: 217, fontangle: 0 },
      { fontname: 'Arial', fontweight: 400, drawingstyle: 1, fontheight: 14, shadowr: 186, shadowg: 186, shadowb: 186, antialias: 1, shadowoffset: 1, fontangle: 0 },
      { fontname: 'Tahoma', fontweight: 400, drawingstyle: 1, fontheight: 12, shadowr: 202, shadowg: 202, shadowb: 202, antialias: 1, shadowoffset: 1, fontangle: 0, italics: 0 },
      { fontname: 'Tahoma', fontweight: 400, drawingstyle: 2, shadowoffset: 1, antialias: 1, fontheight: 12, shadowr: 106, shadowg: 135, shadowb: 168, fontangle: 0 },
      { fontname: 'Arial', fontheight: 14, fontweight: 400, fontangle: 0, shadowoffset: 0, drawingstyle: 0, shadowr: 140, shadowg: 140, shadowb: 140 },
      { fontname: 'Arial', fontheight: 14, fontweight: 700, shadowr: 41, shadowg: 53, shadowb: 71, drawingstyle: 0, shadowoffset: 0 },
      { fontname: 'Microsoft Sans Serif', fontheight: 14, fontweight: 400, shadowr: 220, shadowg: 223, shadowb: 230, drawingstyle: 1 },
      { fontname: 'Microsoft Sans Serif', fontheight: 14, fontweight: 400, shadowr: 205, shadowg: 209, shadowb: 217, drawingstyle: 1 },
      { fontname: 'Microsoft Sans Serif', fontheight: 26, fontweight: 700, shadowoffset: 1, drawingstyle: 1, shadowr: 234, shadowg: 236, shadowb: 238 },
      { fontname: 'Arial', fontheight: 14, fontweight: 700, drawingstyle: 0, fontangle: 1, shadowr: 73, shadowg: 79, shadowb: 91 },
      { fontname: 'Microsoft Sans Serif', fontheight: 13, drawingstyle: 1, shadowr: 234, shadowg: 236, shadowb: 238 },
      { fontname: 'Microsoft Sans Serif', fontheight: 14, fontweight: 400, shadowr: 219, shadowg: 221, shadowb: 227, drawingstyle: 1 },
      { fontname: 'Tahoma', fontweight: 700, fontheight: 14 },
      { fontname: 'Arial', fontheight: 13, fontweight: 400, fontangle: 0, shadowoffset: 1, drawingstyle: 0, shadowr: 186, shadowg: 186, shadowb: 186, italics: 0 },
      { fontname: 'FFF Galaxy', fontheight: 20, fontweight: 700, shadowr: 186, shadowg: 186, shadowb: 186, drawingstyle: 1, antialias: 0, italics: 0, underline: 0, fontangle: 0 },
      { fontname: 'Tahoma', fontheight: 12, fontweight: 700, shadowr: 128, shadowg: 128, shadowb: 128, drawingstyle: 2 },
      { fontname: 'Arial', fontheight: 16, fontweight: 700, drawingstyle: 0, shadowr: 255, shadowg: 255, shadowb: 255 },
    ],

    customColors: [
      { r: 0, g: 0, b: 0 },
      { r: 27, g: 35, b: 47 },
      { r: 0, g: 0, b: 0 },
      { r: 101, g: 101, b: 101 },
      { r: 76, g: 76, b: 76 },
      { r: 255, g: 255, b: 255 },
      { r: 215, g: 215, b: 215 },
      { r: 198, g: 203, b: 206 },
      { r: 0, g: 0, b: 0 },
      { r: 73, g: 78, b: 87 },
      { r: 255, g: 255, b: 255 },
      { r: 227, g: 4, b: 4 },
    ],

    fonts: {
      family: 'FFF Galaxy',
      height: 10,
      weight: 700,
    },
  };
})();
