/*
 * RZIP Long-Range Redundancy Elimination Compression Algorithm
 * Compatible with AlgorithmFramework
 * (c)2006-2025 Hawkynt
 *
 * RZIP was devised by Andrew Tridgell, growing out of the block-matching ideas behind
 * rsync and first described in his PhD thesis "Efficient Algorithms for Sorting and
 * Synchronization" (Australian National University, 1999). The original rzip tool
 * (https://rzip.samba.org/) builds a hash-indexed dictionary across the WHOLE input
 * file (historically up to 900 MB) rather than a small sliding window, so it can find
 * and encode duplicated regions at arbitrary distances - something ordinary LZ77/DEFLATE
 * cannot do because their history buffer is capped at 32-64 KB. Stage 1 emits a compact
 * stream of literal runs and (offset,length) copy tokens; stage 2 pipes that stream
 * through an external general-purpose compressor (bzip2) for entropy coding.
 *
 * Note: this implementation replicates rzip's stage-1 design (a rolling hash built over
 * the entire processed input, so matches can be found and copied from anywhere already
 * seen, not just a recent window) and, because every algorithm file in this project must
 * be a self-contained standalone module with no external tooling or other files to import,
 * adds its own lightweight order-0 canonical Huffman entropy stage for the literal bytes
 * in place of the external bzip2 stage upstream rzip relies on.
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD
    define(['../../AlgorithmFramework', '../../OpCodes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // Node.js/CommonJS
    module.exports = factory(
      require('../../AlgorithmFramework'),
      require('../../OpCodes')
    );
  } else {
    // Browser/Worker global
    factory(root.AlgorithmFramework, root.OpCodes);
  }
}((function() {
  if (typeof globalThis !== 'undefined') return globalThis;
  if (typeof window !== 'undefined') return window;
  if (typeof global !== 'undefined') return global;
  if (typeof self !== 'undefined') return self;
  throw new Error('Unable to locate global object');
})(), function (AlgorithmFramework, OpCodes) {
  'use strict';

  if (!AlgorithmFramework) {
    throw new Error('AlgorithmFramework dependency is required');
  }

  if (!OpCodes) {
    throw new Error('OpCodes dependency is required');
  }

  // Extract framework components
  const { RegisterAlgorithm, CategoryType, ComplexityType, CountryCode,
          CompressionAlgorithm, IAlgorithmInstance, TestCase, LinkItem } = AlgorithmFramework;

  // ===== DETERMINISTIC TEST-VECTOR HELPERS =====
  // Pure arithmetic (multiply/add/mod) linear congruential generator - no bitwise
  // operators are used, since generated bytes only need to be reproducible, not
  // cryptographically random.

  function genPseudoRandomBytes(count, seed) {
    const bytes = [];
    let state = seed % 4294967296;
    for (let i = 0; i < count; ++i) {
      state = (state * 1664525 + 1013904223) % 4294967296;
      bytes.push(Math.floor(state / 16777216) % 256);
    }
    return bytes;
  }

  // ===== VARIABLE-LENGTH INTEGER ENCODING (LEB128-style, arithmetic only) =====

  const VarInt = {
    write(out, value) {
      let v = value;
      for (;;) {
        const byte = v % 128;
        v = Math.floor(v / 128);
        if (v > 0) {
          out.push(byte + 128);
        } else {
          out.push(byte);
          break;
        }
      }
    },

    read(bytes, pos) {
      let result = 0;
      let mult = 1;
      for (;;) {
        const byte = bytes[pos.p++];
        result += (byte % 128) * mult;
        if (byte < 128) break;
        mult *= 128;
      }
      return result;
    }
  };

  // ===== BIT-LEVEL I/O FOR THE LITERAL ENTROPY STAGE =====
  // A private, self-consistent bit packing (bits are appended LSB-first within each byte);
  // encoder and decoder only need to agree with each other, not with any external format.

  class BitWriter {
    constructor() {
      this.bytes = [];
      this.buffer = 0;
      this.bitCount = 0;
    }

    writeBit(bit) {
      this.buffer = OpCodes.ToUint32(OpCodes.OrN(this.buffer, OpCodes.Shl32(bit, this.bitCount)));
      ++this.bitCount;
      if (this.bitCount === 8) {
        this.bytes.push(OpCodes.AndN(this.buffer, 0xFF));
        this.buffer = 0;
        this.bitCount = 0;
      }
    }

    // Writes 'length' bits of 'value', most-significant bit first.
    writeBits(value, length) {
      for (let i = length - 1; i >= 0; --i) {
        const bit = OpCodes.AndN(OpCodes.Shr32(value, i), 1);
        this.writeBit(bit);
      }
    }

    flush() {
      if (this.bitCount > 0) {
        this.bytes.push(OpCodes.AndN(this.buffer, 0xFF));
        this.buffer = 0;
        this.bitCount = 0;
      }
      return this.bytes;
    }
  }

  class BitReader {
    constructor(bytes) {
      this.bytes = bytes;
      this.bytePos = 0;
      this.buffer = 0;
      this.bitPos = 8;
    }

    readBit() {
      if (this.bitPos === 8) {
        if (this.bytePos >= this.bytes.length) {
          throw new Error('Unexpected end of literal bit stream');
        }
        this.buffer = this.bytes[this.bytePos++];
        this.bitPos = 0;
      }
      const bit = OpCodes.AndN(OpCodes.Shr32(this.buffer, this.bitPos), 1);
      ++this.bitPos;
      return bit;
    }
  }

  // ===== CANONICAL HUFFMAN CODING (order-0, 256-symbol byte alphabet) =====

  class HuffmanTree {
    constructor() {
      this.root = null;
      this.codes = null;
    }

    static buildFromLengths(lengths) {
      const tree = new HuffmanTree();
      let maxLen = 0;
      for (const len of lengths) if (len > maxLen) maxLen = len;
      if (maxLen === 0) return tree;

      const blCount = new Array(maxLen + 1).fill(0);
      for (const len of lengths) if (len > 0) ++blCount[len];

      const nextCode = new Array(maxLen + 1).fill(0);
      let code = 0;
      blCount[0] = 0;
      for (let bits = 1; bits <= maxLen; ++bits) {
        code = OpCodes.ToUint32((code + blCount[bits - 1]) * 2);
        nextCode[bits] = code;
      }

      const codes = new Array(lengths.length);
      for (let symbol = 0; symbol < lengths.length; ++symbol) {
        const len = lengths[symbol];
        if (len !== 0) {
          codes[symbol] = { code: nextCode[len], length: len };
          ++nextCode[len];
        }
      }

      tree.root = {};
      for (let symbol = 0; symbol < codes.length; ++symbol) {
        if (!codes[symbol]) continue;

        let node = tree.root;
        const { code: symCode, length } = codes[symbol];

        for (let i = length - 1; i >= 0; --i) {
          const bit = OpCodes.AndN(OpCodes.Shr32(symCode, i), 1);
          const key = bit ? 'one' : 'zero';

          if (i === 0) {
            node[key] = { symbol };
          } else {
            if (!node[key]) node[key] = {};
            node = node[key];
          }
        }
      }

      tree.codes = codes;
      return tree;
    }

    decode(bitReader) {
      let node = this.root;
      if (!node) throw new Error('Invalid Huffman tree');

      while (node.symbol === undefined) {
        const bit = bitReader.readBit();
        node = bit ? node.one : node.zero;
        if (!node) throw new Error('Invalid Huffman code');
      }

      return node.symbol;
    }

    encode(symbol) {
      if (!this.codes || !this.codes[symbol]) {
        throw new Error(`No Huffman code for symbol ${symbol}`);
      }
      return this.codes[symbol];
    }
  }

  // Builds a set of prefix-free code lengths (one per byte value 0-255) from observed
  // frequencies using a classic bottom-up Huffman merge. Symbols that never occur keep
  // length 0 (no code). A single distinct symbol is forced to length 1.
  function buildHuffmanLengths(freqs) {
    const symbols = [];
    for (let s = 0; s < 256; ++s) if (freqs[s] > 0) symbols.push(s);

    const lengths = new Array(256).fill(0);
    if (symbols.length === 0) return lengths;
    if (symbols.length === 1) {
      lengths[symbols[0]] = 1;
      return lengths;
    }

    let heap = symbols.map(s => ({ freq: freqs[s], symbol: s, left: null, right: null }));
    while (heap.length > 1) {
      heap.sort((a, b) => a.freq - b.freq);
      const a = heap.shift();
      const b = heap.shift();
      heap.push({ freq: a.freq + b.freq, symbol: -1, left: a, right: b });
    }

    const assign = (node, depth) => {
      if (node.symbol >= 0) {
        lengths[node.symbol] = depth;
        return;
      }
      assign(node.left, depth + 1);
      assign(node.right, depth + 1);
    };
    assign(heap[0], 0);

    return lengths;
  }

  // ===== RZIP ALGORITHM =====

  class RZIPAlgorithm extends CompressionAlgorithm {
    constructor() {
      super();

      // Required metadata
      this.name = "RZIP";
      this.description = "Long-range redundancy-elimination compressor that indexes the entire input with a rolling hash so LZ77-style (offset,length) matches can be found at arbitrary distances, far beyond a classic 32K/64K sliding window. Literal bytes are entropy-coded with a self-contained order-0 canonical Huffman stage.";
      this.inventor = "Andrew Tridgell";
      this.year = 1998;
      this.category = CategoryType.COMPRESSION;
      this.subCategory = "Long-Range";
      this.securityStatus = null;
      this.complexity = ComplexityType.ADVANCED;
      this.country = CountryCode.AU;

      // Matcher configuration (rolling hash window / minimum match length)
      this.MIN_MATCH = 16;             // Rolling hash window size in bytes
      this.HASH_BUCKET_CAP = 64;       // Maximum stored candidate positions per hash bucket
      this.CANDIDATE_SEARCH_LIMIT = 32;// Maximum candidates examined per position
      this.ROLLING_HASH_BASE = 257;    // Polynomial rolling hash multiplier

      // Literal entropy stage configuration
      this.LITERAL_HUFFMAN_THRESHOLD = 32; // Minimum literal count before bothering with a Huffman table
      this.MAX_CODE_LENGTH = 24;           // Safety cap; falls back to raw storage if exceeded

      // Documentation
      this.documentation = [
        new LinkItem("rzip - a large-file compression program (project home)", "https://rzip.samba.org/"),
        new LinkItem("Andrew Tridgell, \"Efficient Algorithms for Sorting and Synchronization\" (PhD thesis, ANU, 1999)", "https://www.samba.org/~tridge/phd_thesis.pdf"),
        new LinkItem("rzip(1) manual page", "https://manpages.ubuntu.com/manpages/focal/man1/rzip.1.html")
      ];

      this.references = [
        new LinkItem("Rzip - Wikipedia", "https://en.wikipedia.org/wiki/Rzip"),
        new LinkItem("lrzip - Long Range ZIP (rzip descendant)", "https://github.com/ckolivas/lrzip")
      ];

      // Test vectors - round-trip compression tests
      const longMarker = OpCodes.AnsiToBytes("RZIP-LONG-RANGE-MARKER-BLOCK-0123456789ABCDEF");
      const longFiller = genPseudoRandomBytes(40000, 987654321);
      const longRangeVector = longMarker.concat(longFiller).concat(longMarker);

      const alternating = [];
      for (let i = 0; i < 600; ++i) alternating.push(i % 2 === 0 ? 0x58 : 0x59);

      this.tests = [
        new TestCase(
          [],
          [], // Empty expected for round-trip test
          "RZIP round-trip - empty input",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          [0x41],
          [], // Empty expected for round-trip test
          "RZIP round-trip - single byte",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          new Array(2000).fill(0x42),
          [], // Empty expected for round-trip test
          "RZIP round-trip - long repetitive run (2000 bytes)",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          alternating,
          [], // Empty expected for round-trip test
          "RZIP round-trip - alternating byte pattern",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          genPseudoRandomBytes(500, 12345),
          [], // Empty expected for round-trip test
          "RZIP round-trip - pseudo-random binary sample",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          longRangeVector,
          [], // Empty expected for round-trip test
          "RZIP round-trip - identical blocks separated by 40KB of filler (long-range match, exceeds a 32K/64K sliding window)",
          "https://www.samba.org/~tridge/phd_thesis.pdf"
        ),
        new TestCase(
          OpCodes.AnsiToBytes("RZIP finds long distance redundancy in the whole file using a rolling hash dictionary, then relies on a second stage compressor for entropy coding of the literal data."),
          [], // Empty expected for round-trip test
          "RZIP round-trip - spec-flavoured description text",
          "https://rzip.samba.org/"
        )
      ];
    }

    CreateInstance(isInverse = false) {
      return new RZIPInstance(this, isInverse);
    }
  }

  /**
   * RZIP compression instance implementing the Feed/Result pattern.
   * @class
   * @extends {IAlgorithmInstance}
   */

  class RZIPInstance extends IAlgorithmInstance {
    constructor(algorithm, isInverse = false) {
      super(algorithm);
      this.isInverse = isInverse;
      this.inputBuffer = [];
    }

    Feed(data) {
      if (!data || data.length === 0) return;
      // Long-range matching implies large inputs; avoid a spread-argument call-stack
      // overflow that a naive push(...data) would hit on big arrays.
      for (let i = 0; i < data.length; ++i) this.inputBuffer.push(data[i]);
    }

    Result() {
      if (this.inputBuffer.length === 0) return [];

      const result = this.isInverse ?
        this._decompress(this.inputBuffer) :
        this._compress(this.inputBuffer);

      this.inputBuffer = [];
      return result;
    }

    // ===== COMPRESSION =====

    _compress(data) {
      if (data.length === 0) return [];

      const { tokens, literalBytes } = this._findTokens(data);
      const out = [];

      VarInt.write(out, data.length);
      VarInt.write(out, tokens.length);

      for (const t of tokens) {
        if (t.literal) {
          out.push(0);
          VarInt.write(out, t.length);
        } else {
          out.push(1);
          VarInt.write(out, t.distance);
          VarInt.write(out, t.length);
        }
      }

      this._writeLiteralStream(out, literalBytes);

      return out;
    }

    // Long-range LZ77-style matcher: a polynomial rolling hash over MIN_MATCH-byte
    // windows is indexed for every scanned position across the WHOLE input processed
    // so far (never discarded due to distance), which is what lets matches be found
    // arbitrarily far back rather than only within a small recent window.
    _findTokens(data) {
      const algorithm = this.algorithm;
      const MIN_MATCH = algorithm.MIN_MATCH;
      const n = data.length;
      const tokens = [];
      const literalBytes = [];

      if (n === 0) return { tokens, literalBytes };

      if (n < MIN_MATCH) {
        tokens.push({ literal: true, length: n });
        for (let i = 0; i < n; ++i) literalBytes.push(data[i]);
        return { tokens, literalBytes };
      }

      const base = algorithm.ROLLING_HASH_BASE;
      let basePow = 1;
      for (let i = 0; i < MIN_MATCH - 1; ++i) basePow = OpCodes.ToUint32(basePow * base);

      const hashAt = (pos) => {
        let h = 0;
        for (let i = 0; i < MIN_MATCH; ++i) h = OpCodes.ToUint32(h * base + data[pos + i]);
        return h;
      };

      const hashTable = new Map();
      const insert = (h, pos) => {
        let bucket = hashTable.get(h);
        if (!bucket) {
          bucket = [];
          hashTable.set(h, bucket);
        }
        bucket.push(pos);
        if (bucket.length > algorithm.HASH_BUCKET_CAP) bucket.shift();
      };

      const lastPos = n - MIN_MATCH;
      let pos = 0;
      let literalStart = 0;
      let h = hashAt(0);
      let hValid = true;

      while (pos <= lastPos) {
        if (!hValid) {
          h = hashAt(pos);
          hValid = true;
        }

        let bestLen = 0;
        let bestPos = -1;
        const bucket = hashTable.get(h);
        if (bucket) {
          const start = Math.max(0, bucket.length - algorithm.CANDIDATE_SEARCH_LIMIT);
          for (let bi = bucket.length - 1; bi >= start; --bi) {
            const cand = bucket[bi];
            const maxLen = n - pos;
            let len = 0;
            while (len < maxLen && data[cand + len] === data[pos + len]) ++len;
            if (len >= MIN_MATCH && len > bestLen) {
              bestLen = len;
              bestPos = cand;
            }
          }
        }

        insert(h, pos);

        if (bestLen >= MIN_MATCH) {
          if (pos > literalStart) {
            tokens.push({ literal: true, length: pos - literalStart });
            for (let i = literalStart; i < pos; ++i) literalBytes.push(data[i]);
          }
          tokens.push({ literal: false, distance: pos - bestPos, length: bestLen });
          pos += bestLen;
          literalStart = pos;
          hValid = false;
        } else {
          if (pos < lastPos) {
            const outByte = data[pos];
            const inByte = data[pos + MIN_MATCH];
            h = OpCodes.ToUint32(h - OpCodes.ToUint32(outByte * basePow));
            h = OpCodes.ToUint32(h * base + inByte);
          }
          ++pos;
        }
      }

      if (literalStart < n) {
        tokens.push({ literal: true, length: n - literalStart });
        for (let i = literalStart; i < n; ++i) literalBytes.push(data[i]);
      }

      return { tokens, literalBytes };
    }

    // Self-contained literal entropy stage (stands in for upstream rzip's external
    // bzip2 pass): an order-0 canonical Huffman code is built from the observed literal
    // byte frequencies and transmitted as a 256-entry length table, unless the run is
    // too short to be worth the table overhead or a pathological frequency distribution
    // would need codes longer than MAX_CODE_LENGTH, in which case literals are stored raw.
    _writeLiteralStream(out, literalBytes) {
      const algorithm = this.algorithm;
      const count = literalBytes.length;
      VarInt.write(out, count);

      if (count === 0) {
        out.push(0);
        return;
      }

      const freqs = new Array(256).fill(0);
      for (const b of literalBytes) ++freqs[b];

      const lengths = buildHuffmanLengths(freqs);
      let maxLen = 0;
      for (const len of lengths) if (len > maxLen) maxLen = len;

      const useHuffman = count >= algorithm.LITERAL_HUFFMAN_THRESHOLD &&
        maxLen > 0 && maxLen <= algorithm.MAX_CODE_LENGTH;

      if (!useHuffman) {
        out.push(0);
        for (const b of literalBytes) out.push(b);
        return;
      }

      out.push(1);
      for (let s = 0; s < 256; ++s) out.push(lengths[s]);

      const tree = HuffmanTree.buildFromLengths(lengths);
      const writer = new BitWriter();
      for (const b of literalBytes) {
        const { code, length } = tree.encode(b);
        writer.writeBits(code, length);
      }
      for (const byte of writer.flush()) out.push(byte);
    }

    // ===== DECOMPRESSION =====

    _decompress(data) {
      if (data.length === 0) return [];

      const pos = { p: 0 };
      VarInt.read(data, pos); // total original length (informational, reconstructed length is authoritative)
      const tokenCount = VarInt.read(data, pos);

      const tokens = [];
      for (let i = 0; i < tokenCount; ++i) {
        const type = data[pos.p++];
        if (type === 0) {
          const length = VarInt.read(data, pos);
          tokens.push({ literal: true, length });
        } else {
          const distance = VarInt.read(data, pos);
          const length = VarInt.read(data, pos);
          tokens.push({ literal: false, distance, length });
        }
      }

      const literalBytes = this._readLiteralStream(data, pos);

      const output = [];
      let literalPos = 0;
      for (const t of tokens) {
        if (t.literal) {
          for (let i = 0; i < t.length; ++i) output.push(literalBytes[literalPos++]);
        } else {
          for (let i = 0; i < t.length; ++i) {
            output.push(output[output.length - t.distance]);
          }
        }
      }

      return output;
    }

    _readLiteralStream(data, pos) {
      const count = VarInt.read(data, pos);
      const mode = data[pos.p++];
      const literalBytes = [];

      if (count === 0) return literalBytes;

      if (mode === 0) {
        for (let i = 0; i < count; ++i) literalBytes.push(data[pos.p++]);
        return literalBytes;
      }

      const lengths = new Array(256);
      for (let s = 0; s < 256; ++s) lengths[s] = data[pos.p++];

      const tree = HuffmanTree.buildFromLengths(lengths);
      const reader = new BitReader(data.slice(pos.p));
      for (let i = 0; i < count; ++i) literalBytes.push(tree.decode(reader));
      pos.p += reader.bytePos;

      return literalBytes;
    }
  }

  // ===== REGISTRATION =====

  const algorithmInstance = new RZIPAlgorithm();
  if (!AlgorithmFramework.Find(algorithmInstance.name)) {
    RegisterAlgorithm(algorithmInstance);
  }

  // ===== EXPORTS =====

  return { RZIPAlgorithm, RZIPInstance };
}));
