/*
 * RZIP Long-Range Redundancy Elimination Compression Algorithm
 * Compatible with AlgorithmFramework
 * (c)2006-2025 Hawkynt
 *
 * RZIP was devised by Andrew Tridgell, growing out of the block-matching ideas behind
 * rsync and first described in his PhD thesis "Efficient Algorithms for Sorting and
 * Synchronization" (Australian National University, 1999). The original rzip tool
 * (https://rzip.samba.org/) builds a hash-indexed dictionary across the WHOLE input
 * file (historically up to 900 MB) rather than a small sliding window, so it can find
 * and encode duplicated regions at arbitrary distances - something ordinary LZ77/DEFLATE
 * cannot do because their history buffer is capped at 32-64 KB. Stage 1 emits a compact
 * stream of literal runs and (offset,length) copy tokens; stage 2 pipes that stream
 * through an external general-purpose compressor (bzip2) for entropy coding.
 *
 * Note: this implementation replicates rzip's stage-1 design (a rolling hash built over
 * the entire processed input, so matches can be found and copied from anywhere already
 * seen, not just a recent window) and, because every algorithm file in this project must
 * be a self-contained standalone module with no external tooling or other files to import,
 * adds its own lightweight order-0 canonical Huffman entropy stage for the literal bytes
 * in place of the external bzip2 stage upstream rzip relies on. The stream therefore
 * carries the "RZIP" signature and version of the upstream container but is NOT
 * interchangeable with files written by the upstream tool.
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD
    define(['../../AlgorithmFramework', '../../OpCodes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // Node.js/CommonJS
    module.exports = factory(
      require('../../AlgorithmFramework'),
      require('../../OpCodes')
    );
  } else {
    // Browser/Worker global
    factory(root.AlgorithmFramework, root.OpCodes);
  }
}((function() {
  if (typeof globalThis !== 'undefined') return globalThis;
  if (typeof window !== 'undefined') return window;
  if (typeof global !== 'undefined') return global;
  if (typeof self !== 'undefined') return self;
  throw new Error('Unable to locate global object');
})(), function (AlgorithmFramework, OpCodes) {
  'use strict';

  if (!AlgorithmFramework) {
    throw new Error('AlgorithmFramework dependency is required');
  }

  if (!OpCodes) {
    throw new Error('OpCodes dependency is required');
  }

  // Extract framework components
  const { RegisterAlgorithm, CategoryType, ComplexityType, CountryCode,
          CompressionAlgorithm, IAlgorithmInstance, TestCase, LinkItem } = AlgorithmFramework;

  // ===== DETERMINISTIC TEST-VECTOR HELPERS =====
  // Pure arithmetic (multiply/add/mod) linear congruential generator - no bitwise
  // operators are used, since generated bytes only need to be reproducible, not
  // cryptographically random.

  /**
   * @param {int32} count - Number of bytes
   * @param {float64} seed - Generator seed
   * @returns {uint8[]} Reproducible pseudo-random bytes
   */
  function genPseudoRandomBytes(count, seed) {
    /** @type {uint8[]} */
    const bytes = [];
    /** @type {float64} */
    let state = seed % 4294967296;
    for (let i = 0; i < count; ++i) {
      state = (state * 1664525 + 1013904223) % 4294967296;
      /** @type {float64} */
      const byte = Math.floor(state / 16777216) % 256;
      bytes.push(byte);
    }
    return bytes;
  }

  /**
   * @param {int32} size - Number of entries
   * @returns {int32[]} Plain array of zeros
   */
  function zeroArray(size) {
    /** @type {int32[]} */
    const arr = new Array(size);
    for (let i = 0; i < size; ++i) {
      arr[i] = 0;
    }
    return arr;
  }

  // ===== CONTAINER =====
  // "RZIP" + major + minor + original size (4 bytes, big-endian).

  /** @type {uint8[]} */
  const MAGIC = [0x52, 0x5A, 0x49, 0x50];
  const VERSION_MAJOR = 2;
  const VERSION_MINOR = 1;
  const HEADER_SIZE = 10;

  // ===== VARIABLE-LENGTH INTEGER ENCODING (LEB128-style, arithmetic only) =====

  /**
   * Read position shared by the stream parsers.
   */
  class ReadCursor {
    /**
     * @param {int32} p - Initial byte position
     */
    constructor(p) {
      /** @type {int32} */
      this.p = p;
    }
  }

  /**
   * @param {uint8[]} out - Output stream, appended to
   * @param {float64} value - Non-negative integer
   */
  function varIntWrite(out, value) {
    /** @type {float64} */
    let v = value;
    for (;;) {
      /** @type {float64} */
      const byte = v % 128;
      v = Math.floor(v / 128);
      if (v > 0) {
        out.push(byte + 128);
      } else {
        out.push(byte);
        break;
      }
    }
  }

  // A read past the end yields an undefined byte and never terminates, as before.
  /**
   * @param {uint8[]} bytes - Input stream
   * @param {ReadCursor} pos - Read position, advanced
   * @returns {float64} Decoded integer
   */
  function varIntRead(bytes, pos) {
    /** @type {float64} */
    let result = 0;
    /** @type {float64} */
    let mult = 1;
    for (;;) {
      /** @type {float64} */
      const byte = bytes[pos.p++];
      result += (byte % 128) * mult;
      if (byte < 128) {
        break;
      }
      mult *= 128;
    }
    return result;
  }

  // ===== BIT-LEVEL I/O FOR THE LITERAL ENTROPY STAGE =====
  // A private, self-consistent bit packing (bits are appended LSB-first within each byte);
  // encoder and decoder only need to agree with each other, not with any external format.

  class BitWriter {
    constructor() {
      /** @type {uint8[]} */
      this.bytes = [];
      /** @type {uint32} */
      this.buffer = 0;
      /** @type {int32} */
      this.bitCount = 0;
    }

    /**
     * @param {uint32} bit - Bit to append
     */
    writeBit(bit) {
      this.buffer = OpCodes.Or32(this.buffer, OpCodes.Shl32(bit, this.bitCount));
      ++this.bitCount;
      if (this.bitCount === 8) {
        this.bytes.push(OpCodes.And32(this.buffer, 0xFF));
        this.buffer = 0;
        this.bitCount = 0;
      }
    }

    // Writes 'length' bits of 'value', most-significant bit first.
    /**
     * @param {float64} value - Code bits
     * @param {int32} length - Bit count
     */
    writeBits(value, length) {
      for (let i = length - 1; i >= 0; --i) {
        /** @type {uint32} */
        const bit = OpCodes.And32(OpCodes.Shr32(value, i), 1);
        this.writeBit(bit);
      }
    }

    /**
     * @returns {uint8[]} All bytes written so far
     */
    flush() {
      if (this.bitCount > 0) {
        this.bytes.push(OpCodes.And32(this.buffer, 0xFF));
        this.buffer = 0;
        this.bitCount = 0;
      }
      return this.bytes;
    }
  }

  class BitReader {
    /**
     * @param {uint8[]} bytes - Input
     */
    constructor(bytes) {
      /** @type {uint8[]} */
      this.bytes = bytes;
      /** @type {int32} */
      this.bytePos = 0;
      /** @type {uint32} */
      this.buffer = 0;
      /** @type {int32} */
      this.bitPos = 8;
    }

    /**
     * @returns {uint32} Next bit
     */
    readBit() {
      if (this.bitPos === 8) {
        if (this.bytePos >= this.bytes.length) {
          throw new Error('Unexpected end of literal bit stream');
        }
        this.buffer = this.bytes[this.bytePos++];
        this.bitPos = 0;
      }
      /** @type {uint32} */
      const bit = OpCodes.And32(OpCodes.Shr32(this.buffer, this.bitPos), 1);
      ++this.bitPos;
      return bit;
    }
  }

  // ===== CANONICAL HUFFMAN CODING (order-0, 256-symbol byte alphabet) =====

  // The decoding tree is kept as node rows (symbol, zero child, one child; -1
  // for none). Codes are inserted in symbol order exactly as the former object
  // tree did: a leaf replaces whatever hung at its slot, a longer code walks
  // through (and extends) whatever node it meets, so even an inconsistent
  // length table decodes as before.
  class HuffmanTree {
    constructor() {
      /** @type {boolean} */
      this.hasRoot = false;
      /** @type {int32[]} */
      this.nodeSymbol = [];
      /** @type {int32[]} */
      this.nodeZero = [];
      /** @type {int32[]} */
      this.nodeOne = [];
      /** @type {boolean} */
      this.hasCodes = false;
      /** @type {boolean[]} */
      this.codePresent = [];
      /** @type {float64[]} */
      this.codeValues = [];
      /** @type {int32[]} */
      this.codeLengths = [];
    }

    /**
     * @param {int32} symbol - Leaf symbol, -1 for an inner node
     * @returns {int32} New node index
     */
    _newNode(symbol) {
      /** @type {int32} */
      const index = this.nodeSymbol.length;
      this.nodeSymbol.push(symbol);
      this.nodeZero.push(-1);
      this.nodeOne.push(-1);
      return index;
    }

    /**
     * @param {int32} node - Parent node
     * @param {uint32} bit - Branch
     * @returns {int32} Child node, -1 when absent
     */
    _child(node, bit) {
      return bit ? this.nodeOne[node] : this.nodeZero[node];
    }

    /**
     * @param {int32} node - Parent node
     * @param {uint32} bit - Branch
     * @param {int32} child - Child node
     */
    _setChild(node, bit, child) {
      if (bit) {
        this.nodeOne[node] = child;
      } else {
        this.nodeZero[node] = child;
      }
    }

    // A length byte read past the end of the stream is undefined: it gets a
    // code entry but no code bits and no tree path, as before.
    /**
     * @param {int32[]} lengths - Code length per symbol
     * @returns {HuffmanTree} Canonical code and decoding tree
     */
    static buildFromLengths(lengths) {
      /** @type {HuffmanTree} */
      const tree = new HuffmanTree();
      /** @type {int32} */
      let maxLen = 0;
      for (let s = 0; s < lengths.length; ++s) {
        if (lengths[s] > maxLen) {
          maxLen = lengths[s];
        }
      }
      if (maxLen === 0) {
        return tree;
      }

      /** @type {int32[]} */
      const blCount = zeroArray(maxLen + 1);
      for (let s = 0; s < lengths.length; ++s) {
        if (lengths[s] > 0) {
          ++blCount[lengths[s]];
        }
      }

      /** @type {float64[]} */
      const nextCode = [];
      for (let bits = 0; bits <= maxLen; ++bits) {
        nextCode.push(0);
      }
      /** @type {float64} */
      let code = 0;
      blCount[0] = 0;
      for (let bits = 1; bits <= maxLen; ++bits) {
        /** @type {float64} */
        const count = blCount[bits - 1];
        code = OpCodes.ToUint32((code + count) * 2);
        nextCode[bits] = code;
      }

      for (let symbol = 0; symbol < lengths.length; ++symbol) {
        /** @type {int32} */
        const len = lengths[symbol];
        tree.codePresent.push(len !== 0);
        tree.codeValues.push(0);
        tree.codeLengths.push(0);
        if (len > 0) {
          tree.codeValues[symbol] = nextCode[len];
          tree.codeLengths[symbol] = len;
          ++nextCode[len];
        }
      }

      tree.hasRoot = true;
      tree._newNode(-1);
      for (let symbol = 0; symbol < lengths.length; ++symbol) {
        /** @type {int32} */
        const length = tree.codeLengths[symbol];
        if (length === 0) {
          continue;
        }

        /** @type {int32} */
        let node = 0;
        /** @type {float64} */
        const symCode = tree.codeValues[symbol];

        for (let i = length - 1; i >= 0; --i) {
          /** @type {uint32} */
          const bit = OpCodes.And32(OpCodes.Shr32(symCode, i), 1);

          if (i === 0) {
            /** @type {int32} */
            const leaf = tree._newNode(symbol);
            tree._setChild(node, bit, leaf);
          } else {
            /** @type {int32} */
            let next = tree._child(node, bit);
            if (next < 0) {
              next = tree._newNode(-1);
              tree._setChild(node, bit, next);
            }
            node = next;
          }
        }
      }

      tree.hasCodes = true;
      return tree;
    }

    /**
     * @param {BitReader} bitReader - Input bits
     * @returns {int32} Decoded symbol
     */
    decode(bitReader) {
      if (!this.hasRoot) {
        throw new Error('Invalid Huffman tree');
      }
      /** @type {int32} */
      let node = 0;

      while (this.nodeSymbol[node] < 0) {
        /** @type {uint32} */
        const bit = bitReader.readBit();
        node = this._child(node, bit);
        if (node < 0) {
          throw new Error('Invalid Huffman code');
        }
      }

      return this.nodeSymbol[node];
    }
  }

  /**
   * @param {int32} node - Subtree root
   * @param {int32} depth - Depth of that root
   * @param {int32[]} lengths - Code length per symbol, filled in
   * @param {int32[]} nodeSymbol - Leaf symbol per node, -1 for inner nodes
   * @param {int32[]} nodeLeft - Left child per node
   * @param {int32[]} nodeRight - Right child per node
   */
  function assignDepths(node, depth, lengths, nodeSymbol, nodeLeft, nodeRight) {
    if (nodeSymbol[node] >= 0) {
      lengths[nodeSymbol[node]] = depth;
      return;
    }
    assignDepths(nodeLeft[node], depth + 1, lengths, nodeSymbol, nodeLeft, nodeRight);
    assignDepths(nodeRight[node], depth + 1, lengths, nodeSymbol, nodeLeft, nodeRight);
  }

  // Builds a set of prefix-free code lengths (one per byte value 0-255) from observed
  // frequencies using a classic bottom-up Huffman merge. Symbols that never occur keep
  // length 0 (no code). A single distinct symbol is forced to length 1.
  // Each round stably orders the working list by frequency (equal frequencies
  // keep their list order), takes the first two nodes and appends their merge.
  /**
   * @param {int32[]} freqs - Frequency per byte value
   * @returns {int32[]} Code length per byte value
   */
  function buildHuffmanLengths(freqs) {
    /** @type {int32[]} */
    const symbols = [];
    for (let s = 0; s < 256; ++s) {
      if (freqs[s] > 0) {
        symbols.push(s);
      }
    }

    /** @type {int32[]} */
    const lengths = zeroArray(256);
    if (symbols.length === 0) {
      return lengths;
    }
    if (symbols.length === 1) {
      lengths[symbols[0]] = 1;
      return lengths;
    }

    /** @type {float64[]} */
    const nodeFreq = [];
    /** @type {int32[]} */
    const nodeSymbol = [];
    /** @type {int32[]} */
    const nodeLeft = [];
    /** @type {int32[]} */
    const nodeRight = [];
    /** @type {int32[]} */
    let heap = [];
    for (let k = 0; k < symbols.length; ++k) {
      nodeFreq.push(freqs[symbols[k]]);
      nodeSymbol.push(symbols[k]);
      nodeLeft.push(-1);
      nodeRight.push(-1);
      heap.push(k);
    }

    while (heap.length > 1) {
      for (let i = 1; i < heap.length; ++i) {
        /** @type {int32} */
        const item = heap[i];
        /** @type {int32} */
        let j = i - 1;
        while (j >= 0 && nodeFreq[heap[j]] > nodeFreq[item]) {
          heap[j + 1] = heap[j];
          --j;
        }
        heap[j + 1] = item;
      }
      /** @type {int32} */
      const a = heap[0];
      /** @type {int32} */
      const b = heap[1];
      heap = heap.slice(2);
      /** @type {int32} */
      const merged = nodeFreq.length;
      nodeFreq.push(nodeFreq[a] + nodeFreq[b]);
      nodeSymbol.push(-1);
      nodeLeft.push(a);
      nodeRight.push(b);
      heap.push(merged);
    }

    assignDepths(heap[0], 0, lengths, nodeSymbol, nodeLeft, nodeRight);

    return lengths;
  }

  // ===== LONG-RANGE MATCH INDEX =====

  // Rolling-hash buckets keyed by the exact 32-bit hash (open addressing).
  // Only lookups by key are made, so the slot layout never affects output.
  class HashBuckets {
    /**
     * @param {int32} maxKeys - Upper bound on distinct keys inserted
     */
    constructor(maxKeys) {
      /** @type {int32} */
      let bits = 1;
      while (OpCodes.Shl32(1, bits) < maxKeys * 2) {
        ++bits;
      }
      /** @type {int32} */
      this.bits = bits;
      /** @type {int32} */
      this.mask = OpCodes.Shl32(1, bits) - 1;
      /** @type {uint32[]} */
      this.keys = new Uint32Array(this.mask + 1);
      /** @type {uint8[]} */
      this.used = new Uint8Array(this.mask + 1);
      /** @type {int32[][]} */
      this.buckets = new Array(this.mask + 1);
    }

    /**
     * @param {uint32} h - Key
     * @returns {int32} Slot holding the key, or the free slot where it belongs
     */
    _probe(h) {
      /** @type {int32} */
      let slot = OpCodes.Shr32(OpCodes.Mul32(h, 0x9E3779B1), 32 - this.bits);
      while (this.used[slot] !== 0 && this.keys[slot] !== h) {
        slot = OpCodes.And32(slot + 1, this.mask);
      }
      return slot;
    }

    /**
     * @param {uint32} h - Key
     * @returns {int32} Slot of the key's bucket, -1 when absent
     */
    find(h) {
      /** @type {int32} */
      const slot = this._probe(h);
      return this.used[slot] !== 0 ? slot : -1;
    }

    /**
     * Appends a position to the key's bucket, dropping the oldest beyond cap.
     * @param {uint32} h - Key
     * @param {int32} pos - Position
     * @param {int32} cap - Bucket capacity
     */
    insert(h, pos, cap) {
      /** @type {int32} */
      const slot = this._probe(h);
      if (this.used[slot] === 0) {
        this.used[slot] = 1;
        this.keys[slot] = h;
        /** @type {int32[]} */
        const fresh = [];
        this.buckets[slot] = fresh;
      }
      /** @type {int32[]} */
      const bucket = this.buckets[slot];
      bucket.push(pos);
      if (bucket.length > cap) {
        bucket.shift();
      }
    }
  }

  /**
   * @param {uint8[]} data - Input
   * @param {int32} pos - Window start
   * @param {int32} windowSize - Window length
   * @param {uint32} base - Polynomial multiplier
   * @returns {uint32} Polynomial hash of the window, mod 2^32
   */
  function rollingHashAt(data, pos, windowSize, base) {
    /** @type {uint32} */
    let h = 0;
    for (let i = 0; i < windowSize; ++i) {
      h = OpCodes.Add32(OpCodes.Mul32(h, base), data[pos + i]);
    }
    return h;
  }

  /**
   * Token list: a literal run of length bytes, or a match copying length bytes
   * from distance back.
   */
  class ParsedTokens {
    constructor() {
      /** @type {boolean[]} */
      this.literal = [];
      /** @type {float64[]} */
      this.distance = [];
      /** @type {float64[]} */
      this.length = [];
      /** @type {uint8[]} */
      this.literalBytes = [];
    }

    /**
     * @param {boolean} isLiteral - True for a literal run
     * @param {float64} distance - Match distance (0 for literals)
     * @param {float64} length - Run or match length
     */
    add(isLiteral, distance, length) {
      this.literal.push(isLiteral);
      this.distance.push(distance);
      this.length.push(length);
    }
  }

  // ===== RZIP ALGORITHM =====

  class RZIPAlgorithm extends CompressionAlgorithm {
    constructor() {
      super();

      // Required metadata
      this.name = "RZIP";
      this.description = "Long-range redundancy-elimination compressor that indexes the entire input with a rolling hash so LZ77-style (offset,length) matches can be found at arbitrary distances, far beyond a classic 32K/64K sliding window. Literal bytes are entropy-coded with a self-contained order-0 canonical Huffman stage.";
      this.inventor = "Andrew Tridgell";
      this.year = 1998;
      this.category = CategoryType.COMPRESSION;
      this.subCategory = "Long-Range";
      this.securityStatus = null;
      this.complexity = ComplexityType.ADVANCED;
      this.country = CountryCode.AU;

      // Matcher configuration (rolling hash window / minimum match length)
      /** @type {int32} */
      this.MIN_MATCH = 16;             // Rolling hash window size in bytes
      /** @type {int32} */
      this.HASH_BUCKET_CAP = 64;       // Maximum stored candidate positions per hash bucket
      /** @type {int32} */
      this.CANDIDATE_SEARCH_LIMIT = 32;// Maximum candidates examined per position
      /** @type {uint32} */
      this.ROLLING_HASH_BASE = 257;    // Polynomial rolling hash multiplier

      // Literal entropy stage configuration
      /** @type {int32} */
      this.MAX_CODE_LENGTH = 24;           // Safety cap; falls back to raw storage if exceeded

      // Documentation
      this.documentation = [
        new LinkItem("rzip - a large-file compression program (project home)", "https://rzip.samba.org/"),
        new LinkItem("Andrew Tridgell, \"Efficient Algorithms for Sorting and Synchronization\" (PhD thesis, ANU, 1999)", "https://www.samba.org/~tridge/phd_thesis.pdf"),
        new LinkItem("rzip(1) manual page", "https://manpages.ubuntu.com/manpages/focal/man1/rzip.1.html")
      ];

      this.references = [
        new LinkItem("Rzip - Wikipedia", "https://en.wikipedia.org/wiki/Rzip"),
        new LinkItem("lrzip - Long Range ZIP (rzip descendant)", "https://github.com/ckolivas/lrzip")
      ];

      // Test vectors - round-trip compression tests
      const longMarker = OpCodes.AnsiToBytes("RZIP-LONG-RANGE-MARKER-BLOCK-0123456789ABCDEF");
      const longFiller = genPseudoRandomBytes(40000, 987654321);
      const longRangeVector = longMarker.concat(longFiller).concat(longMarker);

      /** @type {uint8[]} */
      const alternating = [];
      for (let i = 0; i < 600; ++i) {
        alternating.push(i % 2 === 0 ? 0x58 : 0x59);
      }

      this.tests = [
        new TestCase(
          [],
          [], // Empty expected for round-trip test
          "RZIP round-trip - empty input",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          [0x41],
          [], // Empty expected for round-trip test
          "RZIP round-trip - single byte",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          new Array(2000).fill(0x42),
          [], // Empty expected for round-trip test
          "RZIP round-trip - long repetitive run (2000 bytes)",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          alternating,
          [], // Empty expected for round-trip test
          "RZIP round-trip - alternating byte pattern",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          genPseudoRandomBytes(500, 12345),
          [], // Empty expected for round-trip test
          "RZIP round-trip - pseudo-random binary sample",
          "https://rzip.samba.org/"
        ),
        new TestCase(
          longRangeVector,
          [], // Empty expected for round-trip test
          "RZIP round-trip - identical blocks separated by 40KB of filler (long-range match, exceeds a 32K/64K sliding window)",
          "https://www.samba.org/~tridge/phd_thesis.pdf"
        ),
        new TestCase(
          OpCodes.AnsiToBytes("RZIP finds long distance redundancy in the whole file using a rolling hash dictionary, then relies on a second stage compressor for entropy coding of the literal data."),
          [], // Empty expected for round-trip test
          "RZIP round-trip - spec-flavoured description text",
          "https://rzip.samba.org/"
        )
      ];
    }

    CreateInstance(isInverse = false) {
      return new RZIPInstance(this, isInverse);
    }
  }

  /**
   * RZIP compression instance implementing the Feed/Result pattern.
   * @class
   * @extends {IAlgorithmInstance}
   */

  class RZIPInstance extends IAlgorithmInstance {
    /**
     * @param {RZIPAlgorithm} algorithm - Owning algorithm
     * @param {boolean} isInverse - True for decompression
     */
    constructor(algorithm, isInverse = false) {
      super(algorithm);
      /** @type {boolean} */
      this.isInverse = isInverse;
      /** @type {uint8[]} */
      this.inputBuffer = [];
    }

    /**
     * @param {uint8[]} data - Bytes to append
     */
    Feed(data) {
      if (!data || data.length === 0) {
        return;
      }
      // Long-range matching implies large inputs; avoid a spread-argument call-stack
      // overflow that a naive push(...data) would hit on big arrays.
      for (let i = 0; i < data.length; ++i) {
        this.inputBuffer.push(data[i]);
      }
    }

    /**
     * @returns {uint8[]} Compressed or decompressed bytes
     */
    Result() {
      /** @type {uint8[]} */
      let result = [];
      if (this.isInverse) {
        result = this._decompress(this.inputBuffer);
      } else {
        result = this._compress(this.inputBuffer);
      }

      this.inputBuffer = [];
      return result;
    }

    // ===== COMPRESSION =====

    /**
     * @param {uint8[]} data - Input
     * @returns {uint8[]} RZIP stream
     */
    _compress(data) {
      /** @type {ParsedTokens} */
      const parsed = this._findTokens(data);
      /** @type {uint8[]} */
      const out = [];

      // Header: "RZIP", major, minor, then the original size big-endian. An .rz stream
      // is a file format, so it names itself rather than relying on the file extension.
      for (let i = 0; i < MAGIC.length; ++i) {
        out.push(MAGIC[i]);
      }
      out.push(VERSION_MAJOR);
      out.push(VERSION_MINOR);
      out.push(OpCodes.And32(OpCodes.Shr32(data.length, 24), 0xFF));
      out.push(OpCodes.And32(OpCodes.Shr32(data.length, 16), 0xFF));
      out.push(OpCodes.And32(OpCodes.Shr32(data.length, 8), 0xFF));
      out.push(OpCodes.And32(data.length, 0xFF));

      varIntWrite(out, parsed.literal.length);

      for (let t = 0; t < parsed.literal.length; ++t) {
        if (parsed.literal[t]) {
          out.push(0);
          varIntWrite(out, parsed.length[t]);
        } else {
          out.push(1);
          varIntWrite(out, parsed.distance[t]);
          varIntWrite(out, parsed.length[t]);
        }
      }

      this._writeLiteralStream(out, parsed.literalBytes);

      return out;
    }

    // Long-range LZ77-style matcher: a polynomial rolling hash over MIN_MATCH-byte
    // windows is indexed for every scanned position across the WHOLE input processed
    // so far (never discarded due to distance), which is what lets matches be found
    // arbitrarily far back rather than only within a small recent window.
    /**
     * @param {uint8[]} data - Input
     * @returns {ParsedTokens} Token list and the literal bytes it refers to
     */
    _findTokens(data) {
      /** @type {RZIPAlgorithm} */
      const algorithm = this.algorithm;
      /** @type {int32} */
      const MIN_MATCH = algorithm.MIN_MATCH;
      /** @type {int32} */
      const n = data.length;
      /** @type {ParsedTokens} */
      const parsed = new ParsedTokens();

      if (n === 0) {
        return parsed;
      }

      if (n < MIN_MATCH) {
        parsed.add(true, 0, n);
        for (let i = 0; i < n; ++i) {
          parsed.literalBytes.push(data[i]);
        }
        return parsed;
      }

      /** @type {uint32} */
      const base = algorithm.ROLLING_HASH_BASE;
      /** @type {uint32} */
      let basePow = 1;
      for (let i = 0; i < MIN_MATCH - 1; ++i) {
        basePow = OpCodes.Mul32(basePow, base);
      }

      /** @type {HashBuckets} */
      const hashTable = new HashBuckets(n);

      /** @type {int32} */
      const lastPos = n - MIN_MATCH;
      /** @type {int32} */
      let pos = 0;
      /** @type {int32} */
      let literalStart = 0;
      /** @type {uint32} */
      let h = rollingHashAt(data, 0, MIN_MATCH, base);
      /** @type {boolean} */
      let hValid = true;

      while (pos <= lastPos) {
        if (!hValid) {
          h = rollingHashAt(data, pos, MIN_MATCH, base);
          hValid = true;
        }

        /** @type {int32} */
        let bestLen = 0;
        /** @type {int32} */
        let bestPos = -1;
        /** @type {int32} */
        const slot = hashTable.find(h);
        if (slot >= 0) {
          /** @type {int32[]} */
          const bucket = hashTable.buckets[slot];
          /** @type {int32} */
          const start = Math.max(0, bucket.length - algorithm.CANDIDATE_SEARCH_LIMIT);
          for (let bi = bucket.length - 1; bi >= start; --bi) {
            /** @type {int32} */
            const cand = bucket[bi];
            /** @type {int32} */
            const maxLen = n - pos;
            /** @type {int32} */
            let len = 0;
            while (len < maxLen && data[cand + len] === data[pos + len]) {
              ++len;
            }
            if (len >= MIN_MATCH && len > bestLen) {
              bestLen = len;
              bestPos = cand;
            }
          }
        }

        hashTable.insert(h, pos, algorithm.HASH_BUCKET_CAP);

        if (bestLen >= MIN_MATCH) {
          if (pos > literalStart) {
            parsed.add(true, 0, pos - literalStart);
            for (let i = literalStart; i < pos; ++i) {
              parsed.literalBytes.push(data[i]);
            }
          }
          parsed.add(false, pos - bestPos, bestLen);
          pos += bestLen;
          literalStart = pos;
          hValid = false;
        } else {
          if (pos < lastPos) {
            /** @type {uint8} */
            const outByte = data[pos];
            /** @type {uint8} */
            const inByte = data[pos + MIN_MATCH];
            h = OpCodes.Sub32(h, OpCodes.Mul32(outByte, basePow));
            h = OpCodes.Add32(OpCodes.Mul32(h, base), inByte);
          }
          ++pos;
        }
      }

      if (literalStart < n) {
        parsed.add(true, 0, n - literalStart);
        for (let i = literalStart; i < n; ++i) {
          parsed.literalBytes.push(data[i]);
        }
      }

      return parsed;
    }

    // Self-contained literal entropy stage (stands in for upstream rzip's external
    // bzip2 pass): an order-0 canonical Huffman code is built from the observed literal
    // byte frequencies and transmitted as a 256-entry length table, unless the run is
    // too short to be worth the table overhead or a pathological frequency distribution
    // would need codes longer than MAX_CODE_LENGTH, in which case literals are stored raw.
    /**
     * @param {uint8[]} out - Output stream, appended to
     * @param {uint8[]} literalBytes - Literal bytes in token order
     */
    _writeLiteralStream(out, literalBytes) {
      /** @type {RZIPAlgorithm} */
      const algorithm = this.algorithm;
      /** @type {int32} */
      const count = literalBytes.length;
      varIntWrite(out, count);

      if (count === 0) {
        out.push(0);
        return;
      }

      /** @type {int32[]} */
      const freqs = zeroArray(256);
      for (let i = 0; i < count; ++i) {
        ++freqs[literalBytes[i]];
      }

      /** @type {int32[]} */
      const lengths = buildHuffmanLengths(freqs);
      /** @type {int32} */
      let maxLen = 0;
      /** @type {float64} */
      let codedBits = 0;
      for (let s = 0; s < 256; ++s) {
        if (lengths[s] > maxLen) {
          maxLen = lengths[s];
        }
        /** @type {float64} */
        const symbolFreq = freqs[s];
        codedBits += symbolFreq * lengths[s];
      }

      // The length table costs a fixed 256 bytes, so coding only pays once the codes
      // save more than that. Without this check a short literal run inflates: 256
      // literals of distinct bytes cost 8 bits each and gain nothing for the table.
      /** @type {float64} */
      const codedCost = 256 + Math.ceil(codedBits / 8);
      /** @type {boolean} */
      const useHuffman = maxLen > 0 && maxLen <= algorithm.MAX_CODE_LENGTH && codedCost < count;

      if (!useHuffman) {
        out.push(0);
        for (let i = 0; i < count; ++i) {
          out.push(literalBytes[i]);
        }
        return;
      }

      out.push(1);
      for (let s = 0; s < 256; ++s) {
        out.push(lengths[s]);
      }

      /** @type {HuffmanTree} */
      const tree = HuffmanTree.buildFromLengths(lengths);
      /** @type {BitWriter} */
      const writer = new BitWriter();
      for (let i = 0; i < count; ++i) {
        /** @type {uint8} */
        const b = literalBytes[i];
        if (!tree.hasCodes || !tree.codePresent[b]) {
          throw new Error('No Huffman code for symbol ' + b);
        }
        writer.writeBits(tree.codeValues[b], tree.codeLengths[b]);
      }
      /** @type {uint8[]} */
      const packed = writer.flush();
      for (let i = 0; i < packed.length; ++i) {
        out.push(packed[i]);
      }
    }

    // ===== DECOMPRESSION =====

    /**
     * @param {uint8[]} data - RZIP stream
     * @returns {uint8[]} Decompressed bytes
     */
    _decompress(data) {
      if (data.length < HEADER_SIZE) {
        throw new Error('Truncated RZIP header');
      }

      for (let i = 0; i < MAGIC.length; ++i) {
        if (data[i] !== MAGIC[i]) {
          throw new Error('Invalid RZIP magic bytes');
        }
      }

      if (data[4] !== VERSION_MAJOR) {
        throw new Error('Unsupported RZIP version: ' + data[4] + '.' + data[5]);
      }

      /** @type {ReadCursor} */
      const pos = new ReadCursor(HEADER_SIZE);
      /** @type {float64} */
      const tokenCount = varIntRead(data, pos);

      /** @type {ParsedTokens} */
      const parsed = new ParsedTokens();
      for (let i = 0; i < tokenCount; ++i) {
        /** @type {uint8} */
        const type = data[pos.p++];
        if (type === 0) {
          /** @type {float64} */
          const length = varIntRead(data, pos);
          parsed.add(true, 0, length);
        } else {
          /** @type {float64} */
          const distance = varIntRead(data, pos);
          /** @type {float64} */
          const length = varIntRead(data, pos);
          parsed.add(false, distance, length);
        }
      }

      /** @type {uint8[]} */
      const literalBytes = this._readLiteralStream(data, pos);

      /** @type {uint8[]} */
      const output = [];
      /** @type {int32} */
      let literalPos = 0;
      for (let t = 0; t < parsed.literal.length; ++t) {
        /** @type {float64} */
        const length = parsed.length[t];
        if (parsed.literal[t]) {
          for (let i = 0; i < length; ++i) {
            output.push(literalBytes[literalPos++]);
          }
        } else {
          /** @type {float64} */
          const distance = parsed.distance[t];
          for (let i = 0; i < length; ++i) {
            output.push(output[output.length - distance]);
          }
        }
      }

      return output;
    }

    /**
     * @param {uint8[]} data - RZIP stream
     * @param {ReadCursor} pos - Read position, advanced past the literal stream
     * @returns {uint8[]} Literal bytes
     */
    _readLiteralStream(data, pos) {
      /** @type {float64} */
      const count = varIntRead(data, pos);
      /** @type {uint8} */
      const mode = data[pos.p++];
      /** @type {uint8[]} */
      const literalBytes = [];

      if (count === 0) {
        return literalBytes;
      }

      if (mode === 0) {
        for (let i = 0; i < count; ++i) {
          literalBytes.push(data[pos.p++]);
        }
        return literalBytes;
      }

      /** @type {int32[]} */
      const lengths = new Array(256);
      for (let s = 0; s < 256; ++s) {
        lengths[s] = data[pos.p++];
      }

      /** @type {HuffmanTree} */
      const tree = HuffmanTree.buildFromLengths(lengths);
      /** @type {BitReader} */
      const reader = new BitReader(data.slice(pos.p));
      for (let i = 0; i < count; ++i) {
        /** @type {uint8} */
        const symbol = tree.decode(reader);
        literalBytes.push(symbol);
      }
      pos.p += reader.bytePos;

      return literalBytes;
    }
  }

  // ===== REGISTRATION =====

  const algorithmInstance = new RZIPAlgorithm();
  if (!AlgorithmFramework.Find(algorithmInstance.name)) {
    RegisterAlgorithm(algorithmInstance);
  }

  // ===== EXPORTS =====

  return { RZIPAlgorithm, RZIPInstance };
}));
