;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/MACOSXDP2';

  skins['MACOSXDP2'] = {
    name: 'MacOS X DP2/Server',
    author: 'John T. Folden',
    email: 'jtfolden@erinet.com',
    url: 'http://www.winstep.net',
    editorNotes: 'This theme is based on MacOS X DP2 & Server',
    wbVersion: 0,
    basePath: BASE,

    personality: {
      usestran: 0,
      buttoncount: 5,
      textalignment: 1,
      textshift: 17,
      textshiftvert: 0,
      textrightclip: 28,
      textonbottom: '0',
      menubar: `${BASE}/MENU.BMP`,
      tilemenu: 1,
      tileleftmenu: 1,
      tilerightmenu: 1,
      menur: 206,
      menug: 207,
      menub: 255,
      activetextr: 0,
      activetextg: 0,
      activetextb: 0,
      inactivetextr: 120,
      inactivetextg: 120,
      inactivetextb: 120,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      top: `${BASE}/TOP.BMP`,
      left: `${BASE}/LEFT.BMP`,
      right: `${BASE}/RIGHT.BMP`,
      bottom: `${BASE}/BOTTOM.BMP`,
      topmask: `${BASE}/MASK_TOP.BMP`,
      leftmask: `${BASE}/MASK_LEFT.BMP`,
      rightmask: `${BASE}/MASK_RIGHT.BMP`,
      bottommask: `${BASE}/MASK_BOTTOM.BMP`,
      toptopheight: 17,
      topbotheight: 48,
      lefttopheight: 22,
      leftbotheight: 22,
      righttopheight: 22,
      rightbotheight: 22,
      bottomtopheight: 16,
      bottombotheight: 16,
      topstretch: 0,
      leftstretch: 0,
      rightstretch: 0,
      bottomstretch: 0,
      anirate: 0,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      textback: 'Macosx-jtf\\textback.bmp',
      textbackmask: 'Macosx-jtf\\mask_textback.bmp',
      textbackground: '1',
      txtbackleft: '4',
      txtbackright: '4',
      wallpaper: 'Macosx-jtf\\wallpaper.bmp',
      exec: 'Macosx-jtf\\Readme.txt',
      runstyle: '3',
      explorerbmp: `${BASE}/EXPLORER.BMP`,
      dialogbmp: `${BASE}/DIALOG.BMP`,
      mdibmp: `${BASE}/MDI.BMP`,
      menuborders: `${BASE}/MNUFRAME.BMP`,
      maxbordercutleft: '0',
      maxbordercuttop: '0',
      maxbordercutright: '0',
      maxbordercutbottom: '0',
      tripleimages: 1,
      soundenabled: 0,
      rollupsize: 22,
      rightclickaction: 2,
      doubleclickaction: '4',
    },

    buttons: {
      checkbutton: `${BASE}/CBOX.BMP`,
      radiobutton: `${BASE}/RADIO.BMP`,
      bitmap: `${BASE}/BUTTONS.BMP`,
      topheight: 8,
      bottomheight: 8,
      leftwidth: 8,
      rightwidth: 17,
      trans: 0,
      tile: '1',
    },

    titleButtons: [
      { image: `${BASE}/CLOSE.BMP`, align: 0, xcoord: 4, ycoord: 4, action: 0, visibility: 0 },
      { image: `${BASE}/MAX.BMP`, align: 1, xcoord: 33, ycoord: 4, action: 1, visibility: 20 },
      { image: `${BASE}/ROLL.BMP`, align: 1, xcoord: 18, ycoord: 4, action: 4 },
      { image: `${BASE}/TOPLEFT.BMP`, align: 0, xcoord: 0, ycoord: 0, action: -1, visibility: 5 },
      { image: `${BASE}/TOPRIGHT.BMP`, align: 1, xcoord: 7, ycoord: 0, action: -1, visibility: 5 },
    ],

    comboButton: {
      image: `${BASE}/COMBOBUT.BMP`,
      topheight: 4,
      bottomheight: 4,
      leftwidth: 4,
      rightwidth: 4,
    },

    taskButton: {
      image: `${BASE}/TASKBAR.BMP`,
      topheight: 3,
      bottomheight: 3,
      leftwidth: 3,
      rightwidth: 3,
    },

    tabControl: {
      image: `${BASE}/TABS.BMP`,
      topheight: 3,
      bottomheight: 3,
      leftwidth: 3,
      rightwidth: 3,
    },

    startButton: { image: `${BASE}/START.BMP` },

    colors: {
      background: [255, 255, 255],
      appWorkspace: [127, 127, 127],
      window: [255, 255, 255],
      windowText: [0, 0, 0],
      menu: [222, 222, 222],
      menuText: [0, 0, 0],
      activeTitle: [175, 175, 175],
      inactiveTitle: [222, 222, 222],
      titleText: [0, 0, 0],
      activeBorder: [222, 222, 222],
      inactiveBorder: [222, 222, 222],
      windowFrame: [0, 0, 0],
      scrollbar: [255, 255, 255],
      buttonFace: [222, 222, 222],
      buttonShadow: [127, 127, 127],
      buttonText: [0, 0, 0],
      grayText: [127, 127, 127],
      highlight: [206, 207, 255],
      highlightText: [0, 0, 0],
      inactiveTitleText: [120, 120, 120],
      buttonHighlight: [255, 255, 255],
      infoText: [0, 0, 0],
      infoWindow: [255, 255, 225],
      buttonLight: [222, 222, 222],
      buttonDarkShadow: [0, 0, 0],
      buttonAlternateFace: [222, 222, 222],
      hotTrackingColor: [0, 0, 255],
      gradientActiveTitle: [175, 175, 175],
      gradientInactiveTitle: [222, 222, 222],
    },

    customFonts: [
      { fontname: 'Verdana', fontheight: 12, fontweight: 700 },
    ],

    customColors: [
      { r: 0, g: 0, b: 0 },
    ],

    fonts: {
      family: 'Tahoma',
      height: 16,
    },
  };
})();
