;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/DINKSDX_BLUE';

  skins['DINKSDX_BLUE'] = {
    name: 'dinksDX Blue',
    author: 'grayhaze.com',
    email: 'mail@grayhaze.com',
    url: 'http://grayhaze.com',
    generator: 'Stardock SkinStudio ver 3.0.0, Build 619  - http://www.skinstudio.net',
    editorNotes: 'This skin is Copyright �2003 grayhaze.com. Please seek permission from the author before modifying this skin for any purpose.',
    wbVersion: 400,
    basePath: BASE,

    personality: {
      buttoncount: 67,
      textalignment: 1,
      textshift: 60,
      textrightclip: 70,
      textshiftvert: 4,
      textbackground: '1',
      textback: 'dinksDX_Blue\\pro-titlebar-textback.bmp',
      txtbackleft: '10',
      txtbackright: '10',
      menubar: `${BASE}/MENU-BAR.BMP`,
      tileleftmenu: 0,
      tilerightmenu: 0,
      menulefttile: 2,
      menur: 255,
      menug: 255,
      menub: 255,
      activetextr: 255,
      activetextg: 255,
      activetextb: 255,
      inactivetextr: 102,
      inactivetextg: 102,
      inactivetextb: 102,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      top: `${BASE}/PRO-FRAME-TOP.BMP`,
      left: `${BASE}/MEDIA-FRAME-LEFT.BMP`,
      right: `${BASE}/MEDIA-FRAME-RIGHT.BMP`,
      bottom: `${BASE}/MEDIA-FRAME-BOTTOM.BMP`,
      toptopheight: 8,
      topbotheight: 8,
      lefttopheight: 22,
      leftbotheight: 17,
      righttopheight: 22,
      rightbotheight: 17,
      bottomtopheight: 35,
      bottombotheight: 30,
      topstretch: 0,
      leftstretch: 0,
      rightstretch: 0,
      bottomstretch: 0,
      anirate: 0,
      topframe: 2,
      leftframe: 2,
      rightframe: 2,
      bottomframe: 2,
      mouseover: 1,
      tripleimages: 1,
      soundenabled: 1,
      rollupsize: 55,
      rightclickaction: 4,
      tilemenu: 1,
      menuborders: `${BASE}/MENU-BORDER.BMP`,
      maxbordercutleft: '0',
      maxbordercutright: '0',
      maxbordercuttop: '0',
      maxbordercutbottom: '0',
      explorerbmp: `${BASE}/BACKGROUND-EXPLORER.BMP`,
      dialogbmp: `${BASE}/BACKGROUND-DIALOG.BMP`,
      doubleclickaction: '1',
      ignoredialogbitmap: '1',
      frontstring: '       ',
      usestran: 1,
      fadelinkedbuttons: 0,
      endstring: '',
      scripting: '1',
      scriptactivate: 'dinksDX_Blue\\pm-closeall.wbs',
      scriptdeactivate: 'dinksDX_Blue\\pm-closeall.wbs',
    },

    buttons: {
      trans: 1,
      bitmap: `${BASE}/BUTTONS.TGA`,
      topheight: 8,
      bottomheight: 9,
      leftwidth: 8,
      rightwidth: 9,
      mouseover: 1,
      normalfont: 6,
      pressedfont: 6,
      disabledfont: 6,
      focusfont: 7,
      defaultfont: 6,
      mouseoverfont: 7,
      normalcolour: '0',
      pressedcolour: '1',
      disabledcolour: '2',
      focuscolour: '1',
      defaultcolour: '0',
      mouseovercolour: '1',
      tile: '1',
      perpixel: '1',
      enhancedmode: '0',
      contentleft: '0',
      contentright: '0',
      contenttop: '0',
      smartsmallmargins: '1',
    },

    titleButtons: [
      { image: `${BASE}/MEDIA-TITLEBAR-TITLEBACK.BMP`, align: 5, xcoord: 5, ycoord: 0, action: -6, visibility: 19, visibility1: 26 },
      { align: 5, xcoord: 5, ycoord: 3, action: -3, width: 200, height: 12, visibility: 19, visibility1: 26, visibility2: 1, dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-VERSION.BMP`, align: 3, xcoord: 120, ycoord: 18, action: -1, visibility: 19, visibility1: 26 },
      { image: `${BASE}/MEDIA-TITLEBAR-MENU.BMP`, align: 3, xcoord: 117, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-SHOW.BMP`, align: 3, xcoord: 104, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-VIS.BMP`, align: 3, xcoord: 91, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-MINUS.BMP`, align: 3, xcoord: 75, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-VOLUME.BMP`, align: 3, xcoord: 62, ycoord: 17, action: 5, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav' },
      { image: `${BASE}/MEDIA-TITLEBAR-PLUS.BMP`, align: 3, xcoord: 49, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-NAME.BMP`, align: 2, xcoord: 5, ycoord: 18, action: -1, visibility: 19, visibility1: 26 },
      { image: `${BASE}/MEDIA-TITLEBAR-PREV.BMP`, align: 2, xcoord: 40, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-PLAY.BMP`, align: 2, xcoord: 53, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-PAUSE.BMP`, align: 2, xcoord: 66, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-STOP.BMP`, align: 2, xcoord: 79, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-NEXT.BMP`, align: 2, xcoord: 92, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/MEDIA-TITLEBAR-EJECT.BMP`, align: 2, xcoord: 105, ycoord: 17, action: -4, width: 12, height: 16, visibility: 19, visibility1: 26, insound: 'dinksDX_Blue\\media-press.wav', dllname: 'dinksDX_Blue\\WBAmp.dll' },
      { image: `${BASE}/0`, align: 4, xcoord: -59, ycoord: 22, action: -3, width: 64, height: 14, visibility: 1, visibility1: 19, dllname: 'dinksDX_Blue\\CClock.dll' },
      { image: `${BASE}/PRO-TITLEBAR-MYDOCS.BMP`, xcoord: 16, ycoord: 22, action: -4, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav', dllname: 'dinksDX_Blue\\AdvCmd.dll' },
      { image: `${BASE}/PRO-TITLEBAR-MYCOMP.BMP`, xcoord: 28, ycoord: 22, action: -4, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav', dllname: 'dinksDX_Blue\\AdvCmd.dll' },
      { image: `${BASE}/PRO-TITLEBAR-TEXTED.BMP`, xcoord: 40, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-CALC.BMP`, xcoord: 52, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-WEB.BMP`, xcoord: 64, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-MAIL.BMP`, xcoord: 76, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-MPLAY.BMP`, xcoord: 88, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-CONPAN.BMP`, xcoord: 100, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-SS.BMP`, align: 1, xcoord: 112, ycoord: 22, action: 10, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-LOCK.BMP`, align: 1, xcoord: 100, ycoord: 22, action: -4, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav', dllname: 'dinksDX_Blue\\AdvCmd.dll' },
      { image: `${BASE}/PRO-TITLEBAR-WBCONFIG.BMP`, align: 1, xcoord: 88, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-DISPROP.BMP`, align: 1, xcoord: 76, ycoord: 22, action: -4, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav', dllname: 'dinksDX_Blue\\AdvCmd.dll' },
      { image: `${BASE}/PRO-TITLEBAR-SHOWDESK.BMP`, align: 1, xcoord: 64, ycoord: 22, action: 5, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-TRANS.BMP`, align: 1, xcoord: 52, ycoord: 22, action: 25, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-SYSTRAY.BMP`, align: 1, xcoord: 40, ycoord: 22, action: 24, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { image: `${BASE}/PRO-TITLEBAR-SYSMENU.BMP`, align: 1, xcoord: 28, ycoord: 22, action: 12, visibility: 0, visibility1: 19, visibility2: 26, visibility3: 16, insound: 'dinksDX_Blue\\pro-click.wav' },
      { align: 8, xcoord: -21, ycoord: 3, action: 11, visibility: 0 },
      { image: `${BASE}/TITLEBAR-ICON.BMP`, align: 8, xcoord: -21, ycoord: 3, action: 12, visibility: 28 },
      { image: `${BASE}/TITLEBAR-MIN.BMP`, align: 1, xcoord: 56, ycoord: 1, action: 23, visibility: 22, visibility1: 20, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-MIN.BMP`, align: 1, xcoord: 38, ycoord: 1, action: 23, visibility: 22, visibility1: 21, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-MAX.BMP`, align: 1, xcoord: 38, ycoord: 1, action: 22, visibility: 4, visibility1: 20, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-RESTORE.BMP`, align: 1, xcoord: 38, ycoord: 1, action: 22, visibility: 3, visibility1: 20, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-CLOSE.BMP`, align: 1, xcoord: 20, ycoord: 1, action: 0, visibility: 0, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-HELP.BMP`, align: 1, xcoord: 74, ycoord: 1, action: 3, visibility: 13, visibility1: 22, visibility2: 20, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-HELP.BMP`, align: 1, xcoord: 56, ycoord: 1, action: 3, visibility: 13, visibility1: 22, visibility2: 21, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-HELP.BMP`, align: 1, xcoord: 38, ycoord: 1, action: 3, visibility: 13, visibility1: 23, visibility2: 21, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-HELP.BMP`, align: 1, xcoord: 56, ycoord: 1, action: 3, visibility: 13, visibility1: 20, visibility2: 23, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-AOTON.BMP`, align: 0, xcoord: 2, ycoord: 1, action: 6, width: NaN, height: NaN, visibility: 8, visibility1: 19, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-AOTOFF.BMP`, xcoord: 2, ycoord: 1, action: 6, visibility: 7, visibility1: 19, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-ROLLUP.BMP`, align: 0, xcoord: 20, ycoord: 1, action: 4, visibility: 6, visibility1: 19, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-UNROLL.BMP`, align: 0, xcoord: 20, ycoord: 1, action: 4, visibility: 5, visibility1: 19, insound: 'dinksDX_Blue\\titlebar-press.wav' },
      { image: `${BASE}/TITLEBAR-LAUNCH.BMP`, align: 0, xcoord: 38, ycoord: 1, action: -4, visibility: 19, insound: 'dinksDX_Blue\\titlebar-press.wav', dllname: 'dinksDX_Blue\\WBWinMenu.dll' },
      { image: `${BASE}/PRO-TITLEBAR-SHORTCUT.BMP`, xcoord: 6, ycoord: 22, action: -2, visibility: 19 },
      { image: `${BASE}/PRO-TITLEBAR-CONTROL.BMP`, align: 1, xcoord: 16, ycoord: 22, action: -2, visibility: 19 },
      { image: `${BASE}/PRO-CAPTION-MYDOCS.BMP`, align: 0, xcoord: 22, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-MYCOMP.BMP`, align: 0, xcoord: 34, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-TEXTED.BMP`, align: 0, xcoord: 46, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-CALC.BMP`, align: 0, xcoord: 58, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-WEB.BMP`, align: 0, xcoord: 70, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-MAIL.BMP`, align: 0, xcoord: 82, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-MPLAY.BMP`, align: 0, xcoord: 94, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-CONPAN.BMP`, align: 0, xcoord: 106, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-SS.BMP`, align: 1, xcoord: 106, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-LOCK.BMP`, align: 1, xcoord: 94, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-WBCONFIG.BMP`, align: 1, xcoord: 82, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-DISPROP.BMP`, align: 1, xcoord: 164, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-SHOWDESK.BMP`, align: 1, xcoord: 136, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-TRANS.BMP`, align: 1, xcoord: 112, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-SYSTRAY.BMP`, align: 1, xcoord: 117, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
      { image: `${BASE}/PRO-CAPTION-SYSMENU.BMP`, align: 1, xcoord: 94, ycoord: 13, action: -1, visibility: 1, visibility1: 19, visibility2: 26, visibility3: 16 },
    ],

    comboButton: {
      image: `${BASE}/COMBO-BUTTON.BMP`,
      bottomheight: 6,
      leftwidth: 1,
      rightwidth: 1,
      topheight: 6,
      tile: 1,
      mouseover: 1,
    },

    startButton: { image: `${BASE}/STARTBUTTON.BMP` },

    colors: {
      background: [0, 51, 102],
      appWorkspace: [102, 153, 204],
      window: [255, 255, 255],
      windowText: [0, 0, 0],
      menu: [238, 238, 238],
      menuText: [0, 0, 0],
      activeTitle: [51, 102, 153],
      inactiveTitle: [204, 204, 204],
      titleText: [255, 255, 255],
      activeBorder: [51, 102, 153],
      inactiveBorder: [204, 204, 204],
      windowFrame: [51, 51, 51],
      scrollbar: [77, 128, 179],
      buttonFace: [204, 204, 204],
      buttonShadow: [153, 153, 153],
      buttonText: [0, 0, 0],
      grayText: [153, 153, 153],
      highlight: [51, 102, 153],
      highlightText: [255, 255, 255],
      inactiveTitleText: [102, 102, 102],
      buttonHighlight: [221, 221, 221],
      infoWindow: [255, 255, 255],
      buttonLight: [255, 255, 255],
      buttonDarkShadow: [102, 102, 102],
      infoText: [0, 0, 0],
      gradientActiveTitle: [51, 102, 153],
      gradientInactiveTitle: [204, 204, 204],
      menuBar: [238, 238, 238],
      menuHighlight: [68, 119, 170],
    },

    subSkins: [
      { id: 'default', name: 'Blue (Default)' },
      {
        id: 'graphite',
        name: 'Graphite',
        colors: {
          background: [51, 51, 68],
          appWorkspace: [128, 128, 148],
          activeTitle: [96, 96, 116],
          activeBorder: [96, 96, 116],
          scrollbar: [118, 118, 138],
          highlight: [96, 96, 116],
          gradientActiveTitle: [96, 96, 116],
          menuHighlight: [106, 106, 126],
          windowFrame: [51, 51, 51],
        },
      },
      {
        id: 'green',
        name: 'Green',
        colors: {
          background: [0, 68, 51],
          appWorkspace: [102, 179, 153],
          activeTitle: [51, 128, 102],
          activeBorder: [51, 128, 102],
          scrollbar: [77, 153, 128],
          highlight: [51, 128, 102],
          gradientActiveTitle: [51, 128, 102],
          menuHighlight: [68, 145, 119],
          windowFrame: [34, 51, 42],
        },
      },
    ],

    customFonts: [
      { fontname: 'Tahoma', fontheight: 13, fontweight: 400, antialias: 1, underline: 0, drawingstyle: 0, shadowoffset: 0, italics: 0, shadowr: 0, shadowg: 0, shadowb: 0, fontangle: 0 },
      { fontname: 'Tahoma', fontheight: 13, fontweight: 400, antialias: 1, shadowoffset: 1, drawingstyle: 2, shadowr: 34, shadowg: 85, shadowb: 136, fontangle: 0 },
      { antialias: 1, fontname: 'Tahoma', fontheight: 13, fontweight: 700, drawingstyle: 2, shadowr: 34, shadowg: 85, shadowb: 136 },
      { fontname: 'Tahoma', fontheight: 13, fontweight: 700, drawingstyle: 0, underline: 0, italics: 0, antialias: 1, shadowoffset: 1, fontangle: 0 },
      { fontname: 'Arial', fontheight: 20, fontweight: 700, antialias: 1, fontangle: 0 },
      { fontname: 'Tahoma', fontheight: 13, antialias: 1, drawingstyle: 0, fontweight: 700, fontangle: 0, shadowoffset: 1 },
      { fontname: 'Tahoma', fontheight: 12, fontweight: 400, antialias: 1, underline: 0, drawingstyle: 0, shadowoffset: 0, italics: 0, shadowr: 0, shadowg: 0, shadowb: 0, fontangle: 0 },
      { fontname: 'Tahoma', fontheight: 12, fontweight: 400, antialias: 1, shadowoffset: 1, drawingstyle: 2, shadowr: 34, shadowg: 85, shadowb: 136 },
      { antialias: 1, fontname: 'Tahoma', fontheight: 13, fontweight: 700, drawingstyle: 2, shadowr: 34, shadowg: 85, shadowb: 136 },
      { antialias: 1, fontname: 'Tahoma', fontheight: 13, fontweight: 700 },
    ],

    customColors: [
      { r: 0, g: 0, b: 0 },
      { r: 255, g: 255, b: 255 },
      { r: 127, g: 127, b: 127 },
      { r: 230, g: 0, b: 0 },
    ],

    fonts: {
      family: 'Tahoma',
      height: 13,
      weight: 700,
      antialias: true,
    },
  };
})();
