;(function() {
  'use strict';
  const SZ = window.SZ || (window.SZ = {});
  const skins = SZ.skins || (SZ.skins = {});

  const BASE = 'skins/AQUARIUM';

  skins['AQUARIUM'] = {
    name: 'Aquarium',
    author: 'Johanne Chain� AKA Alexandrie',
    email: 'alexandrie@pixtudio.com',
    url: 'http://www.pixtudio.com',
    generator: 'SkinStudio ver 1.2.9, Build 385  - http://www.skinstudio.net',
    editorNotes: 'copyright Pixtudio.com',
    wbVersion: 200,
    basePath: BASE,

    personality: {
      buttoncount: 7,
      dynamicframe: 0,
      fadelinkedbuttons: 1,
      faderate: 250,
      textalignment: 0,
      textshift: 21,
      textrightclip: 73,
      textshiftvert: 2,
      top: `${BASE}/TOP.BMP`,
      left: `${BASE}/LEFT_.BMP`,
      right: `${BASE}/RIGHT_.BMP`,
      bottom: `${BASE}/BOTTOM_.BMP`,
      anirate: 300,
      topframe: 15,
      leftframe: 15,
      rightframe: 15,
      bottomframe: 15,
      toptopheight: 52,
      topbotheight: 109,
      lefttopheight: 27,
      leftbotheight: 6,
      righttopheight: 27,
      rightbotheight: 6,
      bottomtopheight: 0,
      bottombotheight: 0,
      topstretch: 1,
      leftstretch: 0,
      rightstretch: 0,
      bottomstretch: 1,
      menur: 129,
      menug: 118,
      menub: 94,
      activetextr: 255,
      activetextg: 255,
      activetextb: 255,
      inactivetextr: 210,
      inactivetextg: 219,
      inactivetextb: 223,
      menutextr: 0,
      menutextg: 0,
      menutextb: 0,
      menubar: `${BASE}/MENU.BMP`,
      tileleftmenu: 0,
      tilerightmenu: 0,
      tilemenu: 1,
      menulefttile: 0,
      menuborders: `${BASE}/MENUBORDER.BMP`,
      rightclickaction: 4,
      rollupsize: 33,
      mouseover: 1,
      tripleimages: 1,
      soundenabled: 1,
      explorerbmp: `${BASE}/EXPLORE.BMP`,
      dialogbmp: `${BASE}/DIALOG.BMP`,
      mdibmp: `${BASE}/MDI.BMP`,
    },

    buttons: {
      checkbutton: `${BASE}/CHECKBOX.BMP`,
      radiobutton: `${BASE}/RADIO.BMP`,
      bitmap: `${BASE}/BUTTON.BMP`,
      topheight: 5,
      bottomheight: 5,
      leftwidth: 5,
      rightwidth: 5,
      mouseover: 1,
      trans: 1,
      normalfont: 0,
      pressedfont: 0,
      disabledfont: 0,
      focusfont: 2,
      defaultfont: 2,
      mouseoverfont: 2,
      alpha: 254,
      framecount: 10,
      animtimerrate: 250,
      mouseenterstartframe: 4,
      mouseoverstartframe: 5,
      mouseoverstopframe: 9,
      mouseleavemode: 1,
    },

    titleButtons: [
      { align: 0, xcoord: 0, ycoord: 0, action: -3, width: 0, height: 0, dllname: 'anim.dll' },
      { image: `${BASE}/EXIT.BMP`, align: 1, xcoord: 22, ycoord: 6, action: 0, visibility: 0, insound: 'Aquarium\\close.wav' },
      { image: `${BASE}/MAX.BMP`, align: 1, xcoord: 40, ycoord: 6, action: 22, visibility: 20, insound: 'Aquarium\\Restore.wav' },
      { image: `${BASE}/MIN.BMP`, align: 1, xcoord: 58, ycoord: 6, action: 23, visibility: 22, insound: 'Aquarium\\Minimize.wav' },
      { align: 0, xcoord: 7, ycoord: 5, action: 11 },
      { image: `${BASE}/MAX.BMP`, align: 1, xcoord: 40, ycoord: 6, action: 22, alpha: 180, visibility: 21, insound: 'Aquarium\\Restore.wav' },
      { image: `${BASE}/MIN.BMP`, align: 1, xcoord: 58, ycoord: 6, action: 23, alpha: 180, visibility: 23, insound: 'Aquarium\\Minimize.wav' },
    ],

    comboButton: {
      image: `${BASE}/COMBO.BMP`,
      tile: 0,
      bottomheight: 4,
      leftwidth: 5,
      rightwidth: 3,
      topheight: 4,
    },

    taskButton: {
      image: `${BASE}/TASKS.BMP`,
      topheight: 5,
      bottomheight: 5,
      leftwidth: 5,
      rightwidth: 5,
      trans: 0,
    },

    progressBar: {
      image: `${BASE}/PROGRESS.BMP`,
      topheight: 2,
      bottomheight: 2,
      leftwidth: 3,
      rightwidth: 3,
      tile: 0,
      tilemode: 2,
    },

    tabControl: {
      image: `${BASE}/TABS.BMP`,
      topheight: 4,
      bottomheight: 3,
      leftwidth: 4,
      rightwidth: 4,
    },

    startButton: {},

    colors: {
      scrollbar: [176, 165, 141],
      background: [21, 31, 42],
      activeTitle: [0, 61, 93],
      inactiveTitle: [128, 117, 94],
      menu: [176, 165, 141],
      window: [255, 255, 255],
      windowFrame: [0, 0, 0],
      menuText: [0, 0, 0],
      windowText: [0, 0, 0],
      titleText: [255, 255, 255],
      activeBorder: [176, 165, 141],
      inactiveBorder: [176, 165, 141],
      appWorkspace: [0, 61, 93],
      highlight: [107, 180, 223],
      highlightText: [0, 0, 0],
      buttonFace: [176, 165, 141],
      buttonShadow: [148, 135, 107],
      grayText: [129, 124, 111],
      buttonText: [0, 0, 0],
      inactiveTitleText: [85, 77, 60],
      buttonHighlight: [190, 183, 167],
      buttonDarkShadow: [47, 40, 22],
      buttonLight: [199, 187, 163],
      infoText: [0, 0, 0],
      infoWindow: [222, 214, 190],
      buttonAlternateFace: [176, 165, 141],
      hotTrackingColor: [0, 0, 255],
      gradientActiveTitle: [0, 61, 93],
      gradientInactiveTitle: [128, 117, 94],
      menuHighlight: [129, 118, 94],
      menuBar: [129, 118, 94],
    },

    customFonts: [
      { fontangle: 0, antialias: 0, fontname: 'Comic Sans MS', fontheight: 14, italics: 0, underline: 0, fontweight: 400, shadowb: 128, shadowg: 128, shadowr: 128, shadowoffset: 1, drawingstyle: 0 },
      { fontangle: 0, antialias: 0, fontname: 'Comic Sans MS', fontheight: 14, italics: 0, underline: 0, fontweight: 600, shadowb: 111, shadowg: 82, shadowr: 47, shadowoffset: 2, drawingstyle: 1 },
      { fontangle: 0, antialias: 0, fontname: 'Comic Sans MS', fontheight: 14, italics: 0, underline: 0, fontweight: 400, shadowb: 120, shadowg: 137, shadowr: 145, shadowoffset: 1, drawingstyle: 1 },
      { fontangle: 0, antialias: 0, fontname: 'Comic Sans MS', fontheight: 14, italics: 0, underline: 0, fontweight: 600, shadowb: 47, shadowg: 148, shadowr: 200, shadowoffset: 1, drawingstyle: 1 },
      { fontangle: 0, antialias: 0, fontname: 'Comic Sans MS', fontheight: 14, italics: 0, underline: 0, fontweight: 600, shadowb: 123, shadowg: 151, shadowr: 164, shadowoffset: 2, drawingstyle: 1 },
      { fontangle: 0, antialias: 0, fontname: 'Comic Sans MS', fontheight: 16, italics: 0, underline: 0, fontweight: 600, shadowb: 165, shadowg: 129, shadowr: 73, shadowoffset: 1, drawingstyle: 2 },
      { fontangle: 0, antialias: 1, fontname: 'Arial', fontheight: 35, italics: 0, underline: 0, fontweight: 800, shadowb: 141, shadowg: 165, shadowr: 176, shadowoffset: 4, drawingstyle: 1 },
    ],

    customColors: [
      { r: 0, g: 0, b: 0 },
      { r: 128, g: 128, b: 128 },
      { r: 255, g: 255, b: 255 },
    ],

    fonts: {
      family: 'Comic Sans MS',
      height: 16,
      weight: 600,
    },
  };
})();
